// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("$lib/intl").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "account": {
      "title": "نقل الحساب",
      "description": "قام شخص ما بإنشاء هذا الحساب وينقله إليك الآن.",
      "accept": "قبول الحساب",
      "content0": "لتولي ملكية الحساب، قم بإعداد تفاصيل تسجيل الدخول الخاصة بك. لن يؤدي هذا إلى إنشاء حساب جديد — بل يمنحك فقط الوصول إلى هذا الحساب.",
      "content1": "هذا لن ينشئ حسابًا جديدًا — بل سيسمح لك فقط بالوصول إلى هذا الحساب وإدارته.",
      "conflict": {
        "content0": (name) => `${name}، لقبول هذا الحساب، سيتم تسجيل خروجك من حسابك الحالي وستحتاج إلى إعداد تفاصيل تسجيل دخول جديدة.`,
        "content1": "لن يؤدي هذا إلى دمج الحسابات — بل ستنتقل إلى الحساب الجديد."
      },
      "switch": "تبديل الحساب",
      "expired": {
        "content": "اطلب من المُرسِل إنشاء رابط جديد.",
        "description": "انتهت صلاحية طلب التحويل هذا.",
        "title": "انتهت صلاحية النقل"
      },
      "og": {
        "tile": "استلم التحكم في حسابك على Evnly.",
        "description": (name) => `${name}، تم إنشاء هذا الحساب لك. أنشئ بيانات تسجيل الدخول لتصبح المالك.`
      }
    },
    "actions": {
      "discard": "تجاهل",
      "close": "إغلاق"
    },
    "friends": {
      "app": {
        "description": "الطريقة الذكية لمتابعة من مدين لمن، مع الأصدقاء معاً."
      },
      "inviter": {
        "description": (name) => `لقد تمت دعوتك من قبل ${name}. فقط سجّل أو قم بتسجيل الدخول، وستكون جاهزًا!`
      },
      "accept": "ابدأ استخدام Evnly",
      "og": {
        "description": "تابع المصاريف المشتركة، ووزّع التكاليف، وابقَ متزامنًا — معًا على Evnly.",
        "title": (name) => `انضم إلى ${name} على Evnly`
      },
      "dialog": {
        "title": "تواصل على إيفنلي",
        "description": "سجّل الدخول أو أنشئ حسابًا للمتابعة.",
        "accept": "اتصل",
        "decline": "ليس الآن",
        "content": (name) => `${name} يرغب في التواصل معك عبر Evnly لتتبع النفقات المشتركة.`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `انضم إلى ${groupName} على Evnly`,
        "description": (names) => `قسّم المصاريف مع ${new Intl.ListFormat("ar", { style: "long", type: "conjunction" }).format(names)}`
      },
      "dialog": {
        "title": (groupname) => `انضم إلى ${groupname}`,
        "join": "انضم",
        "decline": "رفض"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `انضم إلى ${title} عبر Evnly`,
        "description": "شارك مصاريف المغامرة وتابع الحسابات بالتساوي — معًا على Evnly."
      },
      "dialog": {
        "title": (title) => `انضم إلى ${title}`,
        "join": "انضمام",
        "decline": "تجاهل",
        "description": (name, gender) => gender === "he" ? `${name} يدعوك للانضمام إلى المغامرة` : gender === "she" ? `${name} تدعوك للانضمام إلى المغامرة` : `${name} يدعوك/تدعوك للانضمام إلى المغامرة`,
        "heading": "دعوة إلى المغامرة"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `انضم إلى ${title} على Evnly`,
        "description": "اقسم الفاتورة وتابع من الذي يدين لمن — معًا على إيڤنلي."
      },
      "dialog": {
        "join": "انضمام",
        "decline": "رفض",
        "title": "دعوة لتقسيم الفاتورة",
        "description": (name, gender) => gender === "he" ? `${name} يدعوك لتقسيم الفاتورة` : gender === "she" ? `${name} تدعوك لتقسيم الفاتورة` : `${name} يدعوك/تدعوك لتقسيم الفاتورة`,
        "balance": {
          "total": "إجمالي الفاتورة"
        }
      }
    }
  },
  "de-DE": {
    "account": {
      "title": "Kontenübertrag",
      "description": "Jemand hat dieses Konto erstellt und überträgt es nun an dich.",
      "accept": "Konto akzeptieren",
      "content0": "Um die Inhaberschaft zu übernehmen, richte bitte deine Anmeldedaten ein. Dadurch wird kein neues Konto erstellt – du erhältst nur Zugriff auf dieses Konto.",
      "content1": "Dadurch wird kein neues Konto erstellt – du bekommst lediglich Zugriff auf dieses und kannst es verwalten.",
      "conflict": {
        "content0": (name) => `${name}, um dieses Konto zu akzeptieren, wirst du von deinem aktuellen Konto abgemeldet und musst neue Anmeldedaten festlegen.`,
        "content1": "Dadurch werden die Konten nicht zusammengeführt – du wechselst einfach zum neuen Konto."
      },
      "switch": "Konto wechseln",
      "expired": {
        "content": "Bitte den Absender, einen neuen Link zu erstellen.",
        "description": "Diese Überweisungsanfrage ist abgelaufen.",
        "title": "Übertragung abgelaufen"
      },
      "og": {
        "tile": "Übernimm dein Evnly.",
        "description": (name) => `${name}, dieses Konto wurde für dich erstellt. Übernimm es, indem du deine Anmeldedaten festlegst.`
      }
    },
    "actions": {
      "discard": "Ablehnen",
      "close": "Schließen"
    },
    "friends": {
      "app": {
        "description": "Die clevere Art, gemeinsam mit Freunden zu verfolgen, wer wem etwas schuldet."
      },
      "inviter": {
        "description": (name) => `${name} hat dich eingeladen. Registriere dich einfach oder melde dich an und schon kann es losgehen!`
      },
      "accept": "Evnly jetzt nutzen",
      "og": {
        "description": "Geteilte Ausgaben verfolgen, Kosten aufteilen und immer abgestimmt bleiben – gemeinsam auf Evnly.",
        "title": (name) => `Tritt ${name} auf Evnly bei`
      },
      "dialog": {
        "title": "Auf Evnly verbinden",
        "description": "Melden Sie sich an oder erstellen Sie ein Konto, um fortzufahren.",
        "accept": "Verbinden",
        "decline": "Nicht jetzt",
        "content": (name) => `${name} möchte sich auf Evnly mit dir verbinden, um gemeinsame Ausgaben zu verfolgen.`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `Tritt ${groupName} auf Evnly bei`,
        "description": (names) => `Teile die Ausgaben mit ${new Intl.ListFormat("de", { style: "long", type: "conjunction" }).format(names)}`
      },
      "dialog": {
        "title": (groupname) => `Tritt ${groupname} bei`,
        "join": "Beitreten",
        "decline": "Ablehnen"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `Tritt ${title} auf Evnly bei`,
        "description": "Teilt eure Abenteuerkosten und behaltet den Überblick – gemeinsam auf Evnly."
      },
      "dialog": {
        "title": (title) => `Tritt ${title} bei`,
        "join": "Beitreten",
        "decline": "Ignorieren",
        "description": (name, gender) => `${name} lädt dich zum Abenteuer ein`,
        "heading": "Einladung zum Abenteuer"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `Tritt ${title} auf Evnly bei`,
        "description": "Teilt eine Rechnung und verfolgt, wer wem wie viel schuldet – gemeinsam auf Evnly."
      },
      "dialog": {
        "join": "Beitreten",
        "decline": "Ablehnen",
        "title": "Einladung, die Rechnung zu teilen",
        "description": (name, gender) => `${name} lädt dich ein, eine Rechnung zu teilen`,
        "balance": {
          "total": "Gesamtrechnung"
        }
      }
    }
  },
  "en-US": {
    "account": {
      "title": "Account Transfer",
      "description": "Someone has created this account and is transferring it to you.",
      "accept": "Accept account",
      "content0": "To take ownership, set up your sign-in details. This won’t create a new account — it just gives you access to this one.",
      "content1": "This won’t create a new account — it will simply let you access and manage this one.",
      "conflict": {
        "content0": (name) => `${name}, to accept this account, you’ll be signed out of your current one and set up new sign-in details.`,
        "content1": "This won’t merge accounts — you’ll switch to the new one."
      },
      "switch": "Switch account",
      "expired": {
        "content": "Ask the sender to generate a new link.",
        "description": "This transfer request has expired.",
        "title": "Transfer Expired"
      },
      "og": {
        "tile": "Take over your account on Evnly.",
        "description": (name) => `${name}, this account was created for you. Take ownership by setting up sign-in details.`
      }
    },
    "actions": {
      "discard": "Discard",
      "close": "Close"
    },
    "friends": {
      "app": {
        "description": "The smart way to track who owes whom, together with friends."
      },
      "inviter": {
        "description": (name) => `You have been invited by ${name}. Just register or log in, and you’re all set`
      },
      "accept": "Start Using Evnly",
      "og": {
        "description": "Track shared expenses, split costs, and stay in sync — together on Evnly.",
        "title": (name) => `Join ${name} on Evnly`
      },
      "dialog": {
        "title": "Connect on Evnly",
        "description": "Sign in or create an account to continue.",
        "accept": "Connect",
        "decline": "Not now",
        "content": (name) => `${name} wants to connect with you on Evnly to track shared expenses.`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `Join ${groupName} on Evnly`,
        "description": (names) => `Split expenses with ${new Intl.ListFormat("en", { style: "long", type: "conjunction" }).format(names)}`
      },
      "dialog": {
        "title": (groupname) => `Join ${groupname}`,
        "join": "Join",
        "decline": "Decline"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `Join ${title} on Evnly`,
        "description": "Share adventure expenses and keep equal tabs — together on Evnly."
      },
      "dialog": {
        "title": (title) => `Join ${title}`,
        "join": "Join",
        "decline": "Ignore",
        "description": (name, gender) => `${name} invites you to join the adventure`,
        "heading": "Invitation to the adventure"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `Join ${title} on Evnly`,
        "description": "Split a receipt and track who owes whom — together on Evnly."
      },
      "dialog": {
        "join": "Join",
        "decline": "Decline",
        "title": "Invitation to split a bill",
        "description": (name, gender) => `${name} invites you to split a bill`,
        "balance": {
          "total": "Total bill"
        }
      }
    }
  },
  "es-ES": {
    "account": {
      "title": "Transferencia de cuenta",
      "description": "Alguien ha creado esta cuenta y te la está transfiriendo.",
      "accept": "Aceptar cuenta",
      "content0": "Para tomar posesión, configura tus datos de inicio de sesión. Esto no creará una cuenta nueva, solo te da acceso a esta.",
      "content1": "Esto no creará una nueva cuenta; simplemente te permitirá acceder y gestionar esta.",
      "conflict": {
        "content0": (name) => `${name}, para aceptar esta cuenta, cerrarás sesión en la actual y se configurarán nuevos datos de acceso.`,
        "content1": "Esto no fusionará las cuentas; solo cambiarás a la nueva."
      },
      "switch": "Cambiar de cuenta",
      "expired": {
        "content": "Pide al remitente que genere un nuevo enlace.",
        "description": "Esta solicitud de transferencia ha caducado.",
        "title": "Transferencia caducada"
      },
      "og": {
        "tile": "Toma el control de tu cuenta en Evnly.",
        "description": (name) => `${name}, esta cuenta fue creada para ti. Hazla tuya configurando tus datos de acceso.`
      }
    },
    "actions": {
      "discard": "Descartar",
      "close": "Cerrar"
    },
    "friends": {
      "app": {
        "description": "La forma inteligente de llevar un registro de quién debe a quién, junto a tus amigos."
      },
      "inviter": {
        "description": (name) => `Has sido invitado por ${name}. Solo regístrate o inicia sesión, ¡y listo!`
      },
      "accept": "Comienza a usar Evnly",
      "og": {
        "description": "Lleva el control de los gastos compartidos, divide los costes y mantente sincronizado, todo juntos en Evnly.",
        "title": (name) => `Únete a ${name} en Evnly`
      },
      "dialog": {
        "title": "Conéctate en Evnly",
        "description": "Inicia sesión o crea una cuenta para continuar.",
        "accept": "Conectar",
        "decline": "Ahora no",
        "content": (name) => `${name} quiere conectar contigo en Evnly para llevar un seguimiento de los gastos compartidos.`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `Únete a ${groupName} en Evnly`,
        "description": (names) => `Divide los gastos con ${new Intl.ListFormat("es", { style: "long", type: "conjunction" }).format(names)}`
      },
      "dialog": {
        "title": (groupname) => `Únete a ${groupname}`,
        "join": "Unirse",
        "decline": "Rechazar"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `Únete a ${title} en Evnly`,
        "description": "Comparte los gastos de aventura y lleva cuentas iguales — juntos en Evnly."
      },
      "dialog": {
        "title": (title) => `Unirse a ${title}`,
        "join": "Unirse",
        "decline": "Ignorar",
        "description": (name, gender) => `${name} te invita a unirte a la aventura`,
        "heading": "Invitación a la aventura"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `Únete a ${title} en Evnly`,
        "description": "Divide un recibo y lleva el control de quién le debe a quién, todo juntos en Evnly."
      },
      "dialog": {
        "join": "Unirse",
        "decline": "Rechazar",
        "title": "Invitación a dividir la cuenta",
        "description": (name, gender) => gender === "he" ? `${name} te invita a dividir una cuenta` : gender === "she" ? `${name} te invita a dividir una cuenta` : `${name} te invita a dividir una cuenta`,
        "balance": {
          "total": "Total de la cuenta"
        }
      }
    }
  },
  "fr-FR": {
    "account": {
      "title": "Transfert de compte",
      "description": "Quelqu’un a créé ce compte et est en train de vous le transférer.",
      "accept": "Accepter le compte",
      "content0": "Pour prendre la main, configurez vos identifiants de connexion. Cela ne créera pas un nouveau compte — cela vous donnera simplement accès à celui-ci.",
      "content1": "Cela ne créera pas un nouveau compte — cela vous permettra simplement d'accéder à celui-ci et de le gérer.",
      "conflict": {
        "content0": (name) => `${name}, pour accepter ce compte, vous serez déconnecté de votre compte actuel et devrez définir de nouvelles informations de connexion.`,
        "content1": "Cela ne fusionnera pas les comptes — vous passerez simplement au nouveau."
      },
      "switch": "Changer de compte",
      "expired": {
        "content": "Demandez à l'expéditeur de générer un nouveau lien.",
        "description": "Cette demande de transfert a expiré.",
        "title": "Transfert expiré"
      },
      "og": {
        "tile": "Prenez le contrôle de votre compte Evnly.",
        "description": (name) => `${name}, ce compte a été créé pour vous. Prenez-en possession en configurant vos identifiants de connexion.`
      }
    },
    "actions": {
      "discard": "Ignorer",
      "close": "Fermer"
    },
    "friends": {
      "app": {
        "description": "La façon intelligente de suivre qui doit quoi à qui, ensemble avec des amis."
      },
      "inviter": {
        "description": (name) => `Vous avez été invité par ${name}. Inscrivez-vous ou connectez-vous, et tout est prêt !`
      },
      "accept": "Commencer à utiliser Evnly",
      "og": {
        "description": "Gérez vos dépenses partagées, répartissez les coûts et restez synchronisés — ensemble sur Evnly.",
        "title": (name) => `Rejoins ${name} sur Evnly`
      },
      "dialog": {
        "title": "Connectez-vous sur Evnly",
        "description": "Connectez-vous ou créez un compte pour continuer.",
        "accept": "Se connecter",
        "decline": "Pas maintenant",
        "content": (name) => `${name} souhaite se connecter avec vous sur Evnly pour suivre les dépenses partagées.`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `Rejoignez ${groupName} sur Evnly`,
        "description": (names) => `Partagez les dépenses avec ${new Intl.ListFormat("fr", { style: "long", type: "conjunction" }).format(names)}`
      },
      "dialog": {
        "title": (groupname) => `Rejoindre ${groupname}`,
        "join": "Rejoindre",
        "decline": "Refuser"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `Rejoignez ${title} sur Evnly`,
        "description": "Partagez les frais d’aventure et gardez un suivi équitable — ensemble sur Evnly."
      },
      "dialog": {
        "title": (title) => `Rejoindre ${title}`,
        "join": "Rejoindre",
        "decline": "Ignorer",
        "description": (name, gender) => gender === "he" ? `${name} t’invite à rejoindre l’aventure` : gender === "she" ? `${name} t’invite à rejoindre l’aventure` : `${name} t’invite à rejoindre l’aventure`,
        "heading": "Invitation à l’aventure"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `Rejoindre ${title} sur Evnly`,
        "description": "Partagez une note et suivez qui doit quoi à qui — ensemble sur Evnly."
      },
      "dialog": {
        "join": "Rejoindre",
        "decline": "Refuser",
        "title": "Invitation à partager l’addition",
        "description": (name, gender) => gender === "he" ? `${name} vous invite à partager une addition` : gender === "she" ? `${name} vous invite à partager une addition` : `${name} vous invite à partager une addition`,
        "balance": {
          "total": "Total de la facture"
        }
      }
    }
  },
  "hi-IN": {
    "account": {
      "title": "खाता स्थानांतरण",
      "description": "किसी ने यह खाता बनाया है और इसे आपके नाम स्थानांतरित कर रहा है।",
      "accept": "खाता स्वीकार करें",
      "content0": "अधिकार प्राप्त करने के लिए, अपने साइन-इन विवरण सेट करें। इससे नया खाता नहीं बनेगा — यह सिर्फ आपको इसी खाते तक पहुँच देगा।",
      "content1": "इससे नया खाता नहीं बनेगा — यह सिर्फ आपको इस खाते तक पहुँचने और इसे प्रबंधित करने देगा।",
      "conflict": {
        "content0": (name) => `${name}, इस खाते को स्वीकार करने के लिए, आपको अपने वर्तमान खाते से साइन आउट किया जाएगा और नए साइन-इन विवरण सेट करने होंगे।`,
        "content1": "इससे खाते मर्ज नहीं होंगे — आप नए खाते पर स्विच करेंगे।"
      },
      "switch": "खाता बदलें",
      "expired": {
        "content": "प्रेषक से नया लिंक बनाने के लिए कहें।",
        "description": "इस ट्रांसफ़र अनुरोध की अवधि समाप्त हो गई है।",
        "title": "स्थानांतरण की अवधि समाप्त"
      },
      "og": {
        "tile": "Evnly पर अपने खाते का नियंत्रण संभालें।",
        "description": (name) => `${name}, यह खाता आपके लिए बनाया गया है। साइन-इन विवरण सेट करके स्वामित्व लें।`
      }
    },
    "actions": {
      "discard": "अस्वीकार करें",
      "close": "बंद करें"
    },
    "friends": {
      "app": {
        "description": "दोस्तों के साथ मिलकर यह जानने का स्मार्ट तरीका कि किसका किस पर कितना बकाया है।"
      },
      "inviter": {
        "description": (name) => `${name} ने आपको आमंत्रित किया है। बस रजिस्टर करें या लॉग इन करें, और आप तैयार हैं!`
      },
      "accept": "Evnly का उपयोग शुरू करें",
      "og": {
        "description": "साझा खर्च ट्रैक करें, खर्चों को बांटें, और हमेशा साथ रहें — Evnly पर मिलकर।",
        "title": (name) => `${name} के साथ Evnly पर जुड़ें`
      },
      "dialog": {
        "title": "Evnly पर कनेक्ट करें",
        "description": "जारी रखने के लिए साइन इन करें या एक खाता बनाएं।",
        "accept": "कनेक्ट करें",
        "decline": "अभी नहीं",
        "content": (name) => `${name} Evnly पर आपके साथ जुड़ना चाहता है ताकि साझा खर्च ट्रैक कर सकें।`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `Evnly पर ${groupName} से जुड़ें`,
        "description": (names) => `${new Intl.ListFormat("hi", { style: "long", type: "conjunction" }).format(names)} के साथ खर्च बाँटे`
      },
      "dialog": {
        "title": (groupname) => `${groupname} से जुड़ें`,
        "join": "जुड़ें",
        "decline": "अस्वीकृत करें"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `Evnly पर ${title} से जुड़ें`,
        "description": "एडवेंचर के खर्च साझा करें और बराबर हिसाब रखें — Evnly पर एक साथ।"
      },
      "dialog": {
        "title": (title) => `${title} से जुड़ें`,
        "join": "शामिल हों",
        "decline": "अनदेखा करें",
        "description": (name, gender) => gender === "he" ? `${name} आपको रोमांच में शामिल होने के लिए आमंत्रित करता है` : gender === "she" ? `${name} आपको रोमांच में शामिल होने के लिए आमंत्रित करती है` : `${name} आपको रोमांच में शामिल होने के लिए आमंत्रित करता/करती है`,
        "heading": "साहसिक यात्रा के लिए निमंत्रण"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `Evnly पर ${title} से जुड़ें`,
        "description": "रसीद को बाँटें और किसने किसे कितना देना है, यह ट्रैक करें — सब एक साथ Evnly पर।"
      },
      "dialog": {
        "join": "जुड़ें",
        "decline": "अस्वीकार करें",
        "title": "बिल साझा करने का निमंत्रण",
        "description": (name, gender) => gender === "he" ? `${name} आपको बिल साझा करने के लिए आमंत्रित करता है` : gender === "she" ? `${name} आपको बिल साझा करने के लिए आमंत्रित करती है` : `${name} आपको बिल साझा करने के लिए आमंत्रित करता/करती है`,
        "balance": {
          "total": "कुल बिल"
        }
      }
    }
  },
  "it-IT": {
    "account": {
      "title": "Trasferimento account",
      "description": "Qualcuno ha creato questo account e lo sta trasferendo a te.",
      "accept": "Accetta account",
      "content0": "Per assumere la proprietà, imposta i tuoi dettagli di accesso. Questo non creerà un nuovo account — ti darà solo accesso a questo.",
      "content1": "Questo non creerà un nuovo account — ti permetterà semplicemente di accedere e gestire questo.",
      "conflict": {
        "content0": (name) => `${name}, per accettare questo account, verrai disconnesso dal tuo attuale e dovrai impostare nuove credenziali di accesso.`,
        "content1": "Questo non unirà gli account: passerai semplicemente a quello nuovo."
      },
      "switch": "Cambia account",
      "expired": {
        "content": "Chiedi al mittente di generare un nuovo link.",
        "description": "Questa richiesta di trasferimento è scaduta.",
        "title": "Trasferimento scaduto"
      },
      "og": {
        "tile": "Prendi il controllo del tuo account su Evnly.",
        "description": (name) => `${name}, questo account è stato creato per te. Prendine possesso impostando i tuoi dati di accesso.`
      }
    },
    "actions": {
      "discard": "Rifiuta",
      "close": "Chiudi"
    },
    "friends": {
      "app": {
        "description": "Il modo intelligente per tenere traccia di chi deve cosa a chi, insieme agli amici."
      },
      "inviter": {
        "description": (name) => `Sei stato invitato da ${name}. Registrati o accedi, ed è tutto pronto!`
      },
      "accept": "Inizia a usare Evnly",
      "og": {
        "description": "Tieni traccia delle spese condivise, dividi i costi e rimani sincronizzato — insieme su Evnly.",
        "title": (name) => `Unisciti a ${name} su Evnly`
      },
      "dialog": {
        "title": "Connettiti su Evnly",
        "description": "Accedi o crea un account per continuare.",
        "accept": "Connetti",
        "decline": "Non ora",
        "content": (name) => `${name} vuole connettersi con te su Evnly per tenere traccia delle spese condivise.`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `Unisciti a ${groupName} su Evnly`,
        "description": (names) => `Dividi le spese con ${new Intl.ListFormat("it", { style: "long", type: "conjunction" }).format(names)}`
      },
      "dialog": {
        "title": (groupname) => `Unisciti a ${groupname}`,
        "join": "Unisciti",
        "decline": "Rifiuta"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `Unisciti a ${title} su Evnly`,
        "description": "Dividi le spese d’avventura e tieni i conti in pari — insieme su Evnly."
      },
      "dialog": {
        "title": (title) => `Unisciti a ${title}`,
        "join": "Partecipa",
        "decline": "Ignora",
        "description": (name, gender) => `${name} ti invita a unirti all’avventura`,
        "heading": "Invito all’avventura"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `Unisciti a ${title} su Evnly`,
        "description": "Dividi uno scontrino e tieni traccia di chi deve cosa a chi — tutto insieme su Evnly."
      },
      "dialog": {
        "join": "Unisciti",
        "decline": "Rifiuta",
        "title": "Invito a dividere il conto",
        "description": (name, gender) => gender === "he" ? `${name} ti invita a dividere un conto` : gender === "she" ? `${name} ti invita a dividere un conto` : `${name} ti invita a dividere un conto`,
        "balance": {
          "total": "Totale conto"
        }
      }
    }
  },
  "ja-JP": {
    "account": {
      "title": "アカウントの移行",
      "description": "誰かがこのアカウントを作成し、あなたに譲渡しています。",
      "accept": "アカウントを承認",
      "content0": "所有権を取得するには、サインイン情報を設定してください。新しいアカウントは作成されません — このアカウントにアクセスできるようになるだけです。",
      "content1": "新しいアカウントは作成されません。このアカウントにアクセスして管理できるようになるだけです。",
      "conflict": {
        "content0": (name) => `${name}、このアカウントを承認するには、現在のアカウントからサインアウトし、新しいサインイン情報を設定する必要があります。`,
        "content1": "これでアカウントが統合されることはありません。新しいアカウントに切り替わります。"
      },
      "switch": "アカウントを切り替える",
      "expired": {
        "content": "送信者に新しいリンクを生成するよう依頼してください。",
        "description": "この送金リクエストの有効期限が切れました。",
        "title": "転送の有効期限が切れました"
      },
      "og": {
        "tile": "Evnlyのアカウントを引き継ぐ。",
        "description": (name) => `${name}さん、このアカウントはあなたのために作成されました。サインイン情報を設定してご自身のものにしてください。`
      }
    },
    "actions": {
      "discard": "破棄",
      "close": "閉じる"
    },
    "friends": {
      "app": {
        "description": "友達と一緒に、誰が誰にいくら借りているかをスマートに管理する方法。"
      },
      "inviter": {
        "description": (name) => `${name}さんから招待されています。登録またはログインするだけで、すぐにご利用いただけます。`
      },
      "accept": "Evnly を使い始める",
      "og": {
        "description": "共有の支出を管理し、費用を分担し、みんなで常に連携——Evnlyで一緒に。",
        "title": (name) => `Evnlyで${name}に参加しよう`
      },
      "dialog": {
        "title": "Evnlyでつながる",
        "description": "続行するにはサインインするかアカウントを作成してください。",
        "accept": "接続",
        "decline": "今はしない",
        "content": (name) => `${name}さんがEvnlyであなたとつながり、共有した支出を管理したいと考えています。`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `Evnlyで${groupName}に参加する`,
        "description": (names) => `${new Intl.ListFormat("ja", { style: "long", type: "conjunction" }).format(names)}と費用を分割する`
      },
      "dialog": {
        "title": (groupname) => `${groupname}に参加する`,
        "join": "参加する",
        "decline": "辞退する"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `Evnlyで${title}に参加しよう`,
        "description": "冒険の費用をみんなで分けて、公平に管理しよう — Evnlyで一緒に。"
      },
      "dialog": {
        "title": (title) => `${title}に参加`,
        "join": "参加",
        "decline": "無視",
        "description": (name, gender) => `${name}が冒険にあなたを招待しています`,
        "heading": "冒険への招待"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `Evnlyで${title}に参加する`,
        "description": "領収書を分けて、誰が誰にいくら借りているかをEvnyで一緒に管理しましょう。"
      },
      "dialog": {
        "join": "参加する",
        "decline": "拒否",
        "title": "割り勘への招待",
        "description": (name, gender) => `${name}さんが割り勘をしませんかと招待しています`,
        "balance": {
          "total": "合計請求額"
        }
      }
    }
  },
  "ko-KR": {
    "account": {
      "title": "계정 이전",
      "description": "누군가 이 계정을 만들었으며 지금 당신에게 이전하고 있습니다.",
      "accept": "계정 승인",
      "content0": "소유권을 가져오려면 로그인 정보를 설정하세요. 이것은 새 계정을 만드는 것이 아니라, 이 계정에 대한 접근 권한만 부여합니다.",
      "content1": "새 계정을 만들지는 않습니다. 이 계정에 접근하고 관리할 수 있게 해줍니다.",
      "conflict": {
        "content0": (name) => `${name}님, 이 계정을 승인하려면 현재 계정에서 로그아웃하고 새로운 로그인 정보를 설정해야 합니다.`,
        "content1": "계정이 병합되지 않습니다 — 새 계정으로 전환됩니다."
      },
      "switch": "계정 전환",
      "expired": {
        "content": "보내는 사람에게 새 링크를 생성해 달라고 요청하세요.",
        "description": "이체 요청이 만료되었습니다.",
        "title": "전송 만료됨"
      },
      "og": {
        "tile": "Evnly에서 계정을 인수하세요.",
        "description": (name) => `${name}님, 이 계정은 회원님을 위해 생성되었습니다. 로그인 정보를 설정하여 소유권을 가져가세요.`
      }
    },
    "actions": {
      "discard": "버리기",
      "close": "닫기"
    },
    "friends": {
      "app": {
        "description": "친구들과 함께 누가 누구에게 얼마를 빚졌는지 스마트하게 관리하는 방법."
      },
      "inviter": {
        "description": (name) => `${name}님이 초대하셨습니다. 가입하거나 로그인하면 바로 시작할 수 있어요!`
      },
      "accept": "Evnly 시작하기",
      "og": {
        "description": "공동 지출을 기록하고, 비용을 나누며, 항상 함께 맞춰보세요 — Evnly에서 같이.",
        "title": (name) => `Evnly에서 ${name}와 함께해요`
      },
      "dialog": {
        "title": "Evnly에서 연결하기",
        "description": "계속하려면 로그인하거나 계정을 생성하세요.",
        "accept": "연결",
        "decline": "지금은 아니에요",
        "content": (name) => `${name}님이 Evnly에서 함께 연결해 공동 지출을 관리하고 싶어합니다.`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `Evnly에서 ${groupName}에 참여하세요`,
        "description": (names) => `${new Intl.ListFormat("ko", { style: "long", type: "conjunction" }).format(names)}와(과) 비용을 나누세요`
      },
      "dialog": {
        "title": (groupname) => `${groupname}에 가입하기`,
        "join": "참여하기",
        "decline": "거절"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `Evnly에서 ${title}에 참여하세요`,
        "description": "모험 경비를 함께 나누고 공평하게 정산하세요 — Evnly에서 함께해요."
      },
      "dialog": {
        "title": (title) => `${title} 참가하기`,
        "join": "참여하기",
        "decline": "무시",
        "description": (name, gender) => `${name}님이 모험에 초대합니다`,
        "heading": "모험으로의 초대"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `Evnly에서 ${title}에 참여하세요`,
        "description": "영수증을 나누고 누가 누구에게 얼마를 빚졌는지 함께 Evnly에서 확인하세요."
      },
      "dialog": {
        "join": "참여하기",
        "decline": "거절",
        "title": "더치페이 초대",
        "description": (name, gender) => `${name}님이 더치페이를 제안합니다`,
        "balance": {
          "total": "총 청구 금액"
        }
      }
    }
  },
  "nl-NL": {
    "account": {
      "title": "Accountoverdracht",
      "description": "Iemand heeft dit account aangemaakt en draagt het nu aan jou over.",
      "accept": "Account accepteren",
      "content0": "Om eigenaar te worden, stel je je inloggegevens in. Er wordt geen nieuw account aangemaakt — je krijgt alleen toegang tot dit account.",
      "content1": "Dit maakt geen nieuw account aan — het geeft je alleen toegang tot en beheer over dit account.",
      "conflict": {
        "content0": (name) => `${name}, om dit account te accepteren, word je afgemeld van je huidige account en stel je nieuwe inloggegevens in.`,
        "content1": "Dit voegt de accounts niet samen — je schakelt over naar het nieuwe account."
      },
      "switch": "Van account wisselen",
      "expired": {
        "content": "Vraag de afzender om een nieuwe link te genereren.",
        "description": "Dit verzoek tot overboeking is verlopen.",
        "title": "Overdracht verlopen"
      },
      "og": {
        "tile": "Neem de controle over je account op Evnly.",
        "description": (name) => `${name}, dit account is voor jou aangemaakt. Neem het in gebruik door je inloggegevens in te stellen.`
      }
    },
    "actions": {
      "discard": "Afwijzen",
      "close": "Sluiten"
    },
    "friends": {
      "app": {
        "description": "De slimme manier om samen met vrienden bij te houden wie wat aan wie verschuldigd is."
      },
      "inviter": {
        "description": (name) => `Je bent uitgenodigd door ${name}. Registreer je of log in, en je bent klaar om te beginnen!`
      },
      "accept": "Begin met het gebruik van Evnly",
      "og": {
        "description": "Houd gezamenlijke uitgaven bij, splits de kosten en blijf op één lijn — samen op Evnly.",
        "title": (name) => `Word lid van ${name} op Evnly`
      },
      "dialog": {
        "title": "Verbinden via Evnly",
        "description": "Log in of maak een account aan om verder te gaan.",
        "accept": "Verbinden",
        "decline": "Niet nu",
        "content": (name) => `${name} wil graag contact maken op Evnly om gezamenlijke uitgaven bij te houden.`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `Word lid van ${groupName} op Evnly`,
        "description": (names) => `Deel uitgaven met ${new Intl.ListFormat("nl", { style: "long", type: "conjunction" }).format(names)}`
      },
      "dialog": {
        "title": (groupname) => `Word lid van ${groupname}`,
        "join": "Meedoen",
        "decline": "Weigeren"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `Word lid van ${title} op Evnly`,
        "description": "Deel de kosten van avonturen en houd samen eerlijk bij — op Evnly."
      },
      "dialog": {
        "title": (title) => `Word lid van ${title}`,
        "join": "Deelnemen",
        "decline": "Negeren",
        "description": (name, gender) => `${name} nodigt je uit voor het avontuur`,
        "heading": "Uitnodiging voor het avontuur"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `Word lid van ${title} op Evnly`,
        "description": "Splits een bon en houd bij wie wie moet betalen — samen op Evnly."
      },
      "dialog": {
        "join": "Meedoen",
        "decline": "Weigeren",
        "title": "Uitnodiging om de rekening te delen",
        "description": (name, gender) => `${name} nodigt je uit om een rekening te splitten`,
        "balance": {
          "total": "Totaalrekening"
        }
      }
    }
  },
  "ru-RU": {
    "account": {
      "title": "Перевод аккаунта",
      "description": "Кто-то создал этот аккаунт и передаёт его вам.",
      "accept": "Принять аккаунт",
      "content0": "Чтобы получить право владения, настройте свои данные для входа. Это не создаст новую учетную запись — вы просто получите доступ к этой.",
      "content1": "Это не создаст новую учетную запись — просто даст вам доступ к этой и позволит управлять ею.",
      "conflict": {
        "content0": (name) => `${name}, чтобы принять этот аккаунт, вам потребуется выйти из текущего и настроить новые данные для входа.`,
        "content1": "Это не объединит аккаунты — вы просто перейдёте на новый."
      },
      "switch": "Сменить аккаунт",
      "expired": {
        "content": "Попросите отправителя сгенерировать новую ссылку.",
        "description": "Срок действия этого запроса на перевод истёк.",
        "title": "Время передачи истекло"
      },
      "og": {
        "tile": "Перехватите управление своим аккаунтом на Evnly.",
        "description": (name) => `${name}, для вас создана эта учетная запись. Примите владение, настроив данные для входа.`
      }
    },
    "actions": {
      "discard": "Отклонить",
      "close": "Закрыть"
    },
    "friends": {
      "app": {
        "description": "Умный способ вместе с друзьями отслеживать, кто кому сколько должен."
      },
      "inviter": {
        "description": (name) => `Вас пригласил(а) ${name}. Просто зарегистрируйтесь или войдите — и всё готово!`
      },
      "accept": "Начать пользоваться Evnly",
      "og": {
        "description": "Отслеживайте общие расходы, делите затраты и оставайтесь на одной волне — вместе на Evnly.",
        "title": (name) => `Присоединяйся к ${name} на Evnly`
      },
      "dialog": {
        "title": "Подключиться на Evnly",
        "description": "Войдите или создайте аккаунт, чтобы продолжить.",
        "accept": "Подключиться",
        "decline": "Не сейчас",
        "content": (name) => `${name} хочет добавить вас в друзья на Evnly, чтобы отслеживать общие расходы.`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `Присоединиться к ${groupName} на Evnly`,
        "description": (names) => `Разделяй расходы с ${new Intl.ListFormat("ru", { style: "long", type: "conjunction" }).format(names)}`
      },
      "dialog": {
        "title": (groupname) => `Присоединиться к ${groupname}`,
        "join": "Присоединиться",
        "decline": "Отклонить"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `Присоединяйтесь к «${title}» на Evnly`,
        "description": "Делите расходы на приключения и ведите счет вместе — в Evnly."
      },
      "dialog": {
        "title": (title) => `Присоединиться к ${title}`,
        "join": "Присоединиться",
        "decline": "Игнорировать",
        "description": (name, gender) => gender === "he" ? `${name} приглашает тебя присоединиться к приключению` : gender === "she" ? `${name} приглашает тебя присоединиться к приключению` : `${name} приглашает тебя присоединиться к приключению`,
        "heading": "Приглашение в приключение"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `Присоединиться к ${title} на Evnly`,
        "description": "Разделите чек и отслеживайте, кто кому должен — вместе на Evnly."
      },
      "dialog": {
        "join": "Присоединиться",
        "decline": "Отклонить",
        "title": "Приглашение разделить счёт",
        "description": (name, gender) => gender === "he" ? `${name} приглашает вас разделить счёт` : gender === "she" ? `${name} приглашает вас разделить счёт` : `${name} приглашает вас разделить счёт`,
        "balance": {
          "total": "Общий счет"
        }
      }
    }
  },
  "sw-TZ": {
    "account": {
      "title": "Uhamisho wa akaunti",
      "description": "Mtu fulani ameunda akaunti hii na anaikukabidhi kwako.",
      "accept": "Kubali akaunti",
      "content0": "Ili kuwa mmiliki, weka taarifa zako za kuingia. Hii haitaunda akaunti mpya — itakupa tu ufikiaji wa hii.",
      "content1": "Hii haitaunda akaunti mpya — itakuwezesha tu kupata na kudhibiti hii.",
      "conflict": {
        "content0": (name) => `${name}, ili kukubali akaunti hii, utatolewa kwenye akaunti yako ya sasa na kuweka maelezo mapya ya kuingia.`,
        "content1": "Hili haitaunganisha akaunti — utahama kwenda mpya."
      },
      "switch": "Badilisha akaunti",
      "expired": {
        "content": "Muombe mtoa taarifa atengeneze kiungo kipya.",
        "description": "Ombi hili la uhamisho limekwisha muda wake.",
        "title": "Uhamisho umeisha muda wake"
      },
      "og": {
        "tile": "Chukua udhibiti wa akaunti yako kwenye Evnly.",
        "description": (name) => `${name}, akaunti hii iliundwa kwa ajili yako. Miliki kwa kuweka maelezo ya kuingia.`
      }
    },
    "actions": {
      "discard": "Tupa mbali",
      "close": "Funga"
    },
    "friends": {
      "app": {
        "description": "Njia bora ya kufuatilia nani anamdai nani, ukiwa pamoja na marafiki."
      },
      "inviter": {
        "description": (name) => `Umealikwa na ${name}. Jisajili au ingia tu, na uko tayari kuanza!`
      },
      "accept": "Anza kutumia Evnly",
      "og": {
        "description": "Fatilia matumizi ya pamoja, gawanya gharama, na dumuni mmelingano — pamoja kwenye Evnly.",
        "title": (name) => `Jiunge na ${name} kwenye Evnly`
      },
      "dialog": {
        "title": "Unganisha kwenye Evnly",
        "description": "Ingia au tengeneza akaunti ili kuendelea.",
        "accept": "Unganisha",
        "decline": "Siyo sasa",
        "content": (name) => `${name} anataka kuungana nawe kwenye Evnly ili kufuatilia matumizi yenu ya pamoja.`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `Jiunge na ${groupName} kwenye Evnly`,
        "description": (names) => `Gawa gharama na ${new Intl.ListFormat("sw", { style: "long", type: "conjunction" }).format(names)}`
      },
      "dialog": {
        "title": (groupname) => `Jiunge na ${groupname}`,
        "join": "Jiunge",
        "decline": "Kataa"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `Jiunge na ${title} kwenye Evnly`,
        "description": "Gawana gharama za adventure na fuatilia kwa usawa — pamoja kwenye Evnly."
      },
      "dialog": {
        "title": (title) => `Jiunge na ${title}`,
        "join": "Jiunge",
        "decline": "Puuza",
        "description": (name, gender) => `${name} anakualika ujiunge na tukio hili la kusisimua`,
        "heading": "Mwaliko wa kuingia kwenye adventure"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `Jiunge na ${title} kwenye Evnly`,
        "description": "Gawanya risiti na fuatilia nani anamdai nani — pamoja kwenye Evnly."
      },
      "dialog": {
        "join": "Jiunge",
        "decline": "Kataa",
        "title": "Mwaliko wa kugawana bili",
        "description": (name, gender) => `${name} anakualika kugawana bili`,
        "balance": {
          "total": "Jumla ya bili"
        }
      }
    }
  },
  "tr-TR": {
    "account": {
      "title": "Hesap transferi",
      "description": "Birisi bu hesabı oluşturdu ve şimdi onu sana devrediyor.",
      "accept": "Hesabı kabul et",
      "content0": "Sahipliği almak için oturum açma bilgilerini ayarla. Bu, yeni bir hesap oluşturmaz — sadece bu hesaba erişmeni sağlar.",
      "content1": "Bu yeni bir hesap oluşturmaz — sadece bu hesaba erişip yönetmeni sağlar.",
      "conflict": {
        "content0": (name) => `${name}, bu hesabı kabul etmek için mevcut hesabınızdan çıkış yapacak ve yeni oturum açma bilgileri ayarlayacaksınız.`,
        "content1": "Bu hesapları birleştirmez — yeni hesabına geçiş yapacaksın."
      },
      "switch": "Hesabı değiştir",
      "expired": {
        "content": "Gönderen kişiden yeni bir bağlantı oluşturmasını isteyin.",
        "description": "Bu transfer isteğinin süresi doldu.",
        "title": "Aktarım süresi doldu"
      },
      "og": {
        "tile": "Evnly hesabınızı devralın.",
        "description": (name) => `${name}, bu hesap sizin için oluşturuldu. Giriş bilgilerinizi ayarlayarak sahiplenin.`
      }
    },
    "actions": {
      "discard": "Reddet",
      "close": "Kapat"
    },
    "friends": {
      "app": {
        "description": "Kim kime ne borçlu, arkadaşlarınla birlikte takip etmenin akıllı yolu."
      },
      "inviter": {
        "description": (name) => `${name} tarafından davet edildiniz. Sadece kaydolun veya giriş yapın, hazırsınız!`
      },
      "accept": "Evnly’i kullanmaya başla",
      "og": {
        "description": "Paylaşılan harcamaları takip edin, masrafları bölüştürün ve uyumlu kalın — Evnly'de birlikte.",
        "title": (name) => `Evnly'de ${name}'e katıl`
      },
      "dialog": {
        "title": "Evnly'de bağlan",
        "description": "Devam etmek için giriş yapın veya bir hesap oluşturun.",
        "accept": "Bağlan",
        "decline": "Şimdi değil",
        "content": (name) => `${name}, Evnly'de seninle bağlantı kurup ortak giderlerinizi takip etmek istiyor.`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `Evnly'de ${groupName} grubuna katıl`,
        "description": (names) => `${new Intl.ListFormat("tr", { style: "long", type: "conjunction" }).format(names)} ile masrafları paylaş`
      },
      "dialog": {
        "title": (groupname) => `${groupname}’e Katıl`,
        "join": "Katıl",
        "decline": "Reddet"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `Evnly'de ${title}’a katıl`,
        "description": "Macera masraflarını paylaşın ve eşit olarak takip edin — Evnly'de birlikte."
      },
      "dialog": {
        "title": (title) => `${title}'a katıl`,
        "join": "Katıl",
        "decline": "Yoksay",
        "description": (name, gender) => `${name} seni maceraya davet ediyor`,
        "heading": "Macera davetiyesi"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `Evnly'de ${title}'a katıl`,
        "description": "Bir fişi bölüştürün ve kimin kime borcu olduğunu Evnly ile birlikte takip edin."
      },
      "dialog": {
        "join": "Katıl",
        "decline": "Reddet",
        "title": "Hesap paylaşma daveti",
        "description": (name, gender) => `${name} seni bir hesabı bölüşmeye davet ediyor`,
        "balance": {
          "total": "Toplam fatura"
        }
      }
    }
  },
  "uk-UA": {
    "account": {
      "title": "Передача облікового запису",
      "description": "Хтось створив цей обліковий запис і передає його вам.",
      "accept": "Прийняти обліковий запис",
      "content0": "Щоб отримати право володіння, налаштуйте свої дані для входу. Це не створить новий обліковий запис — ви просто отримаєте доступ до цього.",
      "content1": "Це не створить новий обліковий запис — просто дозволить вам отримати доступ до цього та керувати ним.",
      "conflict": {
        "content0": (name) => `${name}, щоб прийняти цей обліковий запис, вам потрібно вийти з поточного та налаштувати нові дані для входу.`,
        "content1": "Це не об'єднає облікові записи — ви просто перейдете до нового."
      },
      "switch": "Змінити обліковий запис",
      "expired": {
        "content": "Попросіть відправника створити нове посилання.",
        "description": "Термін дії цього запиту на переказ минув.",
        "title": "Термін передачі минув"
      },
      "og": {
        "tile": "Переберіть контроль над своїм обліковим записом на Evnly.",
        "description": (name) => `${name}, цей обліковий запис створено для вас. Станьте власником, налаштувавши дані для входу.`
      }
    },
    "actions": {
      "discard": "Відхилити",
      "close": "Закрити"
    },
    "friends": {
      "app": {
        "description": "Розумний спосіб разом із друзями відстежувати, хто кому винен."
      },
      "inviter": {
        "description": (name) => `Вас запросив(ла) ${name}. Просто зареєструйтеся або увійдіть — і все готово!`
      },
      "accept": "Почати користуватися Evnly",
      "og": {
        "description": "Відстежуйте спільні витрати, діліть рахунки та залишайтеся на зв’язку — разом на Evnly.",
        "title": (name) => `Приєднуйся до ${name} на Evnly`
      },
      "dialog": {
        "title": "Підключайтеся на Evnly",
        "description": "Увійдіть або створіть обліковий запис, щоб продовжити.",
        "accept": "Підключитися",
        "decline": "Не зараз",
        "content": (name) => `${name} хоче підключитися до вас у Evnly, щоб відстежувати спільні витрати.`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `Приєднатися до ${groupName} на Evnly`,
        "description": (names) => `Розділіть витрати з ${new Intl.ListFormat("uk", { style: "long", type: "conjunction" }).format(names)}`
      },
      "dialog": {
        "title": (groupname) => `Приєднатися до ${groupname}`,
        "join": "Приєднатися",
        "decline": "Відхилити"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `Приєднуйтесь до «${title}» на Evnly`,
        "description": "Діліться витратами на пригоди та ведіть рахунок порівну — разом в Evnly."
      },
      "dialog": {
        "title": (title) => `Приєднатися до ${title}`,
        "join": "Приєднатися",
        "decline": "Ігнорувати",
        "description": (name, gender) => gender === "he" ? `${name} запрошує вас приєднатися до пригоди` : gender === "she" ? `${name} запрошує вас приєднатися до пригоди` : `${name} запрошує вас приєднатися до пригоди`,
        "heading": "Запрошення до пригоди"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `Приєднатися до ${title} на Evnly`,
        "description": "Розділіть чек і стежте, хто кому винен — разом на Evnly."
      },
      "dialog": {
        "join": "Приєднатися",
        "decline": "Відхилити",
        "title": "Запрошення розділити рахунок",
        "description": (name, gender) => gender === "he" ? `${name} запрошує вас розділити рахунок` : gender === "she" ? `${name} запрошує вас розділити рахунок` : `${name} запрошує вас розділити рахунок`,
        "balance": {
          "total": "Загальний рахунок"
        }
      }
    }
  },
  "zh-CN": {
    "account": {
      "title": "账户转移",
      "description": "有人创建了此账户，并正在将其转交给您。",
      "accept": "接受账户",
      "content0": "要获取所有权，请设置您的登录信息。这不会创建新账户，只会让您访问此账户。",
      "content1": "这不会创建新账户——只会让你访问并管理此账户。",
      "conflict": {
        "content0": (name) => `${name}，接受此账户后，您将退出当前账户并设置新的登录信息。`,
        "content1": "这不会合并账户—你将切换到新账户。"
      },
      "switch": "切换账号",
      "expired": {
        "content": "请让发送方生成一个新链接。",
        "description": "该转账请求已过期。",
        "title": "转移已过期"
      },
      "og": {
        "tile": "接管您在Evnly的账户。",
        "description": (name) => `${name}，此账户是为您创建的。请设置登录信息以获取账户所有权。`
      }
    },
    "actions": {
      "discard": "丢弃",
      "close": "关闭"
    },
    "friends": {
      "app": {
        "description": "与朋友们一起，智能记录谁欠谁的钱。"
      },
      "inviter": {
        "description": (name) => `您已被${name}邀请。只需注册或登录，您就可以开始了！`
      },
      "accept": "开始使用 Evnly",
      "og": {
        "description": "跟踪共享支出、分摊费用、保持同步 —— 一起在 Evnly 上。",
        "title": (name) => `在Evnly上加入${name}`
      },
      "dialog": {
        "title": "在Evnly上连接",
        "description": "请登录或创建账户以继续。",
        "accept": "连接",
        "decline": "现在不要",
        "content": (name) => `${name} 想在 Evnly 上与你建立联系，以便一起管理共同支出。`
      }
    },
    "group": {
      "og": {
        "title": (groupName) => `在Evnly加入${groupName}`,
        "description": (names) => `与${new Intl.ListFormat("zh", { style: "long", type: "conjunction" }).format(names)}分摊费用`
      },
      "dialog": {
        "title": (groupname) => `加入${groupname}`,
        "join": "加入",
        "decline": "拒绝"
      }
    },
    "adventures": {
      "og": {
        "title": (title) => `在Evnly加入${title}`,
        "description": "一起在 Evnly 平分冒险开支，轻松公平记账。"
      },
      "dialog": {
        "title": (title) => `加入${title}`,
        "join": "加入",
        "decline": "忽略",
        "description": (name, gender) => `${name}邀请你加入冒险`,
        "heading": "冒险邀请函"
      }
    },
    "receipts": {
      "og": {
        "title": (title) => `加入Evnly上的${title}`,
        "description": "在 Evnly 一起分账并追踪谁欠谁。"
      },
      "dialog": {
        "join": "加入",
        "decline": "拒绝",
        "title": "邀请一起分账",
        "description": (name, gender) => `${name}邀请你一起AA制`,
        "balance": {
          "total": "账单总额"
        }
      }
    }
  }
};
