// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "account": {
      "title": "نقل الحساب",
      "description": "قام شخص ما بإنشاء هذا الحساب وينقله إليك الآن.",
      "accept": "قبول الحساب",
      "content0": "لتولي ملكية الحساب، قم بإعداد تفاصيل تسجيل الدخول الخاصة بك. لن يؤدي هذا إلى إنشاء حساب جديد — بل يمنحك فقط الوصول إلى هذا الحساب.",
      "content1": "هذا لن ينشئ حسابًا جديدًا — بل سيسمح لك فقط بالوصول إلى هذا الحساب وإدارته.",
      "conflict": {
        "content0": (name) => `${name}، لقبول هذا الحساب، سيتم تسجيل خروجك من حسابك الحالي وستحتاج إلى إعداد تفاصيل تسجيل دخول جديدة.`,
        "content1": "لن يؤدي هذا إلى دمج الحسابات — بل ستنتقل إلى الحساب الجديد."
      },
      "switch": "تبديل الحساب",
      "expired": {
        "content": "اطلب من المُرسِل إنشاء رابط جديد.",
        "description": "انتهت صلاحية طلب التحويل هذا.",
        "title": "انتهت صلاحية النقل"
      }
    },
    "actions": {
      "discard": "تجاهل",
      "close": "إغلاق"
    },
    "friends": {
      "app": {
        "description": "الطريقة الذكية لمتابعة من مدين لمن، مع الأصدقاء معاً."
      },
      "inviter": {
        "description": (name) => `لقد تمت دعوتك من قبل ${name}. فقط سجّل أو قم بتسجيل الدخول، وستكون جاهزًا!`
      },
      "accept": "ابدأ استخدام Evn"
    }
  },
  "de-DE": {
    "account": {
      "title": "Kontenübertrag",
      "description": "Jemand hat dieses Konto erstellt und überträgt es nun an dich.",
      "accept": "Konto akzeptieren",
      "content0": "Um die Inhaberschaft zu übernehmen, richte bitte deine Anmeldedaten ein. Dadurch wird kein neues Konto erstellt – du erhältst nur Zugriff auf dieses Konto.",
      "content1": "Dadurch wird kein neues Konto erstellt – du bekommst lediglich Zugriff auf dieses und kannst es verwalten.",
      "conflict": {
        "content0": (name) => `${name}, um dieses Konto zu akzeptieren, wirst du von deinem aktuellen Konto abgemeldet und musst neue Anmeldedaten festlegen.`,
        "content1": "Dadurch werden die Konten nicht zusammengeführt – du wechselst einfach zum neuen Konto."
      },
      "switch": "Konto wechseln",
      "expired": {
        "content": "Bitte den Absender, einen neuen Link zu erstellen.",
        "description": "Diese Überweisungsanfrage ist abgelaufen.",
        "title": "Übertragung abgelaufen"
      }
    },
    "actions": {
      "discard": "Ablehnen",
      "close": "Schließen"
    },
    "friends": {
      "app": {
        "description": "Die clevere Art, gemeinsam mit Freunden zu verfolgen, wer wem etwas schuldet."
      },
      "inviter": {
        "description": (name) => `${name} hat dich eingeladen. Registriere dich einfach oder melde dich an und schon kann es losgehen!`
      },
      "accept": "Evn jetzt nutzen"
    }
  },
  "en-US": {
    "account": {
      "title": "Account Transfer",
      "description": "Someone has created this account and is transferring it to you.",
      "accept": "Accept account",
      "content0": "To take ownership, set up your sign-in details. This won’t create a new account — it just gives you access to this one.",
      "content1": "This won’t create a new account — it will simply let you access and manage this one.",
      "conflict": {
        "content0": (name) => `${name}, to accept this account, you’ll be signed out of your current one and set up new sign-in details.`,
        "content1": "This won’t merge accounts — you’ll switch to the new one."
      },
      "switch": "Switch account",
      "expired": {
        "content": "Ask the sender to generate a new link.",
        "description": "This transfer request has expired.",
        "title": "Transfer Expired"
      }
    },
    "actions": {
      "discard": "Discard",
      "close": "Close"
    },
    "friends": {
      "app": {
        "description": "The smart way to track who owes whom, together with friends."
      },
      "inviter": {
        "description": (name) => `You have been invited by ${name}. Just register or log in, and you’re all set`
      },
      "accept": "Start Using Evn"
    }
  },
  "es-ES": {
    "account": {
      "title": "Transferencia de cuenta",
      "description": "Alguien ha creado esta cuenta y te la está transfiriendo.",
      "accept": "Aceptar cuenta",
      "content0": "Para tomar posesión, configura tus datos de inicio de sesión. Esto no creará una cuenta nueva, solo te da acceso a esta.",
      "content1": "Esto no creará una nueva cuenta; simplemente te permitirá acceder y gestionar esta.",
      "conflict": {
        "content0": (name) => `${name}, para aceptar esta cuenta, cerrarás sesión en la actual y se configurarán nuevos datos de acceso.`,
        "content1": "Esto no fusionará las cuentas; solo cambiarás a la nueva."
      },
      "switch": "Cambiar de cuenta",
      "expired": {
        "content": "Pide al remitente que genere un nuevo enlace.",
        "description": "Esta solicitud de transferencia ha caducado.",
        "title": "Transferencia caducada"
      }
    },
    "actions": {
      "discard": "Descartar",
      "close": "Cerrar"
    },
    "friends": {
      "app": {
        "description": "La forma inteligente de llevar un registro de quién debe a quién, junto a tus amigos."
      },
      "inviter": {
        "description": (name) => `Has sido invitado por ${name}. Solo regístrate o inicia sesión, ¡y listo!`
      },
      "accept": "Comienza a usar Evn"
    }
  },
  "fr-FR": {
    "account": {
      "title": "Transfert de compte",
      "description": "Quelqu’un a créé ce compte et est en train de vous le transférer.",
      "accept": "Accepter le compte",
      "content0": "Pour prendre la main, configurez vos identifiants de connexion. Cela ne créera pas un nouveau compte — cela vous donnera simplement accès à celui-ci.",
      "content1": "Cela ne créera pas un nouveau compte — cela vous permettra simplement d'accéder à celui-ci et de le gérer.",
      "conflict": {
        "content0": (name) => `${name}, pour accepter ce compte, vous serez déconnecté de votre compte actuel et devrez définir de nouvelles informations de connexion.`,
        "content1": "Cela ne fusionnera pas les comptes — vous passerez simplement au nouveau."
      },
      "switch": "Changer de compte",
      "expired": {
        "content": "Demandez à l'expéditeur de générer un nouveau lien.",
        "description": "Cette demande de transfert a expiré.",
        "title": "Transfert expiré"
      }
    },
    "actions": {
      "discard": "Ignorer",
      "close": "Fermer"
    },
    "friends": {
      "app": {
        "description": "La façon intelligente de suivre qui doit quoi à qui, ensemble avec des amis."
      },
      "inviter": {
        "description": (name) => `Vous avez été invité par ${name}. Inscrivez-vous ou connectez-vous, et tout est prêt !`
      },
      "accept": "Commencer à utiliser Evn"
    }
  },
  "hi-IN": {
    "account": {
      "title": "खाता स्थानांतरण",
      "description": "किसी ने यह खाता बनाया है और इसे आपके नाम स्थानांतरित कर रहा है।",
      "accept": "खाता स्वीकार करें",
      "content0": "अधिकार प्राप्त करने के लिए, अपने साइन-इन विवरण सेट करें। इससे नया खाता नहीं बनेगा — यह सिर्फ आपको इसी खाते तक पहुँच देगा।",
      "content1": "इससे नया खाता नहीं बनेगा — यह सिर्फ आपको इस खाते तक पहुँचने और इसे प्रबंधित करने देगा।",
      "conflict": {
        "content0": (name) => `${name}, इस खाते को स्वीकार करने के लिए, आपको अपने वर्तमान खाते से साइन आउट किया जाएगा और नए साइन-इन विवरण सेट करने होंगे।`,
        "content1": "इससे खाते मर्ज नहीं होंगे — आप नए खाते पर स्विच करेंगे।"
      },
      "switch": "खाता बदलें",
      "expired": {
        "content": "प्रेषक से नया लिंक बनाने के लिए कहें।",
        "description": "इस ट्रांसफ़र अनुरोध की अवधि समाप्त हो गई है।",
        "title": "स्थानांतरण की अवधि समाप्त"
      }
    },
    "actions": {
      "discard": "अस्वीकार करें",
      "close": "बंद करें"
    },
    "friends": {
      "app": {
        "description": "दोस्तों के साथ मिलकर यह जानने का स्मार्ट तरीका कि किसका किस पर कितना बकाया है।"
      },
      "inviter": {
        "description": (name) => `${name} ने आपको आमंत्रित किया है। बस रजिस्टर करें या लॉग इन करें, और आप तैयार हैं!`
      },
      "accept": "Evn का उपयोग शुरू करें"
    }
  },
  "it-IT": {
    "account": {
      "title": "Trasferimento account",
      "description": "Qualcuno ha creato questo account e lo sta trasferendo a te.",
      "accept": "Accetta account",
      "content0": "Per assumere la proprietà, imposta i tuoi dettagli di accesso. Questo non creerà un nuovo account — ti darà solo accesso a questo.",
      "content1": "Questo non creerà un nuovo account — ti permetterà semplicemente di accedere e gestire questo.",
      "conflict": {
        "content0": (name) => `${name}, per accettare questo account, verrai disconnesso dal tuo attuale e dovrai impostare nuove credenziali di accesso.`,
        "content1": "Questo non unirà gli account: passerai semplicemente a quello nuovo."
      },
      "switch": "Cambia account",
      "expired": {
        "content": "Chiedi al mittente di generare un nuovo link.",
        "description": "Questa richiesta di trasferimento è scaduta.",
        "title": "Trasferimento scaduto"
      }
    },
    "actions": {
      "discard": "Rifiuta",
      "close": "Chiudi"
    },
    "friends": {
      "app": {
        "description": "Il modo intelligente per tenere traccia di chi deve cosa a chi, insieme agli amici."
      },
      "inviter": {
        "description": (name) => `Sei stato invitato da ${name}. Registrati o accedi, ed è tutto pronto!`
      },
      "accept": "Inizia a usare Evn"
    }
  },
  "ja-JP": {
    "account": {
      "title": "アカウントの移行",
      "description": "誰かがこのアカウントを作成し、あなたに譲渡しています。",
      "accept": "アカウントを承認",
      "content0": "所有権を取得するには、サインイン情報を設定してください。新しいアカウントは作成されません — このアカウントにアクセスできるようになるだけです。",
      "content1": "新しいアカウントは作成されません。このアカウントにアクセスして管理できるようになるだけです。",
      "conflict": {
        "content0": (name) => `${name}、このアカウントを承認するには、現在のアカウントからサインアウトし、新しいサインイン情報を設定する必要があります。`,
        "content1": "これでアカウントが統合されることはありません。新しいアカウントに切り替わります。"
      },
      "switch": "アカウントを切り替える",
      "expired": {
        "content": "送信者に新しいリンクを生成するよう依頼してください。",
        "description": "この送金リクエストの有効期限が切れました。",
        "title": "転送の有効期限が切れました"
      }
    },
    "actions": {
      "discard": "破棄",
      "close": "閉じる"
    },
    "friends": {
      "app": {
        "description": "友達と一緒に、誰が誰にいくら借りているかをスマートに管理する方法。"
      },
      "inviter": {
        "description": (name) => `${name}さんから招待されています。登録またはログインするだけで、すぐにご利用いただけます。`
      },
      "accept": "Evn を使い始める"
    }
  },
  "ko-KR": {
    "account": {
      "title": "계정 이전",
      "description": "누군가 이 계정을 만들었으며 지금 당신에게 이전하고 있습니다.",
      "accept": "계정 승인",
      "content0": "소유권을 가져오려면 로그인 정보를 설정하세요. 이것은 새 계정을 만드는 것이 아니라, 이 계정에 대한 접근 권한만 부여합니다.",
      "content1": "새 계정을 만들지는 않습니다. 이 계정에 접근하고 관리할 수 있게 해줍니다.",
      "conflict": {
        "content0": (name) => `${name}님, 이 계정을 승인하려면 현재 계정에서 로그아웃하고 새로운 로그인 정보를 설정해야 합니다.`,
        "content1": "계정이 병합되지 않습니다 — 새 계정으로 전환됩니다."
      },
      "switch": "계정 전환",
      "expired": {
        "content": "보내는 사람에게 새 링크를 생성해 달라고 요청하세요.",
        "description": "이체 요청이 만료되었습니다.",
        "title": "전송 만료됨"
      }
    },
    "actions": {
      "discard": "버리기",
      "close": "닫기"
    },
    "friends": {
      "app": {
        "description": "친구들과 함께 누가 누구에게 얼마를 빚졌는지 스마트하게 관리하는 방법."
      },
      "inviter": {
        "description": (name) => `${name}님이 초대하셨습니다. 가입하거나 로그인하면 바로 시작할 수 있어요!`
      },
      "accept": "Evn 시작하기"
    }
  },
  "nl-NL": {
    "account": {
      "title": "Accountoverdracht",
      "description": "Iemand heeft dit account aangemaakt en draagt het nu aan jou over.",
      "accept": "Account accepteren",
      "content0": "Om eigenaar te worden, stel je je inloggegevens in. Er wordt geen nieuw account aangemaakt — je krijgt alleen toegang tot dit account.",
      "content1": "Dit maakt geen nieuw account aan — het geeft je alleen toegang tot en beheer over dit account.",
      "conflict": {
        "content0": (name) => `${name}, om dit account te accepteren, word je afgemeld van je huidige account en stel je nieuwe inloggegevens in.`,
        "content1": "Dit voegt de accounts niet samen — je schakelt over naar het nieuwe account."
      },
      "switch": "Van account wisselen",
      "expired": {
        "content": "Vraag de afzender om een nieuwe link te genereren.",
        "description": "Dit verzoek tot overboeking is verlopen.",
        "title": "Overdracht verlopen"
      }
    },
    "actions": {
      "discard": "Afwijzen",
      "close": "Sluiten"
    },
    "friends": {
      "app": {
        "description": "De slimme manier om samen met vrienden bij te houden wie wat aan wie verschuldigd is."
      },
      "inviter": {
        "description": (name) => `Je bent uitgenodigd door ${name}. Registreer je of log in, en je bent klaar om te beginnen!`
      },
      "accept": "Begin met het gebruik van Evn"
    }
  },
  "ru-RU": {
    "account": {
      "title": "Перевод аккаунта",
      "description": "Кто-то создал этот аккаунт и передаёт его вам.",
      "accept": "Принять аккаунт",
      "content0": "Чтобы получить право владения, настройте свои данные для входа. Это не создаст новую учетную запись — вы просто получите доступ к этой.",
      "content1": "Это не создаст новую учетную запись — просто даст вам доступ к этой и позволит управлять ею.",
      "conflict": {
        "content0": (name) => `${name}, чтобы принять этот аккаунт, вам потребуется выйти из текущего и настроить новые данные для входа.`,
        "content1": "Это не объединит аккаунты — вы просто перейдёте на новый."
      },
      "switch": "Сменить аккаунт",
      "expired": {
        "content": "Попросите отправителя сгенерировать новую ссылку.",
        "description": "Срок действия этого запроса на перевод истёк.",
        "title": "Время передачи истекло"
      }
    },
    "actions": {
      "discard": "Отклонить",
      "close": "Закрыть"
    },
    "friends": {
      "app": {
        "description": "Умный способ вместе с друзьями отслеживать, кто кому сколько должен."
      },
      "inviter": {
        "description": (name) => `Вас пригласил(а) ${name}. Просто зарегистрируйтесь или войдите — и всё готово!`
      },
      "accept": "Начать пользоваться Evn"
    }
  },
  "sw-TZ": {
    "account": {
      "title": "Uhamisho wa akaunti",
      "description": "Mtu fulani ameunda akaunti hii na anaikukabidhi kwako.",
      "accept": "Kubali akaunti",
      "content0": "Ili kuwa mmiliki, weka taarifa zako za kuingia. Hii haitaunda akaunti mpya — itakupa tu ufikiaji wa hii.",
      "content1": "Hii haitaunda akaunti mpya — itakuwezesha tu kupata na kudhibiti hii.",
      "conflict": {
        "content0": (name) => `${name}, ili kukubali akaunti hii, utatolewa kwenye akaunti yako ya sasa na kuweka maelezo mapya ya kuingia.`,
        "content1": "Hili haitaunganisha akaunti — utahama kwenda mpya."
      },
      "switch": "Badilisha akaunti",
      "expired": {
        "content": "Muombe mtoa taarifa atengeneze kiungo kipya.",
        "description": "Ombi hili la uhamisho limekwisha muda wake.",
        "title": "Uhamisho umeisha muda wake"
      }
    },
    "actions": {
      "discard": "Tupa mbali",
      "close": "Funga"
    },
    "friends": {
      "app": {
        "description": "Njia bora ya kufuatilia nani anamdai nani, ukiwa pamoja na marafiki."
      },
      "inviter": {
        "description": (name) => `Umealikwa na ${name}. Jisajili au ingia tu, na uko tayari kuanza!`
      },
      "accept": "Anza kutumia Evn"
    }
  },
  "tr-TR": {
    "account": {
      "title": "Hesap transferi",
      "description": "Birisi bu hesabı oluşturdu ve şimdi onu sana devrediyor.",
      "accept": "Hesabı kabul et",
      "content0": "Sahipliği almak için oturum açma bilgilerini ayarla. Bu, yeni bir hesap oluşturmaz — sadece bu hesaba erişmeni sağlar.",
      "content1": "Bu yeni bir hesap oluşturmaz — sadece bu hesaba erişip yönetmeni sağlar.",
      "conflict": {
        "content0": (name) => `${name}, bu hesabı kabul etmek için mevcut hesabınızdan çıkış yapacak ve yeni oturum açma bilgileri ayarlayacaksınız.`,
        "content1": "Bu hesapları birleştirmez — yeni hesabına geçiş yapacaksın."
      },
      "switch": "Hesabı değiştir",
      "expired": {
        "content": "Gönderen kişiden yeni bir bağlantı oluşturmasını isteyin.",
        "description": "Bu transfer isteğinin süresi doldu.",
        "title": "Aktarım süresi doldu"
      }
    },
    "actions": {
      "discard": "Reddet",
      "close": "Kapat"
    },
    "friends": {
      "app": {
        "description": "Kim kime ne borçlu, arkadaşlarınla birlikte takip etmenin akıllı yolu."
      },
      "inviter": {
        "description": (name) => `${name} tarafından davet edildiniz. Sadece kaydolun veya giriş yapın, hazırsınız!`
      },
      "accept": "Evn’i kullanmaya başla"
    }
  },
  "uk-UA": {
    "account": {
      "title": "Передача облікового запису",
      "description": "Хтось створив цей обліковий запис і передає його вам.",
      "accept": "Прийняти обліковий запис",
      "content0": "Щоб отримати право володіння, налаштуйте свої дані для входу. Це не створить новий обліковий запис — ви просто отримаєте доступ до цього.",
      "content1": "Це не створить новий обліковий запис — просто дозволить вам отримати доступ до цього та керувати ним.",
      "conflict": {
        "content0": (name) => `${name}, щоб прийняти цей обліковий запис, вам потрібно вийти з поточного та налаштувати нові дані для входу.`,
        "content1": "Це не об'єднає облікові записи — ви просто перейдете до нового."
      },
      "switch": "Змінити обліковий запис",
      "expired": {
        "content": "Попросіть відправника створити нове посилання.",
        "description": "Термін дії цього запиту на переказ минув.",
        "title": "Термін передачі минув"
      }
    },
    "actions": {
      "discard": "Відхилити",
      "close": "Закрити"
    },
    "friends": {
      "app": {
        "description": "Розумний спосіб разом із друзями відстежувати, хто кому винен."
      },
      "inviter": {
        "description": (name) => `Вас запросив(ла) ${name}. Просто зареєструйтеся або увійдіть — і все готово!`
      },
      "accept": "Почати користуватися Evn"
    }
  },
  "zh-CN": {
    "account": {
      "title": "账户转移",
      "description": "有人创建了此账户，并正在将其转交给您。",
      "accept": "接受账户",
      "content0": "要获取所有权，请设置您的登录信息。这不会创建新账户，只会让您访问此账户。",
      "content1": "这不会创建新账户——只会让你访问并管理此账户。",
      "conflict": {
        "content0": (name) => `${name}，接受此账户后，您将退出当前账户并设置新的登录信息。`,
        "content1": "这不会合并账户—你将切换到新账户。"
      },
      "switch": "切换账号",
      "expired": {
        "content": "请让发送方生成一个新链接。",
        "description": "该转账请求已过期。",
        "title": "转移已过期"
      }
    },
    "actions": {
      "discard": "丢弃",
      "close": "关闭"
    },
    "friends": {
      "app": {
        "description": "与朋友们一起，智能记录谁欠谁的钱。"
      },
      "inviter": {
        "description": (name) => `您已被${name}邀请。只需注册或登录，您就可以开始了！`
      },
      "accept": "开始使用 Evn"
    }
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];
