// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "account": {
      "title": "نقل الحساب",
      "description": "قام شخص ما بإنشاء هذا الحساب وينقله إليك الآن.",
      "accept": "قبول الحساب",
      "content": "لتُصبح المالك، ستحتاج إلى إعداد تفاصيل تسجيل الدخول الخاصة بك. لن يؤدي ذلك إلى إنشاء حساب جديد — بل سيتيح لك فقط الوصول إلى هذا الحساب وإدارته.",
      "content0": "لتتمكن من امتلاك الحساب، ستحتاج إلى إعداد تفاصيل تسجيل الدخول الخاصة بك.",
      "content1": "هذا لن ينشئ حسابًا جديدًا — بل سيسمح لك فقط بالوصول إلى هذا الحساب وإدارته."
    },
    "actions": {
      "discard": "تجاهل"
    }
  },
  "de-DE": {
    "account": {
      "title": "Kontenübertrag",
      "description": "Jemand hat dieses Konto erstellt und überträgt es nun an dich.",
      "accept": "Konto akzeptieren",
      "content": "Um die Inhaberschaft zu übernehmen, müssen Sie Ihre Zugangsdaten festlegen. Es wird kein neues Konto erstellt – Sie können dadurch einfach auf dieses Konto zugreifen und es verwalten.",
      "content0": "Um die Inhaberschaft zu übernehmen, richte bitte deine Anmeldedaten ein.",
      "content1": "Dadurch wird kein neues Konto erstellt – du bekommst lediglich Zugriff auf dieses und kannst es verwalten."
    },
    "actions": {
      "discard": "Ablehnen"
    }
  },
  "en-US": {
    "account": {
      "title": "Account Transfer",
      "description": "Someone has created this account and is transferring it to you.",
      "accept": "Accept account",
      "content": "To take ownership, you’ll need to set up your sign-in details. This won’t create a new account — it will simply let you access and manage this one.",
      "content0": "To take ownership, you’ll need to set up your sign-in details.",
      "content1": "This won’t create a new account — it will simply let you access and manage this one."
    },
    "actions": {
      "discard": "Discard"
    }
  },
  "es-ES": {
    "account": {
      "title": "Transferencia de cuenta",
      "description": "Alguien ha creado esta cuenta y te la está transfiriendo.",
      "accept": "Aceptar cuenta",
      "content": "Para tomar el control, tendrás que configurar tus datos de acceso. Esto no creará una cuenta nueva; simplemente te permitirá acceder y gestionar esta.",
      "content0": "Para asumir la propiedad, tendrás que configurar tus datos de inicio de sesión.",
      "content1": "Esto no creará una nueva cuenta; simplemente te permitirá acceder y gestionar esta."
    },
    "actions": {
      "discard": "Descartar"
    }
  },
  "fr-FR": {
    "account": {
      "title": "Transfert de compte",
      "description": "Quelqu’un a créé ce compte et est en train de vous le transférer.",
      "accept": "Accepter le compte",
      "content": "Pour devenir propriétaire, vous devrez configurer vos informations de connexion. Cela ne créera pas un nouveau compte — cela vous permettra simplement d'accéder à celui-ci et de le gérer.",
      "content0": "Pour devenir propriétaire, vous devez configurer vos informations de connexion.",
      "content1": "Cela ne créera pas un nouveau compte — cela vous permettra simplement d'accéder à celui-ci et de le gérer."
    },
    "actions": {
      "discard": "Ignorer"
    }
  },
  "hi-IN": {
    "account": {
      "title": "खाता स्थानांतरण",
      "description": "किसी ने यह खाता बनाया है और इसे आपके नाम स्थानांतरित कर रहा है।",
      "accept": "खाता स्वीकार करें",
      "content": "स्वामित्व लेने के लिए, आपको अपनी साइन-इन जानकारी सेटअप करनी होगी। इससे नया खाता नहीं बनेगा — यह केवल आपको इसी खाते तक पहुंचने और इसे प्रबंधित करने देगा।",
      "content0": "स्वामित्व लेने के लिए, आपको अपनी साइन-इन जानकारी सेट अप करनी होगी।",
      "content1": "इससे नया खाता नहीं बनेगा — यह सिर्फ आपको इस खाते तक पहुँचने और इसे प्रबंधित करने देगा।"
    },
    "actions": {
      "discard": "अस्वीकार करें"
    }
  },
  "it-IT": {
    "account": {
      "title": "Trasferimento account",
      "description": "Qualcuno ha creato questo account e lo sta trasferendo a te.",
      "accept": "Accetta account",
      "content": "Per assumere la proprietà, dovrai impostare i tuoi dati di accesso. Questo non creerà un nuovo account — ti permetterà semplicemente di accedere e gestire questo.",
      "content0": "Per assumere la proprietà, devi configurare i tuoi dati di accesso.",
      "content1": "Questo non creerà un nuovo account — ti permetterà semplicemente di accedere e gestire questo."
    },
    "actions": {
      "discard": "Rifiuta"
    }
  },
  "ja-JP": {
    "account": {
      "title": "アカウントの移行",
      "description": "誰かがこのアカウントを作成し、あなたに譲渡しています。",
      "accept": "アカウントを承認",
      "content": "所有者になるには、サインイン情報を設定する必要があります。新しいアカウントは作成されません — このアカウントにアクセスして管理できるようになります。",
      "content0": "権限を取得するには、サインイン情報の設定が必要です。",
      "content1": "新しいアカウントは作成されません。このアカウントにアクセスして管理できるようになるだけです。"
    },
    "actions": {
      "discard": "破棄"
    }
  },
  "ko-KR": {
    "account": {
      "title": "계정 이전",
      "description": "누군가 이 계정을 만들었으며 지금 당신에게 이전하고 있습니다.",
      "accept": "계정 승인",
      "content": "소유권을 갖기 위해 로그인 정보를 설정해야 합니다. 새로운 계정이 생성되는 것은 아니며, 이 계정에 접근하고 관리할 수 있게 됩니다.",
      "content0": "소유권을 갖기 위해서는 로그인 정보를 설정해야 합니다.",
      "content1": "새 계정을 만들지는 않습니다. 이 계정에 접근하고 관리할 수 있게 해줍니다."
    },
    "actions": {
      "discard": "버리기"
    }
  },
  "nl-NL": {
    "account": {
      "title": "Accountoverdracht",
      "description": "Iemand heeft dit account aangemaakt en draagt het nu aan jou over.",
      "accept": "Account accepteren",
      "content": "Om eigenaar te worden, moet je je inloggegevens instellen. Dit maakt geen nieuw account aan — het zorgt er alleen voor dat je toegang krijgt tot en dit account kunt beheren.",
      "content0": "Om eigenaar te worden, moet je je inloggegevens instellen.",
      "content1": "Dit maakt geen nieuw account aan — het geeft je alleen toegang tot en beheer over dit account."
    },
    "actions": {
      "discard": "Afwijzen"
    }
  },
  "ru-FU": {
    "account": {
      "title": "Перевод аккаунта",
      "description": "Кто-то создал этот аккаунт и передаёт его вам.",
      "accept": "Принять аккаунт",
      "content": "Чтобы взять на себя право владения, вам нужно будет настроить данные для входа. Это не создаст новую учётную запись — вы просто получите доступ к этой и сможете её управлять.",
      "content0": "Чтобы получить доступ, нужно настроить свои данные для входа.",
      "content1": "Это не создаст новую учётную запись — просто позволит вам получить доступ к этой и управлять ею."
    },
    "actions": {
      "discard": "Отклонить"
    }
  },
  "ru-RU": {
    "account": {
      "title": "Перевод аккаунта",
      "description": "Кто-то создал этот аккаунт и передаёт его вам.",
      "accept": "Принять аккаунт",
      "content": "Чтобы получить права владельца, вам нужно настроить данные для входа. Это не создаст новую учетную запись — вы просто сможете получить доступ к этой и управлять ею.",
      "content0": "Чтобы получить право владения, необходимо настроить данные для входа.",
      "content1": "Это не создаст новую учетную запись — просто даст вам доступ к этой и позволит управлять ею."
    },
    "actions": {
      "discard": "Отклонить"
    }
  },
  "sw-TZ": {
    "account": {
      "title": "Uhamisho wa akaunti",
      "description": "Mtu fulani ameunda akaunti hii na anaikukabidhi kwako.",
      "accept": "Kubali akaunti",
      "content": "Ili kumiliki, utahitaji kuweka maelezo yako ya kuingia. Hii haitaunda akaunti mpya — itakuwezesha tu kufikia na kudhibiti hii.",
      "content0": "Ili kuchukua umiliki, utahitaji kuweka maelezo yako ya kuingia.",
      "content1": "Hii haitaunda akaunti mpya — itakuwezesha tu kupata na kudhibiti hii."
    },
    "actions": {
      "discard": "Tupa mbali"
    }
  },
  "tr-TR": {
    "account": {
      "title": "Hesap transferi",
      "description": "Birisi bu hesabı oluşturdu ve şimdi onu sana devrediyor.",
      "accept": "Hesabı kabul et",
      "content": "Sahiplik almak için giriş bilgilerinizi ayarlamanız gerekir. Bu, yeni bir hesap oluşturmaz — sadece bu hesaba erişmenizi ve yönetmenizi sağlar.",
      "content0": "Sahipliği almak için oturum açma bilgilerinizi oluşturmanız gerekir.",
      "content1": "Bu yeni bir hesap oluşturmaz — sadece bu hesaba erişip yönetmeni sağlar."
    },
    "actions": {
      "discard": "Reddet"
    }
  },
  "uk-UA": {
    "account": {
      "title": "Передача облікового запису",
      "description": "Хтось створив цей обліковий запис і передає його вам.",
      "accept": "Прийняти обліковий запис",
      "content": "Щоб стати власником, потрібно налаштувати свої дані для входу. Це не створить нового облікового запису — ви просто зможете отримати доступ до цього та керувати ним.",
      "content0": "Щоб отримати права власника, потрібно налаштувати свої дані для входу.",
      "content1": "Це не створить новий обліковий запис — просто дозволить вам отримати доступ до цього та керувати ним."
    },
    "actions": {
      "discard": "Відхилити"
    }
  },
  "zh-CN": {
    "account": {
      "title": "账户转移",
      "description": "有人创建了此账户，并正在将其转交给您。",
      "accept": "接受账户",
      "content": "要获得所有权，您需要设置您的登录信息。这不会创建新账户——只会让您访问并管理此账户。",
      "content0": "要取得所有权，您需要设置您的登录信息。",
      "content1": "这不会创建新账户——只会让你访问并管理此账户。"
    },
    "actions": {
      "discard": "丢弃"
    }
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-FU","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];
