// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("./types").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "splitter": {
      "stack": {
        "claim": "المطالبة بالجميع",
        "release": "إفلات"
      }
    },
    "leave": {
      "label": "اضغط مطولًا للمغادرة"
    },
    "delete": {
      "label": "اضغط مطولاً للحذف"
    },
    "me": "أنا",
    "overview": {
      "total": "الإجمالي"
    },
    "feedback": {
      "question": "كيف كانت نتيجة المسح الضوئي؟",
      "down": "سنلقي نظرة.",
      "thanks": "شكرًا!"
    },
    "autoclose": {
      "description": "أنشئ التقسيم وقم بتحديث الأرصدة عند انتهاء الجميع.",
      "title": "أكمِل تلقائيًا"
    }
  },
  "de-DE": {
    "splitter": {
      "stack": {
        "claim": "Alles einfordern",
        "release": "Loslassen"
      }
    },
    "leave": {
      "label": "Zum Verlassen halten"
    },
    "delete": {
      "label": "Zum Löschen halten"
    },
    "me": "Ich",
    "overview": {
      "total": "Gesamt"
    },
    "feedback": {
      "question": "Wie war der Scan?",
      "down": "Wir schauen es uns an.",
      "thanks": "Danke!"
    },
    "autoclose": {
      "description": "Erstelle die Aufteilung und aktualisiere die Salden, sobald alle fertig sind.",
      "title": "Automatisch abschließen"
    }
  },
  "en-US": {
    "splitter": {
      "stack": {
        "claim": "Claim all",
        "release": "Release"
      }
    },
    "leave": {
      "label": "Hold to leave"
    },
    "delete": {
      "label": "Hold to delete"
    },
    "me": "Me",
    "overview": {
      "total": "Total"
    },
    "feedback": {
      "question": "How did the scan turn out?",
      "down": "We’ll take a look.",
      "thanks": "Thank you!"
    },
    "autoclose": {
      "description": "Create the split and update balances when everyone is done.",
      "title": "Finish automatically"
    }
  },
  "es-ES": {
    "splitter": {
      "stack": {
        "claim": "Reclamar todo",
        "release": "Soltar"
      }
    },
    "leave": {
      "label": "Mantén pulsado para salir"
    },
    "delete": {
      "label": "Mantener para eliminar"
    },
    "me": "Yo",
    "overview": {
      "total": "Total"
    },
    "feedback": {
      "question": "¿Qué tal salió el escaneo?",
      "down": "Le echaremos un vistazo.",
      "thanks": "¡Gracias!"
    },
    "autoclose": {
      "description": "Crea la división y actualiza los saldos cuando todos hayan terminado.",
      "title": "Finalizar automáticamente"
    }
  },
  "fr-FR": {
    "splitter": {
      "stack": {
        "claim": "Tout récupérer",
        "release": "Relâcher"
      }
    },
    "leave": {
      "label": "Maintenir pour quitter"
    },
    "delete": {
      "label": "Maintenir pour supprimer"
    },
    "me": "Moi",
    "overview": {
      "total": "Total"
    },
    "feedback": {
      "question": "Comment s'est passé le scan ?",
      "down": "Nous allons jeter un œil.",
      "thanks": "Merci !"
    },
    "autoclose": {
      "description": "Crée le partage et mets à jour les soldes quand tout le monde a terminé.",
      "title": "Terminer automatiquement"
    }
  },
  "hi-IN": {
    "splitter": {
      "stack": {
        "claim": "सभी प्राप्त करें",
        "release": "छोड़ें"
      }
    },
    "leave": {
      "label": "छोड़ने के लिए दबाए रखें"
    },
    "delete": {
      "label": "हटाने के लिए दबाकर रखें"
    },
    "me": "मैं",
    "overview": {
      "total": "कुल"
    },
    "feedback": {
      "question": "स्कैन कैसा रहा?",
      "down": "हम देख लेंगे।",
      "thanks": "धन्यवाद!"
    },
    "autoclose": {
      "description": "स्प्लिट बनाएं और जब सभी पूरा कर लें तो बैलेंस अपडेट करें।",
      "title": "स्वचालित रूप से समाप्त करें"
    }
  },
  "it-IT": {
    "splitter": {
      "stack": {
        "claim": "Riscuoti tutto",
        "release": "Rilascia"
      }
    },
    "leave": {
      "label": "Tieni premuto per uscire"
    },
    "delete": {
      "label": "Tieni premuto per eliminare"
    },
    "me": "Me",
    "overview": {
      "total": "Totale"
    },
    "feedback": {
      "question": "Com'è venuta la scansione?",
      "down": "Daremo un’occhiata.",
      "thanks": "Grazie!"
    },
    "autoclose": {
      "description": "Crea la suddivisione e aggiorna i saldi quando tutti hanno finito.",
      "title": "Completamento automatico"
    }
  },
  "ja-JP": {
    "splitter": {
      "stack": {
        "claim": "すべて受け取る",
        "release": "離す"
      }
    },
    "leave": {
      "label": "長押しで退出"
    },
    "delete": {
      "label": "長押しで削除"
    },
    "me": "私",
    "overview": {
      "total": "合計"
    },
    "feedback": {
      "question": "スキャンの出来栄えはどうでしたか？",
      "down": "確認します。",
      "thanks": "ありがとうございます！"
    },
    "autoclose": {
      "description": "全員が完了したら、精算を作成して残高を更新してください。",
      "title": "自動で完了"
    }
  },
  "ko-KR": {
    "splitter": {
      "stack": {
        "claim": "모두 받기",
        "release": "놓기"
      }
    },
    "leave": {
      "label": "길게 눌러 나가기"
    },
    "delete": {
      "label": "길게 눌러서 삭제"
    },
    "me": "나",
    "overview": {
      "total": "합계"
    },
    "feedback": {
      "question": "스캔은 어땠나요?",
      "down": "확인해 보겠습니다.",
      "thanks": "감사합니다!"
    },
    "autoclose": {
      "description": "모두 완료되면 분할을 생성하고 잔액을 업데이트하세요.",
      "title": "자동으로 완료"
    }
  },
  "nl-NL": {
    "splitter": {
      "stack": {
        "claim": "Alles claimen",
        "release": "Loslaten"
      }
    },
    "leave": {
      "label": "Houd vast om te verlaten"
    },
    "delete": {
      "label": "Vasthouden om te verwijderen"
    },
    "me": "Ik",
    "overview": {
      "total": "Totaal"
    },
    "feedback": {
      "question": "Hoe is de scan geworden?",
      "down": "We zullen ernaar kijken.",
      "thanks": "Dank je!"
    },
    "autoclose": {
      "description": "Maak de verdeling en werk de saldi bij zodra iedereen klaar is.",
      "title": "Automatisch voltooien"
    }
  },
  "ru-RU": {
    "splitter": {
      "stack": {
        "claim": "Забрать всё",
        "release": "Отпустить"
      }
    },
    "leave": {
      "label": "Удерживайте, чтобы выйти"
    },
    "delete": {
      "label": "Удерживайте для удаления"
    },
    "me": "Я",
    "overview": {
      "total": "Итого"
    },
    "feedback": {
      "question": "Как получился скан?",
      "down": "Мы посмотрим.",
      "thanks": "Спасибо!"
    },
    "autoclose": {
      "description": "Создайте разделение и обновите балансы, когда все будут готовы.",
      "title": "Завершить автоматически"
    }
  },
  "sw-TZ": {
    "splitter": {
      "stack": {
        "claim": "Dai zote",
        "release": "Achia"
      }
    },
    "leave": {
      "label": "Shikilia kuondoka"
    },
    "delete": {
      "label": "Shikilia kufuta"
    },
    "me": "Mimi",
    "overview": {
      "total": "Jumla"
    },
    "feedback": {
      "question": "Uchunguzi ulitokeaje?",
      "down": "Tutaangalia.",
      "thanks": "Asante!"
    },
    "autoclose": {
      "description": "Unda mgawanyo na sasisha salio pindi kila mtu atakapomaliza.",
      "title": "Maliza kiotomatiki"
    }
  },
  "tr-TR": {
    "splitter": {
      "stack": {
        "claim": "Hepsini al",
        "release": "Bırak"
      }
    },
    "leave": {
      "label": "Ayrılmak için basılı tut"
    },
    "delete": {
      "label": "Silmek için basılı tutun"
    },
    "me": "Ben",
    "overview": {
      "total": "Toplam"
    },
    "feedback": {
      "question": "Tarama nasıl oldu?",
      "down": "Bir göz atacağız.",
      "thanks": "Teşekkürler!"
    },
    "autoclose": {
      "description": "Herkes işi bitirdiğinde bölüşümü oluşturun ve bakiyeleri güncelleyin.",
      "title": "Otomatik olarak bitir"
    }
  },
  "uk-UA": {
    "splitter": {
      "stack": {
        "claim": "Забрати все",
        "release": "Відпустити"
      }
    },
    "leave": {
      "label": "Утримуйте, щоб вийти"
    },
    "delete": {
      "label": "Утримуйте для видалення"
    },
    "me": "Я",
    "overview": {
      "total": "Разом"
    },
    "feedback": {
      "question": "Як вийшов скан?",
      "down": "Ми подивимось.",
      "thanks": "Дякую!"
    },
    "autoclose": {
      "description": "Створіть поділ і оновіть баланси, коли всі завершать.",
      "title": "Завершити автоматично"
    }
  },
  "zh-CN": {
    "splitter": {
      "stack": {
        "claim": "全部领取",
        "release": "释放"
      }
    },
    "leave": {
      "label": "按住离开"
    },
    "delete": {
      "label": "长按删除"
    },
    "me": "我",
    "overview": {
      "total": "合计"
    },
    "feedback": {
      "question": "扫描效果怎么样？",
      "down": "我们会查看一下。",
      "thanks": "谢谢！"
    },
    "autoclose": {
      "description": "等所有人都完成后，创建分账并更新余额。",
      "title": "自动完成"
    }
  }
};
/** @type {import("./types").Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];

