// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("./types").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "splitter": {
      "stack": {
        "claim": "المطالبة بالجميع",
        "release": "إفلات"
      }
    },
    "leave": {
      "label": "اضغط مطولًا للمغادرة"
    },
    "delete": {
      "label": "اضغط مطولاً للحذف"
    }
  },
  "de-DE": {
    "splitter": {
      "stack": {
        "claim": "Alles einfordern",
        "release": "Loslassen"
      }
    },
    "leave": {
      "label": "Zum Verlassen halten"
    },
    "delete": {
      "label": "Zum Löschen halten"
    }
  },
  "en-US": {
    "splitter": {
      "stack": {
        "claim": "Claim all",
        "release": "Release"
      }
    },
    "leave": {
      "label": "Hold to leave"
    },
    "delete": {
      "label": "Hold to delete"
    }
  },
  "es-ES": {
    "splitter": {
      "stack": {
        "claim": "Reclamar todo",
        "release": "Soltar"
      }
    },
    "leave": {
      "label": "Mantén pulsado para salir"
    },
    "delete": {
      "label": "Mantener para eliminar"
    }
  },
  "fr-FR": {
    "splitter": {
      "stack": {
        "claim": "Tout récupérer",
        "release": "Relâcher"
      }
    },
    "leave": {
      "label": "Maintenir pour quitter"
    },
    "delete": {
      "label": "Maintenir pour supprimer"
    }
  },
  "hi-IN": {
    "splitter": {
      "stack": {
        "claim": "सभी प्राप्त करें",
        "release": "छोड़ें"
      }
    },
    "leave": {
      "label": "छोड़ने के लिए दबाए रखें"
    },
    "delete": {
      "label": "हटाने के लिए दबाकर रखें"
    }
  },
  "it-IT": {
    "splitter": {
      "stack": {
        "claim": "Riscuoti tutto",
        "release": "Rilascia"
      }
    },
    "leave": {
      "label": "Tieni premuto per uscire"
    },
    "delete": {
      "label": "Tieni premuto per eliminare"
    }
  },
  "ja-JP": {
    "splitter": {
      "stack": {
        "claim": "すべて受け取る",
        "release": "離す"
      }
    },
    "leave": {
      "label": "長押しで退出"
    },
    "delete": {
      "label": "長押しで削除"
    }
  },
  "ko-KR": {
    "splitter": {
      "stack": {
        "claim": "모두 받기",
        "release": "놓기"
      }
    },
    "leave": {
      "label": "길게 눌러 나가기"
    },
    "delete": {
      "label": "길게 눌러서 삭제"
    }
  },
  "nl-NL": {
    "splitter": {
      "stack": {
        "claim": "Alles claimen",
        "release": "Loslaten"
      }
    },
    "leave": {
      "label": "Houd vast om te verlaten"
    },
    "delete": {
      "label": "Vasthouden om te verwijderen"
    }
  },
  "ru-RU": {
    "splitter": {
      "stack": {
        "claim": "Забрать всё",
        "release": "Отпустить"
      }
    },
    "leave": {
      "label": "Удерживайте, чтобы выйти"
    },
    "delete": {
      "label": "Удерживайте для удаления"
    }
  },
  "sw-TZ": {
    "splitter": {
      "stack": {
        "claim": "Dai zote",
        "release": "Achia"
      }
    },
    "leave": {
      "label": "Shikilia kuondoka"
    },
    "delete": {
      "label": "Shikilia kufuta"
    }
  },
  "tr-TR": {
    "splitter": {
      "stack": {
        "claim": "Hepsini al",
        "release": "Bırak"
      }
    },
    "leave": {
      "label": "Ayrılmak için basılı tut"
    },
    "delete": {
      "label": "Silmek için basılı tutun"
    }
  },
  "uk-UA": {
    "splitter": {
      "stack": {
        "claim": "Забрати все",
        "release": "Відпустити"
      }
    },
    "leave": {
      "label": "Утримуйте, щоб вийти"
    },
    "delete": {
      "label": "Утримуйте для видалення"
    }
  },
  "zh-CN": {
    "splitter": {
      "stack": {
        "claim": "全部领取",
        "release": "释放"
      }
    },
    "leave": {
      "label": "按住离开"
    },
    "delete": {
      "label": "长按删除"
    }
  }
};
/** @type {import("./types").Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];

