// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("$lib/intl").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "totals": {
      "negative": "أنت مدين لأصدقائك",
      "positive": "الأصدقاء مدينون لك"
    },
    "tops": {
      "title": "الديون",
      "empty": "حتى الآن، لا أحد مدين لك وأنت لا تدين لأحد بأي شيء.",
      "negative": "أنت مدين في الغالب لـ:",
      "positive": "أكثر من يدينون لك:"
    },
    "groups": {
      "title": "ينتمي إلى المجموعات",
      "empty": "لست عضوًا في أي مجموعة."
    },
    "expenses": {
      "title": "الفعاليات",
      "empty": "لا توجد مصروفات مشتركة حتى الآن."
    },
    "delete": {
      "label": "اضغط مع الاستمرار للحذف"
    }
  },
  "de-DE": {
    "totals": {
      "negative": "Du stehst bei deinen Freunden in der Schuld",
      "positive": "Freunde schulden dir etwas"
    },
    "tops": {
      "title": "Schulden",
      "empty": "Bisher schuldet dir niemand etwas und du schuldest auch nichts.",
      "negative": "Du schuldest hauptsächlich:",
      "positive": "Wer dir am meisten schuldet:"
    },
    "groups": {
      "title": "Gehört zu Gruppen",
      "empty": "Du bist in keiner Gruppe Mitglied."
    },
    "expenses": {
      "title": "Veranstaltungen",
      "empty": "Bisher keine geteilten Ausgaben."
    },
    "delete": {
      "label": "Zum Löschen gedrückt halten"
    }
  },
  "en-US": {
    "totals": {
      "negative": "You owe your friends",
      "positive": "Friends owe you"
    },
    "tops": {
      "title": "Debts",
      "empty": "So far, nobody owes you and you owe nothing.",
      "negative": "You owe mostly to:",
      "positive": "Owe you the most:"
    },
    "groups": {
      "title": "Belongs to groups",
      "empty": "Not a member of any group."
    },
    "expenses": {
      "title": "Events",
      "empty": "No shared expenses so far."
    },
    "delete": {
      "label": "Hold to delete"
    }
  },
  "es-ES": {
    "totals": {
      "negative": "Les debes a tus amigos",
      "positive": "Tus amigos te deben"
    },
    "tops": {
      "title": "Deudas",
      "empty": "Hasta ahora, nadie te debe nada y tú no debes nada.",
      "negative": "Principalmente debes a:",
      "positive": "Quienes más te deben:"
    },
    "groups": {
      "title": "Pertenece a grupos",
      "empty": "No eres miembro de ningún grupo."
    },
    "expenses": {
      "title": "Eventos",
      "empty": "No hay gastos compartidos hasta ahora."
    },
    "delete": {
      "label": "Mantén presionado para eliminar"
    }
  },
  "fr-FR": {
    "totals": {
      "negative": "Tu dois à tes amis",
      "positive": "Tes amis te doivent quelque chose"
    },
    "tops": {
      "title": "Dettes",
      "empty": "Pour l’instant, personne ne te doit rien et tu ne dois rien non plus.",
      "negative": "Vous devez principalement à :",
      "positive": "Ceux qui te doivent le plus :"
    },
    "groups": {
      "title": "Appartient aux groupes",
      "empty": "Vous n'êtes membre d'aucun groupe."
    },
    "expenses": {
      "title": "Événements",
      "empty": "Aucune dépense partagée pour le moment."
    },
    "delete": {
      "label": "Maintenir pour supprimer"
    }
  },
  "hi-IN": {
    "totals": {
      "negative": "आप अपने दोस्तों के ऋणी हैं",
      "positive": "दोस्त तुम्हारे ऋणी हैं"
    },
    "tops": {
      "title": "कर्ज़",
      "empty": "अभी तक कोई भी आपको कुछ नहीं लौटाता और आप भी किसी के कर्जदार नहीं हैं।",
      "negative": "आप मुख्यतः इनसे उधार हैं:",
      "positive": "जो आपको सबसे ज़्यादा पैसे देते हैं:"
    },
    "groups": {
      "title": "समूहों का सदस्य है",
      "empty": "आप किसी भी समूह के सदस्य नहीं हैं।"
    },
    "expenses": {
      "title": "आयोजन",
      "empty": "अब तक कोई साझा खर्च नहीं हुआ है।"
    },
    "delete": {
      "label": "हटाने के लिए दबाए रखें"
    }
  },
  "it-IT": {
    "totals": {
      "negative": "Devi qualcosa ai tuoi amici",
      "positive": "Gli amici ti devono qualcosa"
    },
    "tops": {
      "title": "Debiti",
      "empty": "Finora nessuno ti deve nulla e tu non devi niente a nessuno.",
      "negative": "Devi principalmente a:",
      "positive": "Chi ti deve di più:"
    },
    "groups": {
      "title": "Appartiene ai gruppi",
      "empty": "Non fai parte di nessun gruppo."
    },
    "expenses": {
      "title": "Eventi",
      "empty": "Nessuna spesa condivisa finora."
    },
    "delete": {
      "label": "Tieni premuto per eliminare"
    }
  },
  "ja-JP": {
    "totals": {
      "negative": "あなたは友達に借りがあります",
      "positive": "友達があなたに借りがある"
    },
    "tops": {
      "title": "借金",
      "empty": "今のところ、誰もあなたに借りはなく、あなたも誰にも借りはありません。",
      "negative": "主に借りている相手：",
      "positive": "あなたに最も多く借りている人:"
    },
    "groups": {
      "title": "所属グループ",
      "empty": "どのグループにも所属していません。"
    },
    "expenses": {
      "title": "イベント",
      "empty": "これまでに共有された支出はありません。"
    },
    "delete": {
      "label": "長押しで削除"
    }
  },
  "ko-KR": {
    "totals": {
      "negative": "당신은 친구들에게 빚이 있습니다",
      "positive": "친구들이 당신에게 빚졌어요"
    },
    "tops": {
      "title": "빚",
      "empty": "지금까지 아무도 당신에게 빚진 것이 없고, 당신도 아무에게도 빚이 없습니다.",
      "negative": "주로 빚이 있는 사람:",
      "positive": "가장 많이 빚진 사람:"
    },
    "groups": {
      "title": "소속 그룹",
      "empty": "어떤 그룹에도 속해 있지 않습니다."
    },
    "expenses": {
      "title": "이벤트",
      "empty": "아직 공유된 지출이 없습니다."
    },
    "delete": {
      "label": "길게 눌러 삭제"
    }
  },
  "nl-NL": {
    "totals": {
      "negative": "Je bent je vrienden wat verschuldigd",
      "positive": "Vrienden zijn je iets verschuldigd"
    },
    "tops": {
      "title": "Schulden",
      "empty": "Tot nu toe is niemand jou iets verschuldigd en jij bent niemand iets verschuldigd.",
      "negative": "Je bent vooral iets verschuldigd aan:",
      "positive": "Degenen die jou het meest schuldig zijn:"
    },
    "groups": {
      "title": "Behoort tot groepen",
      "empty": "Je bent geen lid van een groep."
    },
    "expenses": {
      "title": "Evenementen",
      "empty": "Tot nu toe geen gedeelde uitgaven."
    },
    "delete": {
      "label": "Houd vast om te verwijderen"
    }
  },
  "ru-RU": {
    "totals": {
      "negative": "Ты должен своим друзьям",
      "positive": "Друзья тебе должны"
    },
    "tops": {
      "title": "Долги",
      "empty": "Пока что тебе никто не должен, и ты тоже никому не должен.",
      "negative": "В основном вы должны:",
      "positive": "Больше всех должны тебе:"
    },
    "groups": {
      "title": "Состоит в группах",
      "empty": "Вы не состоите ни в одной группе."
    },
    "expenses": {
      "title": "События",
      "empty": "Пока нет совместных расходов."
    },
    "delete": {
      "label": "Удерживайте для удаления"
    }
  },
  "sw-TZ": {
    "totals": {
      "negative": "Unadaiwa na marafiki zako",
      "positive": "Marafiki wanakudai"
    },
    "tops": {
      "title": "Madeni",
      "empty": "Hadi sasa, hakuna anayekudai na wewe haumdai mtu yeyote.",
      "negative": "Una deni mkubwa hasa kwa:",
      "positive": "Waliokukudai zaidi:"
    },
    "groups": {
      "title": "Anahusishwa na vikundi",
      "empty": "Sio mwanachama wa kundi lolote."
    },
    "expenses": {
      "title": "Matukio",
      "empty": "Hakuna gharama za pamoja hadi sasa."
    },
    "delete": {
      "label": "Shikilia ili ufute"
    }
  },
  "tr-TR": {
    "totals": {
      "negative": "Arkadaşlarına borçlusun",
      "positive": "Arkadaşların sana borçlu"
    },
    "tops": {
      "title": "Borçlar",
      "empty": "Şu ana kadar kimse sana borçlu değil ve sen de kimseye borçlu değilsin.",
      "negative": "En çok borçlu olduğunuz kişiler:",
      "positive": "Sana en çok borcu olanlar:"
    },
    "groups": {
      "title": "Gruplara ait",
      "empty": "Herhangi bir grubun üyesi değilsin."
    },
    "expenses": {
      "title": "Etkinlikler",
      "empty": "Şu ana kadar paylaşılan bir harcama yok."
    },
    "delete": {
      "label": "Silmek için basılı tutun"
    }
  },
  "uk-UA": {
    "totals": {
      "negative": "Ти винен своїм друзям",
      "positive": "Друзі тобі винні"
    },
    "tops": {
      "title": "Борги",
      "empty": "Поки що тобі ніхто не винен, і ти теж нікому не винен.",
      "negative": "Ви найбільше винні:",
      "positive": "Хто найбільше тобі винен:"
    },
    "groups": {
      "title": "Належить до груп",
      "empty": "Ви не є учасником жодної групи."
    },
    "expenses": {
      "title": "Події",
      "empty": "Поки що спільних витрат немає."
    },
    "delete": {
      "label": "Утримуйте, щоб видалити"
    }
  },
  "zh-CN": {
    "totals": {
      "negative": "你欠你的朋友",
      "positive": "朋友们欠你"
    },
    "tops": {
      "title": "债务",
      "empty": "到目前为止，没有人欠你，你也不欠任何人。",
      "negative": "你主要欠款给：",
      "positive": "欠你最多的人："
    },
    "groups": {
      "title": "所属群组",
      "empty": "未加入任何群组。"
    },
    "expenses": {
      "title": "活动",
      "empty": "目前还没有共享支出。"
    },
    "delete": {
      "label": "按住以删除"
    }
  }
};
