// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "totals": {
      "negative": "أنت مدين لأصدقائك",
      "positive": "الأصدقاء مدينون لك"
    }
  },
  "de-DE": {
    "totals": {
      "negative": "Du stehst bei deinen Freunden in der Schuld",
      "positive": "Freunde schulden dir etwas"
    }
  },
  "en-US": {
    "totals": {
      "negative": "You owe your friends",
      "positive": "Friends owe you"
    }
  },
  "es-ES": {
    "totals": {
      "negative": "Les debes a tus amigos",
      "positive": "Tus amigos te deben"
    }
  },
  "fr-FR": {
    "totals": {
      "negative": "Tu dois à tes amis",
      "positive": "Tes amis te doivent quelque chose"
    }
  },
  "hi-IN": {
    "totals": {
      "negative": "आप अपने दोस्तों के ऋणी हैं",
      "positive": "दोस्त तुम्हारे ऋणी हैं"
    }
  },
  "it-IT": {
    "totals": {
      "negative": "Devi qualcosa ai tuoi amici",
      "positive": "Gli amici ti devono qualcosa"
    }
  },
  "ja-JP": {
    "totals": {
      "negative": "あなたは友達に借りがあります",
      "positive": "友達があなたに借りがある"
    }
  },
  "ko-KR": {
    "totals": {
      "negative": "당신은 친구들에게 빚이 있습니다",
      "positive": "친구들이 당신에게 빚졌어요"
    }
  },
  "nl-NL": {
    "totals": {
      "negative": "Je bent je vrienden wat verschuldigd",
      "positive": "Vrienden zijn je iets verschuldigd"
    }
  },
  "ru-RU": {
    "totals": {
      "negative": "Ты должен своим друзьям",
      "positive": "Друзья тебе должны"
    }
  },
  "sw-TZ": {
    "totals": {
      "negative": "Unadaiwa na marafiki zako",
      "positive": "Marafiki wanakudai"
    }
  },
  "tr-TR": {
    "totals": {
      "negative": "Arkadaşlarına borçlusun",
      "positive": "Arkadaşların sana borçlu"
    }
  },
  "uk-UA": {
    "totals": {
      "negative": "Ти винен своїм друзям",
      "positive": "Друзі тобі винні"
    }
  },
  "zh-CN": {
    "totals": {
      "negative": "你欠你的朋友",
      "positive": "朋友们欠你"
    }
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];
