// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "totals": {
      "negative": "أنت مدين لأصدقائك",
      "positive": "الأصدقاء مدينون لك"
    },
    "tops": {
      "title": "الأصدقاء",
      "empty": "حتى الآن، لا أحد مدين لك وأنت لا تدين لأحد بأي شيء.",
      "negative": "أنت مدين في الغالب لـ:",
      "positive": "أكثر من يدينون لك:"
    }
  },
  "de-DE": {
    "totals": {
      "negative": "Du stehst bei deinen Freunden in der Schuld",
      "positive": "Freunde schulden dir etwas"
    },
    "tops": {
      "title": "Freunde",
      "empty": "Bisher schuldet dir niemand etwas und du schuldest auch nichts.",
      "negative": "Du schuldest hauptsächlich:",
      "positive": "Wer dir am meisten schuldet:"
    }
  },
  "en-US": {
    "totals": {
      "negative": "You owe your friends",
      "positive": "Friends owe you"
    },
    "tops": {
      "title": "Friends",
      "empty": "So far, nobody owes you and you owe nothing.",
      "negative": "You owe mostly to:",
      "positive": "Owe you the most:"
    }
  },
  "es-ES": {
    "totals": {
      "negative": "Les debes a tus amigos",
      "positive": "Tus amigos te deben"
    },
    "tops": {
      "title": "Amigos",
      "empty": "Hasta ahora, nadie te debe nada y tú no debes nada.",
      "negative": "Principalmente debes a:",
      "positive": "Quienes más te deben:"
    }
  },
  "fr-FR": {
    "totals": {
      "negative": "Tu dois à tes amis",
      "positive": "Tes amis te doivent quelque chose"
    },
    "tops": {
      "title": "Amis",
      "empty": "Pour l’instant, personne ne te doit rien et tu ne dois rien non plus.",
      "negative": "Vous devez principalement à :",
      "positive": "Ceux qui te doivent le plus :"
    }
  },
  "hi-IN": {
    "totals": {
      "negative": "आप अपने दोस्तों के ऋणी हैं",
      "positive": "दोस्त तुम्हारे ऋणी हैं"
    },
    "tops": {
      "title": "मित्र",
      "empty": "अभी तक कोई भी आपको कुछ नहीं लौटाता और आप भी किसी के कर्जदार नहीं हैं।",
      "negative": "आप मुख्यतः इनसे उधार हैं:",
      "positive": "जो आपको सबसे ज़्यादा पैसे देते हैं:"
    }
  },
  "it-IT": {
    "totals": {
      "negative": "Devi qualcosa ai tuoi amici",
      "positive": "Gli amici ti devono qualcosa"
    },
    "tops": {
      "title": "Amici",
      "empty": "Finora nessuno ti deve nulla e tu non devi niente a nessuno.",
      "negative": "Devi principalmente a:",
      "positive": "Chi ti deve di più:"
    }
  },
  "ja-JP": {
    "totals": {
      "negative": "あなたは友達に借りがあります",
      "positive": "友達があなたに借りがある"
    },
    "tops": {
      "title": "友達",
      "empty": "今のところ、誰もあなたに借りはなく、あなたも誰にも借りはありません。",
      "negative": "主に借りている相手：",
      "positive": "あなたに最も多く借りている人:"
    }
  },
  "ko-KR": {
    "totals": {
      "negative": "당신은 친구들에게 빚이 있습니다",
      "positive": "친구들이 당신에게 빚졌어요"
    },
    "tops": {
      "title": "친구",
      "empty": "지금까지 아무도 당신에게 빚진 것이 없고, 당신도 아무에게도 빚이 없습니다.",
      "negative": "주로 빚이 있는 사람:",
      "positive": "가장 많이 빚진 사람:"
    }
  },
  "nl-NL": {
    "totals": {
      "negative": "Je bent je vrienden wat verschuldigd",
      "positive": "Vrienden zijn je iets verschuldigd"
    },
    "tops": {
      "title": "Vrienden",
      "empty": "Tot nu toe is niemand jou iets verschuldigd en jij bent niemand iets verschuldigd.",
      "negative": "Je bent vooral iets verschuldigd aan:",
      "positive": "Degenen die jou het meest schuldig zijn:"
    }
  },
  "ru-RU": {
    "totals": {
      "negative": "Ты должен своим друзьям",
      "positive": "Друзья тебе должны"
    },
    "tops": {
      "title": "Друзья",
      "empty": "Пока что тебе никто не должен, и ты тоже никому не должен.",
      "negative": "В основном вы должны:",
      "positive": "Больше всех должны тебе:"
    }
  },
  "sw-TZ": {
    "totals": {
      "negative": "Unadaiwa na marafiki zako",
      "positive": "Marafiki wanakudai"
    },
    "tops": {
      "title": "Marafiki",
      "empty": "Hadi sasa, hakuna anayekudai na wewe haumdai mtu yeyote.",
      "negative": "Una deni mkubwa hasa kwa:",
      "positive": "Waliokukudai zaidi:"
    }
  },
  "tr-TR": {
    "totals": {
      "negative": "Arkadaşlarına borçlusun",
      "positive": "Arkadaşların sana borçlu"
    },
    "tops": {
      "title": "Arkadaşlar",
      "empty": "Şu ana kadar kimse sana borçlu değil ve sen de kimseye borçlu değilsin.",
      "negative": "En çok borçlu olduğunuz kişiler:",
      "positive": "Sana en çok borcu olanlar:"
    }
  },
  "uk-UA": {
    "totals": {
      "negative": "Ти винен своїм друзям",
      "positive": "Друзі тобі винні"
    },
    "tops": {
      "title": "Друзі",
      "empty": "Поки що тобі ніхто не винен, і ти теж нікому не винен.",
      "negative": "Ви найбільше винні:",
      "positive": "Хто найбільше тобі винен:"
    }
  },
  "zh-CN": {
    "totals": {
      "negative": "你欠你的朋友",
      "positive": "朋友们欠你"
    },
    "tops": {
      "title": "朋友",
      "empty": "到目前为止，没有人欠你，你也不欠任何人。",
      "negative": "你主要欠款给：",
      "positive": "欠你最多的人："
    }
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];
