// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("./types").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "paywall": {
      "title": "إيفنلي بريميوم",
      "offer": {
        "headline": "حتى أفضل مع الاشتراك!",
        "promo": "لفترة محدودة، يتوفر Evnly Premium مجانًا بالكامل.",
        "cta": "ابدأ تجربتك المجانية",
        "disclaimer": "التجربة المجانية متاحة فقط للمشتركين المؤهلين لأول مرة. يجب الإلغاء قبل 24 ساعة من انتهاء التجربة لتجنب الرسوم. سيتم تفعيل الفوترة التلقائية بعد انتهاء الفترة التجريبية المجانية، ويمكنك الإلغاء في أي وقت.",
        "footnote": "‏* يتيح مستخدم بريميوم واحد إمكانية تمييز العناصر لجميع المشاركين. في المغامرات، يتم حفظ نص الإيصال فقط (بدون عرض مرئي للتقسيم).",
        "trial": (price) => `مجاني لمدة 7 أيام، ثم ${price} سنويًا`
      },
      "complete": {
        "thanks": "شكرًا لاشتراكك في Envly Premium",
        "avatarNote": "مبدئيًا، سيرى مستخدمو Evnly الآخرون صورتك الرمزية بهذا الشكل من الآن فصاعدًا.",
        "featuresNote": "بالإضافة إلى ذلك، يمكنك الآن تخصيص الواجهة أكثر في ملفك الشخصي، ومسح الإيصالات والتعرف عليها، والمزيد."
      }
    }
  },
  "de-DE": {
    "paywall": {
      "title": "Evnly Premium",
      "offer": {
        "headline": "Mit Abo wird’s erst richtig Evn!",
        "promo": "Nur für kurze Zeit ist Evnly Premium völlig kostenlos verfügbar.",
        "cta": "Kostenlose Testversion starten",
        "disclaimer": "Kostenlose Testphase nur für berechtigte Erstabonnenten verfügbar. Um eine Berechnung zu vermeiden, kündigen Sie mindestens 24 Stunden vor Ablauf der Testphase. Nach der kostenlosen Testphase wird das Abonnement automatisch verlängert, Kündigung jederzeit möglich.",
        "footnote": "* Ein Premium-Nutzer aktiviert das Markieren von Gegenständen für alle Teilnehmenden. In Abenteuern wird nur der Belegtext gespeichert (keine visuelle Aufteilung).",
        "trial": (price) => `7 Tage kostenlos, danach ${price}/Jahr`
      },
      "complete": {
        "thanks": "Vielen Dank für dein Abonnement von Envly Premium",
        "avatarNote": "Ab jetzt werden andere Evnly-Nutzer dein Avatar so sehen.",
        "featuresNote": "Außerdem kannst du ab sofort die Oberfläche in deinem Profil noch weiter anpassen, Belege scannen und erkennen sowie vieles mehr."
      }
    }
  },
  "en-US": {
    "paywall": {
      "title": "Evnly Premium",
      "offer": {
        "headline": "Evn better with a subscription!",
        "promo": "For a limited time, Evnly Premium is available completely free.",
        "cta": "Start your free trial",
        "disclaimer": "Free trial available only to eligible first time subscribers. Cancel 24 hours before trial ends to avoid charge. Recurring billing after free trial, cancel anytime.",
        "footnote": "* One Premium user enables item marking for all participants. In adventures, only receipt text is saved (no visual split).",
        "trial": (price) => `7-day free, then ${price}/year`
      },
      "complete": {
        "thanks": "Thank you for subscribing to Envly Premium",
        "avatarNote": "From now on, other Evnly users will see your avatar like this.",
        "featuresNote": "Plus, from now on you can further customize the interface in your profile, scan and recognize receipts, and more."
      }
    }
  },
  "es-ES": {
    "paywall": {
      "title": "Evnly Premium",
      "offer": {
        "headline": "¡Mucho más Evn con suscripción!",
        "promo": "Por tiempo limitado, Evnly Premium está disponible totalmente gratis.",
        "cta": "Comienza tu prueba gratis",
        "disclaimer": "Prueba gratuita disponible solo para suscriptores elegibles por primera vez. Cancela 24 horas antes de que termine la prueba para evitar cargos. La suscripción se renovará automáticamente después del periodo de prueba gratuita; puedes cancelar en cualquier momento.",
        "footnote": "* Un usuario Premium permite el marcado de elementos para todos los participantes. En las aventuras, solo se guarda el texto del recibo (sin división visual).",
        "trial": (price) => `7 días gratis, luego ${price}/año`
      },
      "complete": {
        "thanks": "Gracias por suscribirte a Envly Premium",
        "avatarNote": "A partir de ahora, otros usuarios de Evnly verán tu avatar así.",
        "featuresNote": "Además, a partir de ahora puedes personalizar aún más la interfaz en tu perfil, escanear y reconocer recibos y mucho más."
      }
    }
  },
  "fr-FR": {
    "paywall": {
      "title": "Evnly Premium",
      "offer": {
        "headline": "Encore plus Evn avec l’abonnement !",
        "promo": "Pendant une durée limitée, Evnly Premium est disponible entièrement gratuitement.",
        "cta": "Commencer votre essai gratuit",
        "disclaimer": "Essai gratuit réservé uniquement aux nouveaux abonnés éligibles. Annulez 24 heures avant la fin de l’essai pour éviter tout prélèvement. Facturation récurrente après la période d’essai, annulation à tout moment.",
        "footnote": "* Un utilisateur Premium permet le marquage des articles pour tous les participants. Dans les aventures, seul le texte du reçu est enregistré (aucune répartition visuelle).",
        "trial": (price) => `7 jours gratuits, puis ${price}/an`
      },
      "complete": {
        "thanks": "Merci de vous être abonné à Envly Premium",
        "avatarNote": "Désormais, les autres utilisateurs d’Evnly verront votre avatar de cette façon.",
        "featuresNote": "De plus, à partir de maintenant, vous pouvez personnaliser encore davantage l’interface dans votre profil, scanner et reconnaître des reçus, et bien plus encore."
      }
    }
  },
  "hi-IN": {
    "paywall": {
      "title": "Evnly प्रीमियम",
      "offer": {
        "headline": "सब्सक्रिप्शन के साथ Evn और ज़्यादा कमाल!",
        "promo": "सीमित समय के लिए, Evnly Premium पूरी तरह से मुफ्त उपलब्ध है।",
        "cta": "अपना फ्री ट्रायल शुरू करें",
        "disclaimer": "नि:शुल्क ट्रायल केवल योग्य प्रथम बार ग्राहकों के लिए उपलब्ध है। चार्ज से बचने के लिए ट्रायल समाप्त होने से 24 घंटे पहले रद्द करें। नि:शुल्क ट्रायल के बाद आवर्तक बिलिंग स्वचालित रूप से शुरू हो जाएगी, कभी भी रद्द करें।",
        "footnote": "* एक प्रीमियम उपयोगकर्ता सभी प्रतिभागियों के लिए आइटम मार्किंग सक्षम करता है। रोमांचों में केवल रसीद पाठ सेव किया जाता है (कोई दृश्य विभाजन नहीं)।",
        "trial": (price) => `7 दिन मुफ्त, फिर ${price}/वर्ष`
      },
      "complete": {
        "thanks": "Envly Premium की सदस्यता लेने के लिए धन्यवाद",
        "avatarNote": "अब से, अन्य Evnly उपयोगकर्ता आपका अवतार इस तरह देखेंगे।",
        "featuresNote": "इसके अलावा, अब आप अपने प्रोफ़ाइल में इंटरफ़ेस को और भी कस्टमाइज़ कर सकते हैं, रसीदें स्कैन और पहचान सकते हैं, और भी बहुत कुछ कर सकते हैं।"
      }
    }
  },
  "it-IT": {
    "paywall": {
      "title": "Evnly Premium",
      "offer": {
        "headline": "Evn ancora meglio con l’abbonamento!",
        "promo": "Per un periodo limitato, Evnly Premium è disponibile completamente gratis.",
        "cta": "Inizia la prova gratuita",
        "disclaimer": "Prova gratuita disponibile solo per nuovi abbonati idonei. Cancella almeno 24 ore prima della fine della prova per evitare addebiti. Dopo la prova gratuita, la fatturazione sarà ricorrente; è possibile annullare in qualsiasi momento.",
        "footnote": "* Un utente Premium consente la marcatura degli oggetti per tutti i partecipanti. Nelle avventure, viene salvato solo il testo della ricevuta (nessuna suddivisione visiva).",
        "trial": (price) => `7 giorni gratis, poi ${price}/anno`
      },
      "complete": {
        "thanks": "Grazie per esserti abbonato a Envly Premium",
        "avatarNote": "D’ora in poi, gli altri utenti di Evnly vedranno il tuo avatar così.",
        "featuresNote": "Inoltre, da ora puoi personalizzare ulteriormente l’interfaccia nel tuo profilo, scansionare e riconoscere ricevute e molto altro."
      }
    }
  },
  "ja-JP": {
    "paywall": {
      "title": "Evnlyプレミアム",
      "offer": {
        "headline": "サブスクでEvnがさらに進化！",
        "promo": "期間限定で、Evnly Premiumを完全無料でご利用いただけます。",
        "cta": "無料トライアルを開始",
        "disclaimer": "無料トライアルは初めてご利用の対象ユーザーのみ利用できます。料金が発生しないよう、トライアル終了24時間前までにキャンセルしてください。無料トライアル終了後は自動的に継続課金されます。いつでも解約可能です。",
        "footnote": "※ 1人のプレミアムユーザーが全参加者にアイテムマーク機能を有効にします。冒険では、レシートのテキストのみが保存されます（ビジュアルの分割はありません）。",
        "trial": (price) => `7日間無料、その後は${price}/年`
      },
      "complete": {
        "thanks": "Envly Premiumへのご登録ありがとうございます",
        "avatarNote": "これからは、他のEvnlyユーザーがあなたのアバターをこのように表示します。",
        "featuresNote": "さらに、今後はプロフィールからインターフェースをよりカスタマイズしたり、レシートをスキャンして認識したり、さまざまな機能がご利用いただけます。"
      }
    }
  },
  "ko-KR": {
    "paywall": {
      "title": "Evnly 프리미엄",
      "offer": {
        "headline": "구독하면 Evn이 더 좋아져요!",
        "promo": "기간 한정으로 Evnly Premium을 완전히 무료로 이용하실 수 있습니다.",
        "cta": "무료 체험 시작하기",
        "disclaimer": "무료 체험은 자격이 있는 최초 구독자에게만 제공됩니다. 요금이 청구되지 않도록 체험 종료 24시간 전에 해지하세요. 무료 체험 후 반복 결제가 시작되며, 언제든지 해지할 수 있습니다.",
        "footnote": "* 프리미엄 사용자 한 명이 모든 참여자에게 아이템 표시를 활성화합니다. 모험에서는 영수증 텍스트만 저장되며(시각적 분할 없음).",
        "trial": (price) => `7일 무료, 이후 ${price}/연`
      },
      "complete": {
        "thanks": "Envly Premium을 구독해 주셔서 감사합니다",
        "avatarNote": "이제부터 다른 Evnly 사용자들은 당신의 아바타를 이렇게 보게 됩니다.",
        "featuresNote": "또한, 이제부터 프로필에서 인터페이스를 더 세부적으로 맞춤 설정하고, 영수증을 스캔 및 인식하는 등 다양한 기능을 이용하실 수 있습니다."
      }
    }
  },
  "nl-NL": {
    "paywall": {
      "title": "Evnly Premium",
      "offer": {
        "headline": "Evn wordt nog beter met een abonnement!",
        "promo": "Evnly Premium is tijdelijk helemaal gratis beschikbaar.",
        "cta": "Begin je gratis proefperiode",
        "disclaimer": "Gratis proefperiode is alleen beschikbaar voor in aanmerking komende nieuwe abonnees. Annuleer minimaal 24 uur voor het einde van de proefperiode om kosten te voorkomen. Na de gratis proefperiode vindt automatische verlenging plaats; opzeggen kan op elk moment.",
        "footnote": "* Eén Premium-gebruiker maakt het markeren van items mogelijk voor alle deelnemers. In avonturen wordt alleen de tekst van het ontvangstbewijs opgeslagen (geen visuele verdeling).",
        "trial": (price) => `7 dagen gratis, daarna ${price}/jaar`
      },
      "complete": {
        "thanks": "Bedankt voor je abonnement op Envly Premium",
        "avatarNote": "Vanaf nu zien andere Evnly-gebruikers jouw avatar er zo uit.",
        "featuresNote": "Bovendien kun je vanaf nu de interface verder aanpassen in je profiel, bonnetjes scannen en herkennen, en meer."
      }
    }
  },
  "ru-RU": {
    "paywall": {
      "title": "Evnly Премиум",
      "offer": {
        "headline": "Evn становится ещё лучше с подпиской!",
        "promo": "Только ограниченное время: Evnly Premium доступен совершенно бесплатно.",
        "cta": "Начать бесплатную пробную версию",
        "disclaimer": "Бесплатная пробная версия доступна только новым подходящим подписчикам. Отмените за 24 часа до окончания пробного периода, чтобы избежать оплаты. После окончания бесплатного периода списание происходит автоматически, вы можете отменить подписку в любое время.",
        "footnote": "* Один пользователь с подпиской Premium включает возможность пометки предметов для всех участников. В приключениях сохраняется только текст чека (без визуального разделения).",
        "trial": (price) => `7 дней бесплатно, затем ${price} в год`
      },
      "complete": {
        "thanks": "Спасибо за подписку на Envly Premium",
        "avatarNote": "Теперь другие пользователи Evnly будут видеть ваш аватар вот так.",
        "featuresNote": "Кроме того, теперь вы можете ещё больше настраивать интерфейс в своём профиле, сканировать и распознавать чеки и многое другое."
      }
    }
  },
  "sw-TZ": {
    "paywall": {
      "title": "Evnly Premium",
      "offer": {
        "headline": "Evn inakuwa bora zaidi ukiwa na usajili!",
        "promo": "Kwa muda mfupi, Evnly Premium inapatikana bure kabisa.",
        "cta": "Anza jaribio lako bure",
        "disclaimer": "Jaribio la bure linapatikana tu kwa wateja wapya wanaostahiki. Ghairi saa 24 kabla jaribio haliijaisha ili kuepuka malipo. Baada ya kipindi cha jaribio la bure, ada itakatwa kila mara, unaweza kughairi wakati wowote.",
        "footnote": "* Mtumiaji mmoja wa Premium huwasha uandikaji wa bidhaa kwa washiriki wote. Katika safari, maandishi ya risiti pekee ndiyo yanayahifadhiwa (hakuna mgawanyo wa kiona).",
        "trial": (price) => `Bure kwa siku 7, halafu ${price}/mwaka`
      },
      "complete": {
        "thanks": "Asante kwa kujisajili kwenye Envly Premium",
        "avatarNote": "Kuanzia sasa, watumiaji wengine wa Evnly wataona avatar yako hivi.",
        "featuresNote": "Zaidi ya hayo, kuanzia sasa unaweza kubinafsisha zaidi muonekano kwenye wasifu wako, kutambaza na kutambua risiti na mengi zaidi."
      }
    }
  },
  "tr-TR": {
    "paywall": {
      "title": "Evnly Premium",
      "offer": {
        "headline": "Abonelikle Evn çok daha iyi!",
        "promo": "Sınırlı bir süre için, Evnly Premium tamamen ücretsiz olarak sunuluyor.",
        "cta": "Ücretsiz denemeyi başlat",
        "disclaimer": "Ücretsiz deneme yalnızca uygun ve ilk kez abone olanlar için geçerlidir. Ücretlendirmeyi önlemek için deneme sona ermeden 24 saat önce iptal edin. Ücretsiz deneme sonrasında otomatik yenilenir; istediğiniz zaman iptal edebilirsiniz.",
        "footnote": "* Bir Premium kullanıcı, tüm katılımcılar için ürün işaretlemeyi etkinleştirir. Maceralarda yalnızca fiş metni kaydedilir (görsel bölme yoktur).",
        "trial": (price) => `7 gün ücretsiz, ardından ${price}/yıl`
      },
      "complete": {
        "thanks": "Envly Premium’a abone olduğunuz için teşekkürler",
        "avatarNote": "Bundan sonra diğer Evnly kullanıcıları avatarınızı bu şekilde görecek.",
        "featuresNote": "Ayrıca, artık profilinizde arayüzü daha fazla özelleştirebilir, fişleri tarayıp tanıyabilir ve daha fazlasını yapabilirsiniz."
      }
    }
  },
  "uk-UA": {
    "paywall": {
      "title": "Evnly Premium",
      "offer": {
        "headline": "Evn ще крутіше з підпискою!",
        "promo": "Тільки протягом обмеженого часу Evnly Premium доступний абсолютно безкоштовно.",
        "cta": "Почати безкоштовний пробний період",
        "disclaimer": "Безкоштовна пробна версія доступна лише для нових відповідних підписників. Скасуйте за 24 години до завершення пробного періоду, щоб уникнути стягнення плати. Після закінчення безкоштовного періоду діє автоматична підписка — скасувати можна будь-коли.",
        "footnote": "* Один користувач із підпискою Premium дає змогу позначати елементи для всіх учасників. У пригодах зберігається лише текст чеку (без візуального поділу).",
        "trial": (price) => `7 днів безкоштовно, потім ${price} на рік`
      },
      "complete": {
        "thanks": "Дякуємо за підписку на Envly Premium",
        "avatarNote": "Відтепер інші користувачі Evnly бачитимуть ваш аватар ось так.",
        "featuresNote": "До того ж, відтепер ви можете ще більше налаштовувати інтерфейс у своєму профілі, сканувати й розпізнавати чеки та багато іншого."
      }
    }
  },
  "zh-CN": {
    "paywall": {
      "title": "Evnly尊享版",
      "offer": {
        "headline": "订阅让 Evn 更出色！",
        "promo": "限时优惠，Evnly Premium 完全免费开放。",
        "cta": "开始免费试用",
        "disclaimer": "免费试用仅对符合条件的首次订阅用户开放。为避免收费，请在试用结束前24小时取消。免费试用结束后将自动续费，您可随时取消订阅。",
        "footnote": "* 一名高级用户可为所有参与者启用物品标记。在冒险中，仅保存收据文本（无可视化分割）。",
        "trial": (price) => `7天免费，之后${price}/年`
      },
      "complete": {
        "thanks": "感谢您订阅 Envly Premium",
        "avatarNote": "从现在开始，其他 Evnly 用户会这样看到你的头像。",
        "featuresNote": "此外，从现在起，你还可以在个人资料中进一步自定义界面，扫描和识别小票等更多功能。"
      }
    }
  }
};
/** @type {import("./types").Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];

