// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<string, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "demo": {
      "button": "عرض توضيحي"
    }
  },
  "de-DE": {
    "demo": {
      "button": "Demo"
    }
  },
  "en-US": {
    "demo": {
      "button": "Demo"
    }
  },
  "es-ES": {
    "demo": {
      "button": "Demostración"
    }
  },
  "fr-FR": {
    "demo": {
      "button": "Démo"
    }
  },
  "hi-IN": {
    "demo": {
      "button": "डेमो"
    }
  },
  "it-IT": {
    "demo": {
      "button": "Demo"
    }
  },
  "ja-JP": {
    "demo": {
      "button": "デモ"
    }
  },
  "ko-KR": {
    "demo": {
      "button": "데모"
    }
  },
  "nl-NL": {
    "demo": {
      "button": "Demo"
    }
  },
  "ru-RU": {
    "demo": {
      "button": "Демо"
    }
  },
  "sw-TZ": {
    "demo": {
      "button": "Onyesho"
    }
  },
  "tr-TR": {
    "demo": {
      "button": "Demo"
    }
  },
  "uk-UA": {
    "demo": {
      "button": "Демо"
    }
  },
  "zh-CN": {
    "demo": {
      "button": "演示"
    }
  }
};

/** @type {string[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];
