// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "recent": {
      "title": "المصروفات",
      "empty": "لم يحدث شيء بعد. أضف بعض المصروفات أو ادعُ أصدقاءك لبدء النشاط."
    },
    "payer": {
      "placeholder": "اختر الدافع"
    },
    "participants": {
      "tabs": {
        "sums": "حسب المبالغ",
        "shares": "حسب الحصص"
      },
      "add": {
        "label": "إضافة مشاركين"
      }
    }
  },
  "de-DE": {
    "recent": {
      "title": "Ausgaben",
      "empty": "Es ist noch nichts passiert. Füge Ausgaben hinzu oder lade Freunde ein, um loszulegen."
    },
    "payer": {
      "placeholder": "Zahler auswählen"
    },
    "participants": {
      "tabs": {
        "sums": "Nach Beträgen",
        "shares": "Anhand von Anteilen"
      },
      "add": {
        "label": "Teilnehmer hinzufügen"
      }
    }
  },
  "en-US": {
    "recent": {
      "title": "Expenses",
      "empty": "Nothing happened yet. Add some spending or invite friends to get things started."
    },
    "payer": {
      "placeholder": "Select payer"
    },
    "participants": {
      "tabs": {
        "sums": "By sums",
        "shares": "By shares"
      },
      "add": {
        "label": "Add participants"
      }
    }
  },
  "es-ES": {
    "recent": {
      "title": "Gastos",
      "empty": "Aún no ha pasado nada. Añade algún gasto o invita a tus amigos para poner esto en marcha."
    },
    "payer": {
      "placeholder": "Seleccionar pagador"
    },
    "participants": {
      "tabs": {
        "sums": "Por sumas",
        "shares": "Por acciones"
      },
      "add": {
        "label": "Agregar participantes"
      }
    }
  },
  "fr-FR": {
    "recent": {
      "title": "Dépenses",
      "empty": "Rien ne s'est encore passé. Ajoutez des dépenses ou invitez des amis pour lancer les choses."
    },
    "payer": {
      "placeholder": "Sélectionner le payeur"
    },
    "participants": {
      "tabs": {
        "sums": "Par sommes",
        "shares": "Par parts"
      },
      "add": {
        "label": "Ajouter des participants"
      }
    }
  },
  "hi-IN": {
    "recent": {
      "title": "खर्चे",
      "empty": "अभी तक कुछ नहीं हुआ है। कुछ खर्च जोड़ें या शुरुआत करने के लिए दोस्तों को बुलाएं।"
    },
    "payer": {
      "placeholder": "भुगतानकर्ता चुनें"
    },
    "participants": {
      "tabs": {
        "sums": "राशि के अनुसार",
        "shares": "शेयरों के अनुसार"
      },
      "add": {
        "label": "प्रतिभागी जोड़ें"
      }
    }
  },
  "it-IT": {
    "recent": {
      "title": "Spese",
      "empty": "Non è ancora successo nulla. Aggiungi qualche spesa o invita amici per iniziare."
    },
    "payer": {
      "placeholder": "Seleziona il pagatore"
    },
    "participants": {
      "tabs": {
        "sums": "Per somme",
        "shares": "Per quote"
      },
      "add": {
        "label": "Aggiungi partecipanti"
      }
    }
  },
  "ja-JP": {
    "recent": {
      "title": "経費",
      "empty": "まだ何も起きていません。支出を追加したり、友達を招待して始めてみましょう。"
    },
    "payer": {
      "placeholder": "支払者を選択"
    },
    "participants": {
      "tabs": {
        "sums": "合計別",
        "shares": "持分ごとに"
      },
      "add": {
        "label": "参加者を追加"
      }
    }
  },
  "ko-KR": {
    "recent": {
      "title": "지출",
      "empty": "아직 아무 일도 일어나지 않았어요. 지출을 추가하거나 친구를 초대해 시작해보세요."
    },
    "payer": {
      "placeholder": "지불자 선택"
    },
    "participants": {
      "tabs": {
        "sums": "금액별",
        "shares": "지분별로"
      },
      "add": {
        "label": "참가자 추가"
      }
    }
  },
  "nl-NL": {
    "recent": {
      "title": "Uitgaven",
      "empty": "Er is nog niets gebeurd. Voeg wat uitgaven toe of nodig vrienden uit om op gang te komen."
    },
    "payer": {
      "placeholder": "Betaler selecteren"
    },
    "participants": {
      "tabs": {
        "sums": "Op bedragen",
        "shares": "Op basis van aandelen"
      },
      "add": {
        "label": "Deelnemers toevoegen"
      }
    }
  },
  "ru-RU": {
    "recent": {
      "title": "Расходы",
      "empty": "Пока ничего не произошло. Добавьте расходы или пригласите друзей, чтобы начать."
    },
    "payer": {
      "placeholder": "Выберите плательщика"
    },
    "participants": {
      "tabs": {
        "sums": "По суммам",
        "shares": "По долям"
      },
      "add": {
        "label": "Добавить участников"
      }
    }
  },
  "sw-TZ": {
    "recent": {
      "title": "Matumizi",
      "empty": "Bado hakuna kilichotokea. Ongeza matumizi au alika marafiki ili mambo yaanze."
    },
    "payer": {
      "placeholder": "Chagua mtoaji wa malipo"
    },
    "participants": {
      "tabs": {
        "sums": "Kwa jumla",
        "shares": "Kwa hisa"
      },
      "add": {
        "label": "Ongeza washiriki"
      }
    }
  },
  "tr-TR": {
    "recent": {
      "title": "Giderler",
      "empty": "Henüz hiçbir şey olmadı. Biraz harcama ekleyin veya arkadaşlarınızı davet edin, böylece her şey başlasın."
    },
    "payer": {
      "placeholder": "Ödeyeni seç"
    },
    "participants": {
      "tabs": {
        "sums": "Toplamlara göre",
        "shares": "Hisselere göre"
      },
      "add": {
        "label": "Katılımcı ekle"
      }
    }
  },
  "uk-UA": {
    "recent": {
      "title": "Витрати",
      "empty": "Поки що нічого не сталося. Додайте витрати або запросіть друзів, щоб розпочати."
    },
    "payer": {
      "placeholder": "Виберіть платника"
    },
    "participants": {
      "tabs": {
        "sums": "За сумами",
        "shares": "За частками"
      },
      "add": {
        "label": "Додати учасників"
      }
    }
  },
  "zh-CN": {
    "recent": {
      "title": "支出",
      "empty": "还没有任何活动。添加一些支出或邀请朋友一起开启新体验吧。"
    },
    "payer": {
      "placeholder": "选择付款方"
    },
    "participants": {
      "tabs": {
        "sums": "按金额",
        "shares": "按份额"
      },
      "add": {
        "label": "添加参与者"
      }
    }
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];
