// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "recent": {
      "title": "مال",
      "empty": "لم يحدث شيء بعد. أضف بعض المصروفات أو ادعُ أصدقاءك لبدء النشاط."
    },
    "payer": {
      "placeholder": "اختر الدافع"
    },
    "participants": {
      "tabs": {
        "sums": "حسب المبالغ",
        "shares": "حسب الحصص"
      },
      "add": {
        "label": "إضافة مشاركين"
      }
    },
    "transfer": {
      "action": "تحويل",
      "dialog": {
        "title": "تسوية الحساب",
        "cancel": "إلغاء",
        "action": "تأكيد"
      },
      "me": "أنا",
      "direction": {
        "byme": (gender) => gender === "he" ? "لقد دفعت" : (gender === "she" ? "لقد دفعتِ" : "لقد دفعت"),
        "tome": (gender) => gender === "he" ? "لقد استلمت" : (gender === "she" ? "لقد استلمتِ" : "لقد استلمت")
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "ستكون قد استقررت تمامًا",
        "positive": "سيكون لك دين",
        "negative": "سَتَدِين"
      },
      "done": {
        "paid": (gender) => gender === "he" ? "لقد دفعتَ" : gender === "she" ? "لقد دفعتِ" : "لقد دفعت",
        "received": (gender) => gender === "he" ? "لقد استلمتَ" : gender === "she" ? "لقد استلمتِ" : "لقد استلمت"
      }
    }
  },
  "de-DE": {
    "recent": {
      "title": "Geld",
      "empty": "Es ist noch nichts passiert. Füge Ausgaben hinzu oder lade Freunde ein, um loszulegen."
    },
    "payer": {
      "placeholder": "Zahler auswählen"
    },
    "participants": {
      "tabs": {
        "sums": "Nach Beträgen",
        "shares": "Anhand von Anteilen"
      },
      "add": {
        "label": "Teilnehmer hinzufügen"
      }
    },
    "transfer": {
      "action": "Überweisung",
      "dialog": {
        "title": "Ausgleichen",
        "cancel": "Abbrechen",
        "action": "Bestätigen"
      },
      "me": "Ich",
      "direction": {
        "byme": (gender) => gender === "he" ? "Ich habe bezahlt" : (gender === "she" ? "Ich habe bezahlt" : "Ich habe bezahlt"),
        "tome": (gender) => gender === "he" ? "Ich habe erhalten" : (gender === "she" ? "Ich habe erhalten" : "Ich habe erhalten")
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "Du wirst ganz angekommen sein",
        "positive": "Es wird dir geschuldet",
        "negative": "Du hast eine offene Forderung"
      },
      "done": {
        "paid": (gender) => gender === "he" ? "Du hast bezahlt" : gender === "she" ? "Du hast bezahlt" : "Du hast bezahlt",
        "received": (gender) => gender === "he" ? "Du hast bekommen" : gender === "she" ? "Du hast bekommen" : "Du hast bekommen"
      }
    }
  },
  "en-US": {
    "recent": {
      "title": "Money",
      "empty": "Nothing happened yet. Add some spending or invite friends to get things started."
    },
    "payer": {
      "placeholder": "Select payer"
    },
    "participants": {
      "tabs": {
        "sums": "By sums",
        "shares": "By shares"
      },
      "add": {
        "label": "Add participants"
      }
    },
    "transfer": {
      "action": "Transfer",
      "dialog": {
        "title": "Settle Up",
        "cancel": "Cancel",
        "action": "Confirm"
      },
      "me": "Me",
      "direction": {
        "byme": (gender) => "I paid",
        "tome": (gender) => "I received"
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "You’ll be all settled",
        "positive": "You'll be owed",
        "negative": "You’ll owe"
      },
      "done": {
        "paid": (gender) => "You’ve paid",
        "received": (gender) => gender === "he" ? "You've received" : gender === "she" ? "You've received" : "You've received"
      }
    }
  },
  "es-ES": {
    "recent": {
      "title": "Dinero",
      "empty": "Aún no ha pasado nada. Añade algún gasto o invita a tus amigos para poner esto en marcha."
    },
    "payer": {
      "placeholder": "Seleccionar pagador"
    },
    "participants": {
      "tabs": {
        "sums": "Por sumas",
        "shares": "Por acciones"
      },
      "add": {
        "label": "Agregar participantes"
      }
    },
    "transfer": {
      "action": "Transferencia",
      "dialog": {
        "title": "Pagar la cuenta",
        "cancel": "Cancelar",
        "action": "Confirmar"
      },
      "me": "Yo",
      "direction": {
        "byme": (gender) => gender === "he" ? "He pagado" : (gender === "she" ? "He pagado" : "He pagado"),
        "tome": (gender) => gender === "he" ? "He recibido" : (gender === "she" ? "He recibido" : "He recibido")
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "Estarás completamente instalado",
        "positive": "Te lo deberán",
        "negative": "Tendrás una deuda"
      },
      "done": {
        "paid": (gender) => gender === "he" ? "Has pagado" : gender === "she" ? "Has pagado" : "Has pagado",
        "received": (gender) => gender === "he" ? "Has recibido" : gender === "she" ? "Has recibido" : "Has recibido"
      }
    }
  },
  "fr-FR": {
    "recent": {
      "title": "Argent",
      "empty": "Rien ne s'est encore passé. Ajoutez des dépenses ou invitez des amis pour lancer les choses."
    },
    "payer": {
      "placeholder": "Sélectionner le payeur"
    },
    "participants": {
      "tabs": {
        "sums": "Par sommes",
        "shares": "Par parts"
      },
      "add": {
        "label": "Ajouter des participants"
      }
    },
    "transfer": {
      "action": "Virement",
      "dialog": {
        "title": "Régler le solde",
        "cancel": "Annuler",
        "action": "Confirmer"
      },
      "me": "Moi",
      "direction": {
        "byme": (gender) => gender === "he" ? "J'ai payé" : (gender === "she" ? "J'ai payée" : "J'ai payé(e)"),
        "tome": (gender) => gender === "he" ? "J'ai reçu" : (gender === "she" ? "J'ai reçu" : "J'ai reçu")
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "Tu seras bien installé",
        "positive": "On te devra quelque chose",
        "negative": "Vous devrez"
      },
      "done": {
        "paid": (gender) => gender === "he" ? "Tu as payé" : gender === "she" ? "Tu as payé" : "Tu as payé",
        "received": (gender) => gender === "he" ? "Tu as reçu" : gender === "she" ? "Tu as reçu" : "Tu as reçu"
      }
    }
  },
  "hi-IN": {
    "recent": {
      "title": "पैसा",
      "empty": "अभी तक कुछ नहीं हुआ है। कुछ खर्च जोड़ें या शुरुआत करने के लिए दोस्तों को बुलाएं।"
    },
    "payer": {
      "placeholder": "भुगतानकर्ता चुनें"
    },
    "participants": {
      "tabs": {
        "sums": "राशि के अनुसार",
        "shares": "शेयरों के अनुसार"
      },
      "add": {
        "label": "प्रतिभागी जोड़ें"
      }
    },
    "transfer": {
      "action": "स्थानांतरण",
      "dialog": {
        "title": "बकाया चुकाएँ",
        "cancel": "रद्द करें",
        "action": "पुष्टि करें"
      },
      "me": "मैं",
      "direction": {
        "byme": (gender) => gender === "he" ? "मैंने भुगतान किया" : (gender === "she" ? "मैंने भुगतान की" : "मैंने भुगतान किया"),
        "tome": (gender) => gender === "he" ? "मैंने प्राप्त किया" : (gender === "she" ? "मैंने प्राप्त की" : "मैंने प्राप्त किया/की")
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "आप पूरी तरह से व्यवस्थित हो जाएंगे",
        "positive": "आपका बकाया रहेगा",
        "negative": "आपको देना होगा"
      },
      "done": {
        "paid": (gender) => gender === "he" ? "तुमने पैसे दे दिए" : gender === "she" ? "तुमने पैसे दे दी" : "तुमने पैसे दे दिए",
        "received": (gender) => gender === "he" ? "तुम्हें मिला है" : gender === "she" ? "तुम्हें मिली है" : "तुम्हें मिला/मिली है"
      }
    }
  },
  "it-IT": {
    "recent": {
      "title": "Denaro",
      "empty": "Non è ancora successo nulla. Aggiungi qualche spesa o invita amici per iniziare."
    },
    "payer": {
      "placeholder": "Seleziona il pagatore"
    },
    "participants": {
      "tabs": {
        "sums": "Per somme",
        "shares": "Per quote"
      },
      "add": {
        "label": "Aggiungi partecipanti"
      }
    },
    "transfer": {
      "action": "Trasferimento",
      "dialog": {
        "title": "Salda il conto",
        "cancel": "Annulla",
        "action": "Conferma"
      },
      "me": "Io",
      "direction": {
        "byme": (gender) => gender === "he" ? "Ho pagato" : (gender === "she" ? "Ho pagata" : "Ho pagato/a"),
        "tome": (gender) => gender === "he" ? "Ho ricevuto" : (gender === "she" ? "Ho ricevuto" : "Ho ricevuto")
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "Sarai completamente sistemato",
        "positive": "Ti sarà dovuto",
        "negative": "Avrai un debito"
      },
      "done": {
        "paid": (gender) => gender === "he" ? "Hai pagato" : gender === "she" ? "Hai pagato" : "Hai pagato",
        "received": (gender) => gender === "he" ? "Hai ricevuto" : gender === "she" ? "Hai ricevuta" : "Hai ricevuto/a"
      }
    }
  },
  "ja-JP": {
    "recent": {
      "title": "お金",
      "empty": "まだ何も起きていません。支出を追加したり、友達を招待して始めてみましょう。"
    },
    "payer": {
      "placeholder": "支払者を選択"
    },
    "participants": {
      "tabs": {
        "sums": "合計別",
        "shares": "持分ごとに"
      },
      "add": {
        "label": "参加者を追加"
      }
    },
    "transfer": {
      "action": "送金",
      "dialog": {
        "title": "精算する",
        "cancel": "キャンセル",
        "action": "確認"
      },
      "me": "私",
      "direction": {
        "byme": (gender) => "支払いました",
        "tome": (gender) => "受け取りました"
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "すっかり落ち着きますよ",
        "positive": "あなたは借りができることになります",
        "negative": "あなたに未払いがあります"
      },
      "done": {
        "paid": (gender) => "支払いが完了しました",
        "received": (gender) => "受け取ったよ"
      }
    }
  },
  "ko-KR": {
    "recent": {
      "title": "돈",
      "empty": "아직 아무 일도 일어나지 않았어요. 지출을 추가하거나 친구를 초대해 시작해보세요."
    },
    "payer": {
      "placeholder": "지불자 선택"
    },
    "participants": {
      "tabs": {
        "sums": "금액별",
        "shares": "지분별로"
      },
      "add": {
        "label": "참가자 추가"
      }
    },
    "transfer": {
      "action": "송금",
      "dialog": {
        "title": "정산하기",
        "cancel": "취소",
        "action": "확인"
      },
      "me": "나",
      "direction": {
        "byme": (gender) => "지불했습니다",
        "tome": (gender) => "받았습니다"
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "완전히 자리 잡을 거예요",
        "positive": "당신에게 빚이 생길 거예요",
        "negative": "지불해야 합니다"
      },
      "done": {
        "paid": (gender) => "결제하셨습니다",
        "received": (gender) => "받았어"
      }
    }
  },
  "nl-NL": {
    "recent": {
      "title": "Geld",
      "empty": "Er is nog niets gebeurd. Voeg wat uitgaven toe of nodig vrienden uit om op gang te komen."
    },
    "payer": {
      "placeholder": "Betaler selecteren"
    },
    "participants": {
      "tabs": {
        "sums": "Op bedragen",
        "shares": "Op basis van aandelen"
      },
      "add": {
        "label": "Deelnemers toevoegen"
      }
    },
    "transfer": {
      "action": "Overschrijving",
      "dialog": {
        "title": "Afrekenen",
        "cancel": "Annuleren",
        "action": "Bevestigen"
      },
      "me": "Ik",
      "direction": {
        "byme": (gender) => "Ik heb betaald",
        "tome": (gender) => "Ik heb ontvangen"
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "Je bent straks helemaal gesetteld",
        "positive": "Jij krijgt nog wat tegoed",
        "negative": "Je zult verschuldigd zijn"
      },
      "done": {
        "paid": (gender) => "Je hebt betaald",
        "received": (gender) => "Je hebt ontvangen"
      }
    }
  },
  "ru-RU": {
    "recent": {
      "title": "Деньги",
      "empty": "Пока ничего не произошло. Добавьте расходы или пригласите друзей, чтобы начать."
    },
    "payer": {
      "placeholder": "Выберите плательщика"
    },
    "participants": {
      "tabs": {
        "sums": "По суммам",
        "shares": "По долям"
      },
      "add": {
        "label": "Добавить участников"
      }
    },
    "transfer": {
      "action": "Перевод",
      "dialog": {
        "title": "Рассчитаться",
        "cancel": "Отмена",
        "action": "Подтвердить"
      },
      "me": "Я",
      "direction": {
        "byme": (gender) => gender === "he" ? "Я заплатил" : (gender === "she" ? "Я заплатила" : "Я заплатил(а)"),
        "tome": (gender) => gender === "he" ? "Я получил" : (gender === "she" ? "Я получила" : "Я получил(а)")
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "Ты полностью обустроишься",
        "positive": "Тебе будут должны",
        "negative": "Вы будете должны"
      },
      "done": {
        "paid": (gender) => gender === "he" ? "Ты заплатил" : gender === "she" ? "Ты заплатила" : "Ты заплатил(а)",
        "received": (gender) => gender === "he" ? "Ты получил" : gender === "she" ? "Ты получила" : "Ты получил(а)"
      }
    }
  },
  "sw-TZ": {
    "recent": {
      "title": "Pesa",
      "empty": "Bado hakuna kilichotokea. Ongeza matumizi au alika marafiki ili mambo yaanze."
    },
    "payer": {
      "placeholder": "Chagua mtoaji wa malipo"
    },
    "participants": {
      "tabs": {
        "sums": "Kwa jumla",
        "shares": "Kwa hisa"
      },
      "add": {
        "label": "Ongeza washiriki"
      }
    },
    "transfer": {
      "action": "Uhamisho",
      "dialog": {
        "title": "Lipa deni",
        "cancel": "Ghairi",
        "action": "Thibitisha"
      },
      "me": "Mimi",
      "direction": {
        "byme": (gender) => gender === "he" ? "Nimelipa" : (gender === "she" ? "Nimelipa" : "Nimelipa"),
        "tome": (gender) => gender === "he" ? "Nimepokea" : (gender === "she" ? "Nimepokea" : "Nimepokea")
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "Utakua umeshatulia kabisa",
        "positive": "Utakuwa na deni lako",
        "negative": "Utakuwa na deni"
      },
      "done": {
        "paid": (gender) => "Umelipa",
        "received": (gender) => "Umepewa"
      }
    }
  },
  "tr-TR": {
    "recent": {
      "title": "Para",
      "empty": "Henüz hiçbir şey olmadı. Biraz harcama ekleyin veya arkadaşlarınızı davet edin, böylece her şey başlasın."
    },
    "payer": {
      "placeholder": "Ödeyeni seç"
    },
    "participants": {
      "tabs": {
        "sums": "Toplamlara göre",
        "shares": "Hisselere göre"
      },
      "add": {
        "label": "Katılımcı ekle"
      }
    },
    "transfer": {
      "action": "Transfer",
      "dialog": {
        "title": "Hesap Kapat",
        "cancel": "İptal",
        "action": "Onayla"
      },
      "me": "Ben",
      "direction": {
        "byme": (gender) => "Ödedim",
        "tome": (gender) => "Aldım"
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "Tamamen yerleşmiş olacaksın",
        "positive": "Sana borçlanılacak",
        "negative": "Borçlu olacaksın"
      },
      "done": {
        "paid": (gender) => "Ödedin",
        "received": (gender) => "Aldın"
      }
    }
  },
  "uk-UA": {
    "recent": {
      "title": "Гроші",
      "empty": "Поки що нічого не сталося. Додайте витрати або запросіть друзів, щоб розпочати."
    },
    "payer": {
      "placeholder": "Виберіть платника"
    },
    "participants": {
      "tabs": {
        "sums": "За сумами",
        "shares": "За частками"
      },
      "add": {
        "label": "Додати учасників"
      }
    },
    "transfer": {
      "action": "Переказ",
      "dialog": {
        "title": "Розрахуватися",
        "cancel": "Скасувати",
        "action": "Підтвердити"
      },
      "me": "Я",
      "direction": {
        "byme": (gender) => gender === "he" ? "Я заплатив" : (gender === "she" ? "Я заплатила" : "Я заплатив(ла)"),
        "tome": (gender) => gender === "he" ? "Я отримав" : (gender === "she" ? "Я отримала" : "Я отримав(ла)")
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "Ти повністю облаштуєшся",
        "positive": "Тобі будуть винні",
        "negative": "Ви будете винні"
      },
      "done": {
        "paid": (gender) => gender === "he" ? "Ти заплатив" : gender === "she" ? "Ти заплатила" : "Ти заплатив(ла)",
        "received": (gender) => gender === "he" ? "Ти отримав" : gender === "she" ? "Ти отримала" : "Ти отримав(ла)"
      }
    }
  },
  "zh-CN": {
    "recent": {
      "title": "钱",
      "empty": "还没有任何活动。添加一些支出或邀请朋友一起开启新体验吧。"
    },
    "payer": {
      "placeholder": "选择付款方"
    },
    "participants": {
      "tabs": {
        "sums": "按金额",
        "shares": "按份额"
      },
      "add": {
        "label": "添加参与者"
      }
    },
    "transfer": {
      "action": "转账",
      "dialog": {
        "title": "结清账单",
        "cancel": "取消",
        "action": "确认"
      },
      "me": "我",
      "direction": {
        "byme": (gender) => "我付了钱",
        "tome": (gender) => "我收到了"
      }
    },
    "transfers": {
      "tobe": {
        "neutral": "你会完全安顿好的",
        "positive": "你会被欠下",
        "negative": "你将欠款"
      },
      "done": {
        "paid": (gender) => "你已付款",
        "received": (gender) => "你已收到"
      }
    }
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];
