// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("./types").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "members": {
      "title": "الأعضاء",
      "add": "إضافة أعضاء",
      "empty": "لا يوجد أحد هنا بعد. أضِف بعض الأعضاء لبدء المغامرة."
    },
    "editor": {
      "cover": "غلاف",
      "upload": "اختر بنفسك",
      "name": "اسم المغامرة",
      "note": "سيتمكن جميع الأعضاء من رؤية هذا الاسم",
      "info": "المغامرات مخصصة لأولئك الذين يرغبون في الإنفاق بالتساوي، سواء كانت رحلة معًا أو فاتورة بار أو حتى مصاريف منزلية مشتركة. الديون في المغامرة ليست بين الأفراد، بل بين جميع الأعضاء للحفاظ على حسابات متساوية للجميع.",
      "settings": "الإعدادات",
      "title": "مغامرة جديدة"
    },
    "finish": {
      "title": "أنه المغامرة",
      "description": "أرشفة المغامرة ستزيلها من شاشة النفقات الجديدة وتضعها في نهاية قائمة مغامراتك.",
      "button": "مغامرة الأرشيف",
      "delete": "حذف المغامرة"
    },
    "expenses": {
      "title": "النفقات",
      "total": "الإجمالي",
      "paidBy": "دفع بواسطة",
      "paid": "دفع"
    },
    "spending": {
      "yours": "إنفاقك",
      "total": "إجمالي الإنفاق"
    },
    "me": "أنا",
    "selector": {
      "regular": "الإنفاق المنتظم"
    }
  },
  "de-DE": {
    "members": {
      "title": "Mitglieder",
      "add": "Mitglieder hinzufügen",
      "empty": "Hier ist noch niemand. Füge Mitglieder hinzu, um das Abenteuer zu starten."
    },
    "editor": {
      "cover": "Titelbild",
      "upload": "Wähle selbst",
      "name": "Abenteuername",
      "note": "Alle Mitglieder sehen diesen Namen",
      "info": "Abenteuer sind für diejenigen, die die Ausgaben gleichmäßig teilen möchten – egal ob gemeinsame Reise, Bar-Rechnung oder einfach Haushaltskosten. Die Schulden innerhalb eines Abenteuers bestehen nicht zwischen einzelnen Nutzern, sondern gegenüber allen Mitgliedern, sodass alle Ausgaben fair abgerechnet werden.",
      "settings": "Einstellungen",
      "title": "Neues Abenteuer"
    },
    "finish": {
      "title": "Beende das Abenteuer",
      "description": "Durch das Archivieren des Abenteuers wird es aus dem Bildschirm für neue Ausgaben entfernt und ans Ende deiner Abenteuerliste verschoben.",
      "button": "Abenteuer im Archiv",
      "delete": "Abenteuer löschen"
    },
    "expenses": {
      "title": "Ausgaben",
      "total": "Gesamt",
      "paidBy": "Bezahlt von",
      "paid": "Bezahlt"
    },
    "spending": {
      "yours": "Ihre Ausgaben",
      "total": "Gesamtausgaben"
    },
    "me": "Ich",
    "selector": {
      "regular": "Regelmäßige Ausgaben"
    }
  },
  "en-US": {
    "members": {
      "title": "Members",
      "add": "Add members",
      "empty": "Nobody here yet. Add some members to start the adventure."
    },
    "editor": {
      "cover": "Cover",
      "upload": "Choose your own",
      "name": "Adventure name",
      "note": "All members will see this name",
      "info": "Adventures are for those who want to split expenses equally, whether it's a trip together, a bar tab, or just shared household costs. Debts in an adventure aren't between individual users but among all members, keeping everyone’s share balanced.",
      "settings": "Settings",
      "title": "New Adventure"
    },
    "finish": {
      "title": "Finish the adventure",
      "description": "Archiving the adventure will remove it from the new expense screen and move it to the back of your adventure list.",
      "button": "Archive Adventure",
      "delete": "Delete adventure"
    },
    "expenses": {
      "title": "Expenses",
      "total": "Total",
      "paidBy": "Paid by",
      "paid": "Paid"
    },
    "spending": {
      "yours": "Your spending",
      "total": "Total spent"
    },
    "me": "Me",
    "selector": {
      "regular": "Regular spending"
    }
  },
  "es-ES": {
    "members": {
      "title": "Miembros",
      "add": "Agregar miembros",
      "empty": "Todavía no hay nadie aquí. Añade algunos miembros para comenzar la aventura."
    },
    "editor": {
      "cover": "Portada",
      "upload": "Elige el tuyo",
      "name": "Nombre de la aventura",
      "note": "Todos los miembros verán este nombre",
      "info": "Las aventuras son para quienes desean compartir los gastos por igual, ya sea un viaje juntos, una cuenta de bar o simplemente los gastos comunes del hogar. Las deudas en una aventura no son entre usuarios individuales, sino entre todos los miembros, para mantener cuentas equitativas.",
      "settings": "Configuración",
      "title": "Nueva aventura"
    },
    "finish": {
      "title": "Termina la aventura",
      "description": "Archivar la aventura la eliminará de la pantalla de nuevos gastos y la pondrá al final de tu lista de aventuras.",
      "button": "Aventura en el archivo",
      "delete": "Eliminar aventura"
    },
    "expenses": {
      "title": "Gastos",
      "total": "Total",
      "paidBy": "Pagado por",
      "paid": "Pagado"
    },
    "spending": {
      "yours": "Tus gastos",
      "total": "Total gastado"
    },
    "me": "Yo",
    "selector": {
      "regular": "Gastos habituales"
    }
  },
  "fr-FR": {
    "members": {
      "title": "Membres",
      "add": "Ajouter des membres",
      "empty": "Personne n'est encore là. Ajoutez des membres pour commencer l'aventure."
    },
    "editor": {
      "cover": "Couverture",
      "upload": "Choisissez le vôtre",
      "name": "Nom de l’aventure",
      "note": "Tous les membres verront ce nom",
      "info": "Les aventures sont faites pour ceux qui veulent partager les dépenses de manière égale, que ce soit un voyage ensemble, une addition de bar ou simplement des frais ménagers communs. Les dettes lors d’une aventure ne sont pas entre individus, mais entre tous les membres pour garder un équilibre équitable.",
      "settings": "Paramètres",
      "title": "Nouvelle aventure"
    },
    "finish": {
      "title": "Terminer l’aventure",
      "description": "L’archivage de l’aventure la retirera de l’écran des nouvelles dépenses et la placera à la fin de votre liste d’aventures.",
      "button": "Aventure d’archive",
      "delete": "Supprimer l’aventure"
    },
    "expenses": {
      "title": "Dépenses",
      "total": "Total",
      "paidBy": "Payé par",
      "paid": "Payé"
    },
    "spending": {
      "yours": "Vos dépenses",
      "total": "Total dépensé"
    },
    "me": "Moi",
    "selector": {
      "regular": "Dépenses régulières"
    }
  },
  "hi-IN": {
    "members": {
      "title": "सदस्य",
      "add": "सदस्य जोड़ें",
      "empty": "अभी यहाँ कोई नहीं है। साहसिक यात्रा शुरू करने के लिए कुछ सदस्य जोड़ें।"
    },
    "editor": {
      "cover": "कवर",
      "upload": "अपना स्वयं चुनें",
      "name": "साहसिक कार्य का नाम",
      "note": "सभी सदस्य यह नाम देख पाएंगे",
      "info": "रोमांच उन लोगों के लिए है जो खर्च बराबर करना चाहते हैं, चाहे वह साथ में यात्रा हो, बार का बिल हो या सिर्फ सामान्य घरेलू खर्च। रोमांच में क़र्ज़े व्यक्तिगत यूज़र्स के बीच नहीं, बल्कि सभी सदस्यों के बीच होते हैं ताकि सभी का हिसाब बराबर रहे।",
      "settings": "सेटिंग्स",
      "title": "नई रोमांचक यात्रा"
    },
    "finish": {
      "title": "साहसिक कार्य समाप्त करें",
      "description": "साहसिक यात्रा को आर्काइव करने से यह नए खर्च स्क्रीन से हट जाएगी और आपकी साहसिक यात्राओं की सूची के अंत में आ जाएगी।",
      "button": "आर्काइव एडवेंचर",
      "delete": "एडवेंचर हटाएँ"
    },
    "expenses": {
      "title": "खर्चे",
      "total": "कुल",
      "paidBy": "द्वारा भुगतान किया गया",
      "paid": "भुगतान किया गया"
    },
    "spending": {
      "yours": "आपके खर्च",
      "total": "कुल खर्च"
    },
    "me": "मैं",
    "selector": {
      "regular": "नियमित खर्च"
    }
  },
  "it-IT": {
    "members": {
      "title": "Membri",
      "add": "Aggiungi membri",
      "empty": "Non c'è ancora nessuno qui. Aggiungi dei membri per iniziare l'avventura."
    },
    "editor": {
      "cover": "Copertina",
      "upload": "Scegli il tuo",
      "name": "Nome dell’avventura",
      "note": "Tutti i membri vedranno questo nome",
      "info": "Le avventure sono per chi vuole dividere le spese in modo equo, che si tratti di un viaggio insieme, di un conto al bar o delle semplici spese domestiche comuni. I debiti in un’avventura non sono tra utenti singoli, ma tra tutti i partecipanti, così da mantenere i conti in pari per tutti.",
      "settings": "Impostazioni",
      "title": "Nuova avventura"
    },
    "finish": {
      "title": "Termina l’avventura",
      "description": "L'archiviazione dell'avventura la rimuoverà dalla schermata delle nuove spese e la sposterà in fondo alla tua lista di avventure.",
      "button": "Avventura nell’archivio",
      "delete": "Elimina avventura"
    },
    "expenses": {
      "title": "Spese",
      "total": "Totale",
      "paidBy": "Pagato da",
      "paid": "Pagato"
    },
    "spending": {
      "yours": "Le tue spese",
      "total": "Totale speso"
    },
    "me": "Io",
    "selector": {
      "regular": "Spese regolari"
    }
  },
  "ja-JP": {
    "members": {
      "title": "メンバー",
      "add": "メンバーを追加",
      "empty": "まだ誰もいません。冒険を始めるためにメンバーを追加しましょう。"
    },
    "editor": {
      "cover": "カバー",
      "upload": "自分で選ぶ",
      "name": "冒険の名前",
      "note": "すべてのメンバーがこの名前を表示します",
      "info": "冒険は、旅行や飲み代、または日々の共同出費など、すべてを平等に分担したい人たちのためのものです。冒険での債務は個々のユーザー間で発生するものではなく、全メンバー間で均等に精算されます。",
      "settings": "設定",
      "title": "新しい冒険"
    },
    "finish": {
      "title": "冒険を終える",
      "description": "冒険をアーカイブすると、新しい支出画面から削除され、あなたの冒険リストの最後に移動します。",
      "button": "アーカイブアドベンチャー",
      "delete": "冒険を削除"
    },
    "expenses": {
      "title": "経費",
      "total": "合計",
      "paidBy": "支払者",
      "paid": "支払い済み"
    },
    "spending": {
      "yours": "あなたの支出",
      "total": "合計支出"
    },
    "me": "私",
    "selector": {
      "regular": "定期的な支出"
    }
  },
  "ko-KR": {
    "members": {
      "title": "구성원",
      "add": "구성원 추가",
      "empty": "아직 아무도 없습니다. 모험을 시작하려면 멤버를 추가하세요."
    },
    "editor": {
      "cover": "커버",
      "upload": "직접 선택하세요",
      "name": "모험 이름",
      "note": "모든 멤버가 이 이름을 볼 수 있습니다",
      "info": "모험은 여행, 술집 계산, 또는 단순한 공동 가계비와 같이 비용을 공평하게 나누고 싶은 사람들을 위한 것입니다. 모험의 빚은 개인 사용자 간이 아니라 모든 회원들끼리 서로 공평하게 정산되도록 되어 있습니다.",
      "settings": "설정",
      "title": "새로운 모험"
    },
    "finish": {
      "title": "모험을 끝내기",
      "description": "모험을 보관하면 새 지출 화면에서 제거되고 내 모험 목록의 맨 뒤로 이동합니다.",
      "button": "아카이브 어드벤처",
      "delete": "모험 삭제"
    },
    "expenses": {
      "title": "지출",
      "total": "합계",
      "paidBy": "결제자",
      "paid": "결제 완료"
    },
    "spending": {
      "yours": "내 지출",
      "total": "총 지출"
    },
    "me": "나",
    "selector": {
      "regular": "정기 지출"
    }
  },
  "nl-NL": {
    "members": {
      "title": "Leden",
      "add": "Leden toevoegen",
      "empty": "Hier is nog niemand. Voeg leden toe om het avontuur te beginnen."
    },
    "editor": {
      "cover": "Omslag",
      "upload": "Kies zelf",
      "name": "Naam van het avontuur",
      "note": "Alle leden zien deze naam",
      "info": "Avonturen zijn er voor mensen die de kosten gelijk willen delen, of het nu om samen reizen, een gezamenlijke barrekening of gewoon huishoudelijke uitgaven gaat. De schulden binnen een avontuur zijn niet tussen losse gebruikers, maar onder alle leden om het eerlijk bij te houden.",
      "settings": "Instellingen",
      "title": "Nieuw avontuur"
    },
    "finish": {
      "title": "Maak het avontuur af",
      "description": "Als je het avontuur archiveert, wordt het verwijderd van het nieuwe uitgavenscherm en naar het einde van je avonturenlijst verplaatst.",
      "button": "Archiefavontuur",
      "delete": "Avontuur verwijderen"
    },
    "expenses": {
      "title": "Uitgaven",
      "total": "Totaal",
      "paidBy": "Betaald door",
      "paid": "Betaald"
    },
    "spending": {
      "yours": "Jouw uitgaven",
      "total": "Totaal uitgegeven"
    },
    "me": "Ik",
    "selector": {
      "regular": "Regelmatige uitgaven"
    }
  },
  "ru-RU": {
    "members": {
      "title": "Участники",
      "add": "Добавить участников",
      "empty": "Здесь пока никого нет. Добавьте участников, чтобы начать приключение."
    },
    "editor": {
      "cover": "Обложка",
      "upload": "Выберите свой вариант",
      "name": "Название приключения",
      "note": "Все участники увидят это имя",
      "info": "Приключения созданы для тех, кто хочет делить расходы поровну — будь то совместное путешествие, счёт в баре или просто общие домашние траты. Долги в приключениях распределяются не между отдельными пользователями, а между всеми участниками, чтобы поддерживать равный баланс.",
      "settings": "Настройки",
      "title": "Новое приключение"
    },
    "finish": {
      "title": "Завершить приключение",
      "description": "Архивирование приключения удалит его из экрана новых расходов и переместит в конец списка ваших приключений.",
      "button": "Архивное приключение",
      "delete": "Удалить приключение"
    },
    "expenses": {
      "title": "Расходы",
      "total": "Итого",
      "paidBy": "Оплачено",
      "paid": "Оплачено"
    },
    "spending": {
      "yours": "Ваши расходы",
      "total": "Всего потрачено"
    },
    "me": "Я",
    "selector": {
      "regular": "Регулярные расходы"
    }
  },
  "sw-TZ": {
    "members": {
      "title": "Wanachama",
      "add": "Ongeza wanachama",
      "empty": "Hakuna mtu hapa bado. Ongeza wanachama kuanza safari ya kichumbakazi."
    },
    "editor": {
      "cover": "Jalada",
      "upload": "Chagua yako mwenyewe",
      "name": "Jina la tukio",
      "note": "Wanachama wote wataona jina hili",
      "info": "Matukio ni kwa wale wanaotaka kugawana gharama sawa, iwe ni safari pamoja, bili ya baa, au matumizi ya kawaida ya nyumbani. Madeni kwenye tukio hayawekwi kati ya watumiaji mmoja mmoja, bali kati ya wanachama wote wanaosaidia kuweka usawa kwenye matumizi.",
      "settings": "Mipangilio",
      "title": "Ndoto Mpya"
    },
    "finish": {
      "title": "Maliza safari hii",
      "description": "Ukiihifadhi tukio, litaondolewa kwenye skrini ya matumizi mapya na kuwekwa mwisho wa orodha ya matukio yako.",
      "button": "Maandishi ya Matukio",
      "delete": "Futa tukio"
    },
    "expenses": {
      "title": "Matumizi",
      "total": "Jumla",
      "paidBy": "Imelipiwa na",
      "paid": "Imelipwa"
    },
    "spending": {
      "yours": "Matumizi yako",
      "total": "Jumla iliyotumika"
    },
    "me": "Mimi",
    "selector": {
      "regular": "Matumizi ya kawaida"
    }
  },
  "tr-TR": {
    "members": {
      "title": "Üyeler",
      "add": "Üye ekle",
      "empty": "Henüz burada kimse yok. Maceraya başlamak için birkaç üye ekle."
    },
    "editor": {
      "cover": "Kapak",
      "upload": "Kendi seçimini yap",
      "name": "Macera adı",
      "note": "Tüm üyeler bu ismi görecek",
      "info": "Macera, masrafları eşit şekilde paylaşmak isteyenler içindir; ister birlikte bir seyahat, ister bar hesabı ya da sadece ortak ev harcamaları olsun. Maceradaki borçlar bireysel kullanıcılar arasında değil, tüm üyeler arasında eşit şekilde tutulur.",
      "settings": "Ayarlar",
      "title": "Yeni Macera"
    },
    "finish": {
      "title": "Macerayı bitir",
      "description": "Macera arşivlendiğinde, yeni harcama ekranından kaldırılır ve macera listenizin en sonuna taşınır.",
      "button": "Arşiv macerası",
      "delete": "Macera sil"
    },
    "expenses": {
      "title": "Giderler",
      "total": "Toplam",
      "paidBy": "Ödeyen",
      "paid": "Ödendi"
    },
    "spending": {
      "yours": "Harcamalarınız",
      "total": "Toplam harcama"
    },
    "me": "Ben",
    "selector": {
      "regular": "Düzenli harcamalar"
    }
  },
  "uk-UA": {
    "members": {
      "title": "Учасники",
      "add": "Додати учасників",
      "empty": "Тут поки нікого немає. Додайте учасників, щоб розпочати пригоду."
    },
    "editor": {
      "cover": "Обкладинка",
      "upload": "Виберіть свій варіант",
      "name": "Назва пригоди",
      "note": "Усі учасники побачать це ім'я",
      "info": "Пригоди створені для тих, хто хоче ділити витрати порівну — чи це спільна подорож, рахунок у барі чи просто загальні домашні витрати. Борги в пригоді виникають не між окремими користувачами, а між усіма учасниками, щоб кожен мав рівні частки.",
      "settings": "Налаштування",
      "title": "Нова пригода"
    },
    "finish": {
      "title": "Завершити пригоду",
      "description": "Архівування пригоди видалить її з екрана нових витрат і перемістить у кінець вашого списку пригод.",
      "button": "Архівна пригода",
      "delete": "Видалити пригоду"
    },
    "expenses": {
      "title": "Витрати",
      "total": "Всього",
      "paidBy": "Сплачено",
      "paid": "Оплачено"
    },
    "spending": {
      "yours": "Ваші витрати",
      "total": "Всього витрачено"
    },
    "me": "Я",
    "selector": {
      "regular": "Регулярні витрати"
    }
  },
  "zh-CN": {
    "members": {
      "title": "成员",
      "add": "添加成员",
      "empty": "这里还没有人。添加一些成员，开启冒险之旅吧。"
    },
    "editor": {
      "cover": "封面",
      "upload": "自行选择",
      "name": "冒险名称",
      "note": "所有成员都能看到此名字",
      "info": "冒险适合那些希望平等分担花费的人，无论是一起旅行、共同买单还是家庭开支。冒险中的债务不是个人之间的，而是所有成员共同分担，确保每个人的账目都公平。",
      "settings": "设置",
      "title": "新冒险"
    },
    "finish": {
      "title": "完成冒险",
      "description": "归档该冒险后，它将从新的支出界面中移除，并被放到你的冒险列表最后。",
      "button": "档案冒险",
      "delete": "删除冒险"
    },
    "expenses": {
      "title": "支出",
      "total": "总计",
      "paidBy": "由...支付",
      "paid": "已支付"
    },
    "spending": {
      "yours": "你的支出",
      "total": "总支出"
    },
    "me": "我",
    "selector": {
      "regular": "定期支出"
    }
  }
};
/** @type {import("./types").Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];

