// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("$lib/intl").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "editor": {
      "cover": "غلاف",
      "upload": "اختر بنفسك",
      "name": "اسم المغامرة",
      "note": "سيتمكن جميع الأعضاء من رؤية هذا الاسم",
      "info": "المغامرات مخصصة لأولئك الذين يرغبون في الإنفاق بالتساوي، سواء كانت رحلة معًا أو فاتورة بار أو حتى مصاريف منزلية مشتركة. الديون في المغامرة ليست بين الأفراد، بل بين جميع الأعضاء للحفاظ على حسابات متساوية للجميع.",
      "settings": "الإعدادات",
      "title": "مغامرة جديدة"
    },
    "finish": {
      "archive": {
        "title": "أنهِ المغامرة",
        "description": "أرشفة المغامرة ستزيلها من شاشة المصاريف الجديدة وتنقلها إلى نهاية قائمة مغامراتك.",
        "button": "أرشفة المغامرة"
      },
      "delete": {
        "button": (title) => `حذف ${title}`,
        "hold": "اضغط مع الاستمرار للحذف",
        "label": "حذف"
      }
    },
    "expenses": {
      "title": "النفقات",
      "total": "الإجمالي",
      "paidBy": "دفع بواسطة",
      "paid": "دفع",
      "empty": "لم يحدث أي شيء بعد. ادعُ بعض الأصدقاء وأضف بعض النفقات لبدء الأمور.",
      "delete": {
        "hold": "اضغط مع الاستمرار للحذف"
      }
    },
    "spending": {
      "yours": "إنفاقك",
      "total": "إجمالي الإنفاق"
    },
    "me": "أنا",
    "selector": {
      "regular": "تقسيم"
    },
    "archive": {
      "header": "الأرشيف",
      "warning": "أرشفة المغامرة إجراء دائم ولا يمكن التراجع عنه.",
      "merge": {
        "label": "تحويل الأرصدة",
        "description": "عند أرشفة هذه المغامرة، سيتم تحويل الأرصدة المستحقة إلى ديون عادية بين الأعضاء."
      }
    },
    "balance": {
      "header": "عند أرشفة هذه المغامرة:",
      "merge": "انقل الديون إلى ديون الأعضاء العاديين",
      "keep": "اترك الديون/الأرصدة في المغامرة"
    },
    "archived": "مؤرشف",
    "hint": {
      "action": "ابدأ مغامرتك الأولى",
      "dismiss": "تجاهل",
      "dismissed": "يمكنك إنشاء مغامرة جديدة في أي وقت من خلال قائمة + في أسفل الشاشة."
    },
    "title": "المغامرات",
    "panel": {
      "total": "الإجمالي"
    },
    "participants": {
      "title": "الأعضاء",
      "add": "إضافة أعضاء",
      "empty": "لا يوجد أحد هنا بعد. أضِف بعض الأعضاء لبدء المغامرة."
    }
  },
  "de-DE": {
    "editor": {
      "cover": "Titelbild",
      "upload": "Wähle selbst",
      "name": "Abenteuername",
      "note": "Alle Mitglieder sehen diesen Namen",
      "info": "Abenteuer sind für diejenigen, die die Ausgaben gleichmäßig teilen möchten – egal ob gemeinsame Reise, Bar-Rechnung oder einfach Haushaltskosten. Die Schulden innerhalb eines Abenteuers bestehen nicht zwischen einzelnen Nutzern, sondern gegenüber allen Mitgliedern, sodass alle Ausgaben fair abgerechnet werden.",
      "settings": "Einstellungen",
      "title": "Neues Abenteuer"
    },
    "finish": {
      "archive": {
        "title": "Abenteuer abschließen",
        "description": "Wenn du das Abenteuer archivierst, wird es vom Bildschirm für neue Ausgaben entfernt und ans Ende deiner Abenteuerliste verschoben.",
        "button": "Abenteuer archivieren"
      },
      "delete": {
        "button": (title) => `"${title}" löschen`,
        "hold": "Zum Löschen halten",
        "label": "Löschen"
      }
    },
    "expenses": {
      "title": "Ausgaben",
      "total": "Gesamt",
      "paidBy": "Bezahlt von",
      "paid": "Bezahlt",
      "empty": "Es ist noch nichts passiert. Lade ein paar Freunde ein und füge Ausgaben hinzu, damit es losgehen kann.",
      "delete": {
        "hold": "Zum Löschen gedrückt halten"
      }
    },
    "spending": {
      "yours": "Ihre Ausgaben",
      "total": "Gesamtausgaben"
    },
    "me": "Ich",
    "selector": {
      "regular": "Aufteilen"
    },
    "archive": {
      "header": "Archiv",
      "warning": "Das Archivieren des Abenteuers ist dauerhaft und kann nicht rückgängig gemacht werden.",
      "merge": {
        "label": "Guthaben übertragen",
        "description": "Wenn dieses Abenteuer archiviert wird, werden ausstehende Beträge in reguläre Schulden zwischen den Mitgliedern umgewandelt."
      }
    },
    "balance": {
      "header": "Beim Archivieren dieses Abenteuers:",
      "merge": "Schulden zu den regulären Mitgliedsschulden übertragen",
      "keep": "Schulden/Restbeträge im Abenteuer belassen"
    },
    "archived": "Archiviert",
    "hint": {
      "action": "Starte dein erstes Abenteuer",
      "dismiss": "Schließen",
      "dismissed": "Du kannst jederzeit ein neues Abenteuer über das +-Menü unten auf dem Bildschirm erstellen."
    },
    "title": "Abenteuer",
    "panel": {
      "total": "Gesamtsumme"
    },
    "participants": {
      "title": "Mitglieder",
      "add": "Mitglieder hinzufügen",
      "empty": "Hier ist noch niemand. Füge Mitglieder hinzu, um das Abenteuer zu starten."
    }
  },
  "en-US": {
    "editor": {
      "cover": "Cover",
      "upload": "Choose your own",
      "name": "Adventure name",
      "note": "All members will see this name",
      "info": "Adventures are for those who want to split expenses equally, whether it's a trip together, a bar tab, or just shared household costs. Debts in an adventure aren't between individual users but among all members, keeping everyone’s share balanced.",
      "settings": "Settings",
      "title": "New Adventure"
    },
    "finish": {
      "archive": {
        "title": "Finish the adventure",
        "description": "Archiving the adventure will remove it from the new expense screen and move it to the back of your adventure list.",
        "button": "Archive adventure"
      },
      "delete": {
        "button": (title) => `Delete ${title}`,
        "hold": "Hold to delete",
        "label": "Delete"
      }
    },
    "expenses": {
      "title": "Expenses",
      "total": "Total",
      "paidBy": "Paid by",
      "paid": "Paid",
      "empty": "Nothing happened yet. Invite some friends and add some spendings to get things started.",
      "delete": {
        "hold": "Hold to delete"
      }
    },
    "spending": {
      "yours": "Your spending",
      "total": "Total spent"
    },
    "me": "Me",
    "selector": {
      "regular": "Split"
    },
    "archive": {
      "header": "Archive",
      "warning": "Archiving the adventure is permanent and cannot be undone.",
      "merge": {
        "label": "Transfer balances",
        "description": "When this adventure is archived, outstanding balances will be converted into regular debts between members."
      }
    },
    "balance": {
      "header": "When archiving this adventure:",
      "merge": "Move debts to the regular member debts",
      "keep": "Leave debts/balances in adventure"
    },
    "archived": "Archived",
    "hint": {
      "action": "Start your first adventure",
      "dismiss": "Dismiss",
      "dismissed": "You can create a new adventure anytime through the + menu at the bottom of the screen."
    },
    "title": "Adventures",
    "panel": {
      "total": "Total"
    },
    "participants": {
      "title": "Members",
      "add": "Add members",
      "empty": "Nobody here yet. Add some members to start the adventure."
    }
  },
  "es-ES": {
    "editor": {
      "cover": "Portada",
      "upload": "Elige el tuyo",
      "name": "Nombre de la aventura",
      "note": "Todos los miembros verán este nombre",
      "info": "Las aventuras son para quienes desean compartir los gastos por igual, ya sea un viaje juntos, una cuenta de bar o simplemente los gastos comunes del hogar. Las deudas en una aventura no son entre usuarios individuales, sino entre todos los miembros, para mantener cuentas equitativas.",
      "settings": "Configuración",
      "title": "Nueva aventura"
    },
    "finish": {
      "archive": {
        "title": "Finalizar la aventura",
        "description": "Archivar la aventura la eliminará de la pantalla de nuevos gastos y la moverá al final de tu lista de aventuras.",
        "button": "Archivar aventura"
      },
      "delete": {
        "button": (title) => `Eliminar ${title}`,
        "hold": "Mantén pulsado para borrar",
        "label": "Eliminar"
      }
    },
    "expenses": {
      "title": "Gastos",
      "total": "Total",
      "paidBy": "Pagado por",
      "paid": "Pagado",
      "empty": "Aún no ha pasado nada. Invita a algunos amigos y añade algunos gastos para poner todo en marcha.",
      "delete": {
        "hold": "Mantén pulsado para borrar"
      }
    },
    "spending": {
      "yours": "Tus gastos",
      "total": "Total gastado"
    },
    "me": "Yo",
    "selector": {
      "regular": "Dividir"
    },
    "archive": {
      "header": "Archivo",
      "warning": "Archivar la aventura es una acción permanente y no se puede deshacer.",
      "merge": {
        "label": "Transferir saldos",
        "description": "Cuando se archive esta aventura, los saldos pendientes se convertirán en deudas habituales entre los miembros."
      }
    },
    "balance": {
      "header": "Al archivar esta aventura:",
      "merge": "Mover deudas a las deudas de miembros regulares",
      "keep": "Dejar las deudas/saldos en la aventura"
    },
    "archived": "Archivado",
    "hint": {
      "action": "Comienza tu primera aventura",
      "dismiss": "Descartar",
      "dismissed": "Puedes crear una nueva aventura en cualquier momento desde el menú + en la parte inferior de la pantalla."
    },
    "title": "Aventuras",
    "panel": {
      "total": "Total"
    },
    "participants": {
      "title": "Miembros",
      "add": "Agregar miembros",
      "empty": "Todavía no hay nadie aquí. Añade algunos miembros para comenzar la aventura."
    }
  },
  "fr-FR": {
    "editor": {
      "cover": "Couverture",
      "upload": "Choisissez le vôtre",
      "name": "Nom de l’aventure",
      "note": "Tous les membres verront ce nom",
      "info": "Les aventures sont faites pour ceux qui veulent partager les dépenses de manière égale, que ce soit un voyage ensemble, une addition de bar ou simplement des frais ménagers communs. Les dettes lors d’une aventure ne sont pas entre individus, mais entre tous les membres pour garder un équilibre équitable.",
      "settings": "Paramètres",
      "title": "Nouvelle aventure"
    },
    "finish": {
      "archive": {
        "title": "Terminer l’aventure",
        "description": "Archiver l’aventure la retirera de l’écran des nouvelles dépenses et la placera à la fin de ta liste d’aventures.",
        "button": "Archiver l’aventure"
      },
      "delete": {
        "button": (title) => `Supprimer ${title}`,
        "hold": "Maintenir pour supprimer",
        "label": "Supprimer"
      }
    },
    "expenses": {
      "title": "Dépenses",
      "total": "Total",
      "paidBy": "Payé par",
      "paid": "Payé",
      "empty": "Rien ne s'est encore passé. Invite des amis et ajoute des dépenses pour lancer les choses.",
      "delete": {
        "hold": "Maintiens pour supprimer"
      }
    },
    "spending": {
      "yours": "Vos dépenses",
      "total": "Total dépensé"
    },
    "me": "Moi",
    "selector": {
      "regular": "Partager"
    },
    "archive": {
      "header": "Archive",
      "warning": "L’archivage de l’aventure est définitif et ne peut pas être annulé.",
      "merge": {
        "label": "Transférer les soldes",
        "description": "Lorsque cette aventure sera archivée, les soldes en attente seront convertis en dettes classiques entre les membres."
      }
    },
    "balance": {
      "header": "Lors de l’archivage de cette aventure :",
      "merge": "Transférer les dettes vers les dettes des membres réguliers",
      "keep": "Laisser les dettes/soldes dans l’aventure"
    },
    "archived": "Archivé",
    "hint": {
      "action": "Commence ta première aventure",
      "dismiss": "Ignorer",
      "dismissed": "Vous pouvez créer une nouvelle aventure à tout moment via le menu + en bas de l'écran."
    },
    "title": "Aventures",
    "panel": {
      "total": "Total"
    },
    "participants": {
      "title": "Membres",
      "add": "Ajouter des membres",
      "empty": "Personne n'est encore là. Ajoutez des membres pour commencer l'aventure."
    }
  },
  "hi-IN": {
    "editor": {
      "cover": "कवर",
      "upload": "अपना स्वयं चुनें",
      "name": "साहसिक कार्य का नाम",
      "note": "सभी सदस्य यह नाम देख पाएंगे",
      "info": "रोमांच उन लोगों के लिए है जो खर्च बराबर करना चाहते हैं, चाहे वह साथ में यात्रा हो, बार का बिल हो या सिर्फ सामान्य घरेलू खर्च। रोमांच में क़र्ज़े व्यक्तिगत यूज़र्स के बीच नहीं, बल्कि सभी सदस्यों के बीच होते हैं ताकि सभी का हिसाब बराबर रहे।",
      "settings": "सेटिंग्स",
      "title": "नई रोमांचक यात्रा"
    },
    "finish": {
      "archive": {
        "title": "साहसिक कार्य समाप्त करें",
        "description": "एडवेंचर को आर्काइव करने से यह नए खर्च स्क्रीन से हट जाएगा और आपकी एडवेंचर सूची के अंत में चला जाएगा।",
        "button": "एडवेंचर को संग्रहित करें"
      },
      "delete": {
        "button": (title) => `${title} हटाएँ`,
        "hold": "हटाने के लिए दबाए रखें",
        "label": "हटाएँ"
      }
    },
    "expenses": {
      "title": "खर्चे",
      "total": "कुल",
      "paidBy": "द्वारा भुगतान किया गया",
      "paid": "भुगतान किया गया",
      "empty": "अभी तक कुछ नहीं हुआ है। कुछ दोस्तों को बुलाएं और खर्च जोड़ें ताकि चीज़ें शुरू हो सकें।",
      "delete": {
        "hold": "हटाने के लिए दबाए रखें"
      }
    },
    "spending": {
      "yours": "आपके खर्च",
      "total": "कुल खर्च"
    },
    "me": "मैं",
    "selector": {
      "regular": "विभाजित करें"
    },
    "archive": {
      "header": "आर्काइव",
      "warning": "एडवेंचर को आर्काइव करना स्थायी है और इसे वापस नहीं लिया जा सकता।",
      "merge": {
        "label": "बैलेंस ट्रांसफर करें",
        "description": "जब इस एडवेंचर को आर्काइव किया जाएगा, तो लंबित बकाया राशियाँ सदस्यों के बीच सामान्य ऋण में बदल जाएंगी।"
      }
    },
    "balance": {
      "header": "इस साहसिक कार्य को संग्रहित करते समय:",
      "merge": "ऋणों को नियमित सदस्य के ऋणों में स्थानांतरित करें",
      "keep": "एडवेंचर में ऋण/बैलेंस छोड़ें"
    },
    "archived": "संग्रहीत",
    "hint": {
      "action": "अपना पहला रोमांच शुरू करें",
      "dismiss": "खारिज करें",
      "dismissed": "आप स्क्रीन के नीचे दिए गए + मेनू से कभी भी नया साहसिक शुरू कर सकते हैं।"
    },
    "title": "रोमांच",
    "panel": {
      "total": "कुल राशि"
    },
    "participants": {
      "title": "सदस्य",
      "add": "सदस्य जोड़ें",
      "empty": "अभी यहाँ कोई नहीं है। साहसिक यात्रा शुरू करने के लिए कुछ सदस्य जोड़ें।"
    }
  },
  "it-IT": {
    "editor": {
      "cover": "Copertina",
      "upload": "Scegli il tuo",
      "name": "Nome dell’avventura",
      "note": "Tutti i membri vedranno questo nome",
      "info": "Le avventure sono per chi vuole dividere le spese in modo equo, che si tratti di un viaggio insieme, di un conto al bar o delle semplici spese domestiche comuni. I debiti in un’avventura non sono tra utenti singoli, ma tra tutti i partecipanti, così da mantenere i conti in pari per tutti.",
      "settings": "Impostazioni",
      "title": "Nuova avventura"
    },
    "finish": {
      "archive": {
        "title": "Concludi l’avventura",
        "description": "Archiviare l’avventura la rimuoverà dalla schermata delle nuove spese e la sposterà in fondo alla tua lista di avventure.",
        "button": "Archivia avventura"
      },
      "delete": {
        "button": (title) => `Elimina ${title}`,
        "hold": "Tieni premuto per eliminare",
        "label": "Elimina"
      }
    },
    "expenses": {
      "title": "Spese",
      "total": "Totale",
      "paidBy": "Pagato da",
      "paid": "Pagato",
      "empty": "Non è ancora successo nulla. Invita degli amici e aggiungi delle spese per far partire tutto.",
      "delete": {
        "hold": "Tieni premuto per eliminare"
      }
    },
    "spending": {
      "yours": "Le tue spese",
      "total": "Totale speso"
    },
    "me": "Io",
    "selector": {
      "regular": "Dividi"
    },
    "archive": {
      "header": "Archivio",
      "warning": "L’archiviazione dell’avventura è permanente e non può essere annullata.",
      "merge": {
        "label": "Trasferisci saldi",
        "description": "Quando questa avventura verrà archiviata, i saldi in sospeso saranno convertiti in debiti ordinari tra i membri."
      }
    },
    "balance": {
      "header": "Durante l’archiviazione di questa avventura:",
      "merge": "Sposta i debiti nei debiti dei membri regolari",
      "keep": "Lascia debiti/saldi nell’avventura"
    },
    "archived": "Archiviato",
    "hint": {
      "action": "Inizia la tua prima avventura",
      "dismiss": "Ignora",
      "dismissed": "Puoi creare una nuova avventura in qualsiasi momento tramite il menu + in fondo allo schermo."
    },
    "title": "Avventure",
    "panel": {
      "total": "Totale"
    },
    "participants": {
      "title": "Membri",
      "add": "Aggiungi membri",
      "empty": "Non c'è ancora nessuno qui. Aggiungi dei membri per iniziare l'avventura."
    }
  },
  "ja-JP": {
    "editor": {
      "cover": "カバー",
      "upload": "自分で選ぶ",
      "name": "冒険の名前",
      "note": "すべてのメンバーがこの名前を表示します",
      "info": "冒険は、旅行や飲み代、または日々の共同出費など、すべてを平等に分担したい人たちのためのものです。冒険での債務は個々のユーザー間で発生するものではなく、全メンバー間で均等に精算されます。",
      "settings": "設定",
      "title": "新しい冒険"
    },
    "finish": {
      "archive": {
        "title": "冒険を完了する",
        "description": "冒険をアーカイブすると、新しい支出画面から削除され、あなたの冒険リストの最後に移動します。",
        "button": "冒険をアーカイブ"
      },
      "delete": {
        "button": (title) => `${title}を削除`,
        "hold": "長押しで削除",
        "label": "削除"
      }
    },
    "expenses": {
      "title": "経費",
      "total": "合計",
      "paidBy": "支払者",
      "paid": "支払い済み",
      "empty": "まだ何も起きていません。友達を招待して、支出を追加してみましょう。",
      "delete": {
        "hold": "長押しで削除"
      }
    },
    "spending": {
      "yours": "あなたの支出",
      "total": "合計支出"
    },
    "me": "私",
    "selector": {
      "regular": "割り勘"
    },
    "archive": {
      "header": "アーカイブ",
      "warning": "冒険のアーカイブは永久的で元に戻せません。",
      "merge": {
        "label": "残高を移行",
        "description": "このアドベンチャーがアーカイブされると、未清算の残高はメンバー間の通常の借金に変換されます。"
      }
    },
    "balance": {
      "header": "この冒険をアーカイブする際：",
      "merge": "債務を通常メンバーの債務に移動する",
      "keep": "冒険に借金／残高を残す"
    },
    "archived": "アーカイブ済み",
    "hint": {
      "action": "最初の冒険を始めよう",
      "dismiss": "閉じる",
      "dismissed": "画面下部の「+」メニューから、いつでも新しい冒険を作成できます。"
    },
    "title": "冒険",
    "panel": {
      "total": "合計"
    },
    "participants": {
      "title": "メンバー",
      "add": "メンバーを追加",
      "empty": "まだ誰もいません。冒険を始めるためにメンバーを追加しましょう。"
    }
  },
  "ko-KR": {
    "editor": {
      "cover": "커버",
      "upload": "직접 선택하세요",
      "name": "모험 이름",
      "note": "모든 멤버가 이 이름을 볼 수 있습니다",
      "info": "모험은 여행, 술집 계산, 또는 단순한 공동 가계비와 같이 비용을 공평하게 나누고 싶은 사람들을 위한 것입니다. 모험의 빚은 개인 사용자 간이 아니라 모든 회원들끼리 서로 공평하게 정산되도록 되어 있습니다.",
      "settings": "설정",
      "title": "새로운 모험"
    },
    "finish": {
      "archive": {
        "title": "모험 마무리하기",
        "description": "모험을 보관하면 새로운 지출 화면에서 제거되고 모험 목록의 맨 뒤로 이동합니다.",
        "button": "모험 보관하기"
      },
      "delete": {
        "button": (title) => `${title} 삭제`,
        "hold": "길게 눌러 삭제",
        "label": "삭제"
      }
    },
    "expenses": {
      "title": "지출",
      "total": "합계",
      "paidBy": "결제자",
      "paid": "결제 완료",
      "empty": "아직 아무 일도 일어나지 않았어요. 친구들을 초대하고 지출을 추가해서 시작해보세요.",
      "delete": {
        "hold": "길게 눌러서 삭제"
      }
    },
    "spending": {
      "yours": "내 지출",
      "total": "총 지출"
    },
    "me": "나",
    "selector": {
      "regular": "분할"
    },
    "archive": {
      "header": "아카이브",
      "warning": "이 모험을 보관하면 영구적으로 삭제되며 되돌릴 수 없습니다.",
      "merge": {
        "label": "잔액 이체",
        "description": "이 모험이 보관되면 미결제 잔액은 멤버들 간의 일반적인 부채로 전환됩니다."
      }
    },
    "balance": {
      "header": "이 모험을 보관할 때:",
      "merge": "부채를 일반 회원 부채로 이동",
      "keep": "모험에서 부채/잔액 남기기"
    },
    "archived": "보관됨",
    "hint": {
      "action": "첫 번째 모험을 시작하세요",
      "dismiss": "닫기",
      "dismissed": "화면 하단의 + 메뉴를 통해 언제든지 새로운 모험을 만들 수 있습니다."
    },
    "title": "모험",
    "panel": {
      "total": "총액"
    },
    "participants": {
      "title": "구성원",
      "add": "구성원 추가",
      "empty": "아직 아무도 없습니다. 모험을 시작하려면 멤버를 추가하세요."
    }
  },
  "nl-NL": {
    "editor": {
      "cover": "Omslag",
      "upload": "Kies zelf",
      "name": "Naam van het avontuur",
      "note": "Alle leden zien deze naam",
      "info": "Avonturen zijn er voor mensen die de kosten gelijk willen delen, of het nu om samen reizen, een gezamenlijke barrekening of gewoon huishoudelijke uitgaven gaat. De schulden binnen een avontuur zijn niet tussen losse gebruikers, maar onder alle leden om het eerlijk bij te houden.",
      "settings": "Instellingen",
      "title": "Nieuw avontuur"
    },
    "finish": {
      "archive": {
        "title": "Avontuur afronden",
        "description": "Als je het avontuur archiveert, wordt het van het nieuwe onkostenscherm verwijderd en naar het einde van je avonturenlijst verplaatst.",
        "button": "Avontuur archiveren"
      },
      "delete": {
        "button": (title) => `${title} verwijderen`,
        "hold": "Vasthouden om te verwijderen",
        "label": "Verwijderen"
      }
    },
    "expenses": {
      "title": "Uitgaven",
      "total": "Totaal",
      "paidBy": "Betaald door",
      "paid": "Betaald",
      "empty": "Er is nog niks gebeurd. Nodig wat vrienden uit en voeg uitgaven toe om op gang te komen.",
      "delete": {
        "hold": "Houd vast om te verwijderen"
      }
    },
    "spending": {
      "yours": "Jouw uitgaven",
      "total": "Totaal uitgegeven"
    },
    "me": "Ik",
    "selector": {
      "regular": "Splitsen"
    },
    "archive": {
      "header": "Archief",
      "warning": "Het archiveren van het avontuur is permanent en kan niet ongedaan worden gemaakt.",
      "merge": {
        "label": "Saldi overzetten",
        "description": "Wanneer dit avontuur wordt gearchiveerd, worden openstaande saldi omgezet in gewone schulden tussen de leden."
      }
    },
    "balance": {
      "header": "Bij het archiveren van dit avontuur:",
      "merge": "Verplaats schulden naar de gewone leden-schulden",
      "keep": "Schulden/saldi achterlaten in het avontuur"
    },
    "archived": "Gearchiveerd",
    "hint": {
      "action": "Begin aan je eerste avontuur",
      "dismiss": "Sluiten",
      "dismissed": "Je kunt altijd een nieuw avontuur starten via het + menu onderaan het scherm."
    },
    "title": "Avonturen",
    "panel": {
      "total": "Totaal"
    },
    "participants": {
      "title": "Leden",
      "add": "Leden toevoegen",
      "empty": "Hier is nog niemand. Voeg leden toe om het avontuur te beginnen."
    }
  },
  "ru-RU": {
    "editor": {
      "cover": "Обложка",
      "upload": "Выберите свой вариант",
      "name": "Название приключения",
      "note": "Все участники увидят это имя",
      "info": "Приключения созданы для тех, кто хочет делить расходы поровну — будь то совместное путешествие, счёт в баре или просто общие домашние траты. Долги в приключениях распределяются не между отдельными пользователями, а между всеми участниками, чтобы поддерживать равный баланс.",
      "settings": "Настройки",
      "title": "Новое приключение"
    },
    "finish": {
      "archive": {
        "title": "Завершить приключение",
        "description": "Архивация приключения удалит его с экрана новых расходов и переместит в конец вашего списка приключений.",
        "button": "Архивировать приключение"
      },
      "delete": {
        "button": (title) => `Удалить «${title}»`,
        "hold": "Удерживайте для удаления",
        "label": "Удалить"
      }
    },
    "expenses": {
      "title": "Расходы",
      "total": "Итого",
      "paidBy": "Оплачено",
      "paid": "Оплачено",
      "empty": "Пока ничего не произошло. Пригласите друзей и добавьте расходы, чтобы начать движение.",
      "delete": {
        "hold": "Удерживай, чтобы удалить"
      }
    },
    "spending": {
      "yours": "Ваши расходы",
      "total": "Всего потрачено"
    },
    "me": "Я",
    "selector": {
      "regular": "Разделить"
    },
    "archive": {
      "header": "Архив",
      "warning": "Архивирование приключения — это необратимое действие и не может быть отменено.",
      "merge": {
        "label": "Перевести балансы",
        "description": "Когда это приключение будет архивировано, все непогашенные балансы будут превращены в обычные долги между участниками."
      }
    },
    "balance": {
      "header": "При архивировании этого приключения:",
      "merge": "Перенести долги в долги обычных участников",
      "keep": "Оставить долги/балансы в приключении"
    },
    "archived": "Архивировано",
    "hint": {
      "action": "Начни своё первое приключение",
      "dismiss": "Закрыть",
      "dismissed": "Вы можете создать новое приключение в любое время через меню «+» внизу экрана."
    },
    "title": "Приключения",
    "panel": {
      "total": "Итого"
    },
    "participants": {
      "title": "Участники",
      "add": "Добавить участников",
      "empty": "Здесь пока никого нет. Добавьте участников, чтобы начать приключение."
    }
  },
  "sw-TZ": {
    "editor": {
      "cover": "Jalada",
      "upload": "Chagua yako mwenyewe",
      "name": "Jina la tukio",
      "note": "Wanachama wote wataona jina hili",
      "info": "Matukio ni kwa wale wanaotaka kugawana gharama sawa, iwe ni safari pamoja, bili ya baa, au matumizi ya kawaida ya nyumbani. Madeni kwenye tukio hayawekwi kati ya watumiaji mmoja mmoja, bali kati ya wanachama wote wanaosaidia kuweka usawa kwenye matumizi.",
      "settings": "Mipangilio",
      "title": "Ndoto Mpya"
    },
    "finish": {
      "archive": {
        "title": "Kamata safari",
        "description": "Kuhifadhi tukio hili kutaliondoa kwenye skrini ya matumizi mapya na kulipeleka mwisho wa orodha yako ya matukio.",
        "button": "Hifadhi adventure"
      },
      "delete": {
        "button": (title) => `Futa ${title}`,
        "hold": "Shikilia kufuta",
        "label": "Futa"
      }
    },
    "expenses": {
      "title": "Matumizi",
      "total": "Jumla",
      "paidBy": "Imelipiwa na",
      "paid": "Imelipwa",
      "empty": "Hakuna kilichotokea bado. Alika marafiki na ongeza matumizi ili mambo yaanze.",
      "delete": {
        "hold": "Shikilia ili ufute"
      }
    },
    "spending": {
      "yours": "Matumizi yako",
      "total": "Jumla iliyotumika"
    },
    "me": "Mimi",
    "selector": {
      "regular": "Gawanya"
    },
    "archive": {
      "header": "Kumbukumbu",
      "warning": "Kuhifadhi tukio hili ni la kudumu na haliwezi kubatilishwa.",
      "merge": {
        "label": "Hamisha salio",
        "description": "Safari hii itakapohifadhiwa, salio lolote lililobaki litageuzwa kuwa deni la kawaida kati ya wanachama."
      }
    },
    "balance": {
      "header": "Unapohifadhi tukio hili kwenye kumbukumbu:",
      "merge": "Hamisha madeni kwa madeni ya wanachama wa kawaida",
      "keep": "Acha madeni/saldo kwenye safari ya kusisimua"
    },
    "archived": "Imehifadhiwa",
    "hint": {
      "action": "Anza safari yako ya kwanza",
      "dismiss": "Funga",
      "dismissed": "Unaweza kuunda tukio jipya wakati wowote kupitia menyu ya + chini ya skrini."
    },
    "title": "Matukio",
    "panel": {
      "total": "Jumla"
    },
    "participants": {
      "title": "Wanachama",
      "add": "Ongeza wanachama",
      "empty": "Hakuna mtu hapa bado. Ongeza wanachama kuanza safari ya kichumbakazi."
    }
  },
  "tr-TR": {
    "editor": {
      "cover": "Kapak",
      "upload": "Kendi seçimini yap",
      "name": "Macera adı",
      "note": "Tüm üyeler bu ismi görecek",
      "info": "Macera, masrafları eşit şekilde paylaşmak isteyenler içindir; ister birlikte bir seyahat, ister bar hesabı ya da sadece ortak ev harcamaları olsun. Maceradaki borçlar bireysel kullanıcılar arasında değil, tüm üyeler arasında eşit şekilde tutulur.",
      "settings": "Ayarlar",
      "title": "Yeni Macera"
    },
    "finish": {
      "archive": {
        "title": "Macerayı bitir",
        "description": "Macera arşivlendiğinde yeni harcama ekranından kaldırılır ve macera listenizin sonuna taşınır.",
        "button": "Macera arşivle"
      },
      "delete": {
        "button": (title) => `${title} Sil`,
        "hold": "Silmek için basılı tutun",
        "label": "Sil"
      }
    },
    "expenses": {
      "title": "Giderler",
      "total": "Toplam",
      "paidBy": "Ödeyen",
      "paid": "Ödendi",
      "empty": "Henüz hiçbir şey olmadı. Birkaç arkadaşını davet et ve harcamalar ekleyerek işleri başlat.",
      "delete": {
        "hold": "Silmek için basılı tut"
      }
    },
    "spending": {
      "yours": "Harcamalarınız",
      "total": "Toplam harcama"
    },
    "me": "Ben",
    "selector": {
      "regular": "Böl"
    },
    "archive": {
      "header": "Arşiv",
      "warning": "Macera arşivlendiğinde bu işlem kalıcıdır ve geri alınamaz.",
      "merge": {
        "label": "Bakiyeleri aktar",
        "description": "Bu macera arşivlendiğinde, açık bakiyeler üyeler arasındaki normal borçlara dönüştürülecektir."
      }
    },
    "balance": {
      "header": "Bu macera arşivlenirken:",
      "merge": "Borçları normal üye borçlarına taşı",
      "keep": "Macera sırasında borçları/bakiyeleri bırak"
    },
    "archived": "Arşivlendi",
    "hint": {
      "action": "İlk macerana başla",
      "dismiss": "Kapat",
      "dismissed": "Ekranın altındaki + menüsünden istediğin zaman yeni bir macera oluşturabilirsin."
    },
    "title": "Macera",
    "panel": {
      "total": "Toplam"
    },
    "participants": {
      "title": "Üyeler",
      "add": "Üye ekle",
      "empty": "Henüz burada kimse yok. Maceraya başlamak için birkaç üye ekle."
    }
  },
  "uk-UA": {
    "editor": {
      "cover": "Обкладинка",
      "upload": "Виберіть свій варіант",
      "name": "Назва пригоди",
      "note": "Усі учасники побачать це ім'я",
      "info": "Пригоди створені для тих, хто хоче ділити витрати порівну — чи це спільна подорож, рахунок у барі чи просто загальні домашні витрати. Борги в пригоді виникають не між окремими користувачами, а між усіма учасниками, щоб кожен мав рівні частки.",
      "settings": "Налаштування",
      "title": "Нова пригода"
    },
    "finish": {
      "archive": {
        "title": "Завершити пригоду",
        "description": "Архівування пригоди видалить її з екрана нових витрат і перемістить у кінець вашого списку пригод.",
        "button": "Архівувати пригоду"
      },
      "delete": {
        "button": (title) => `Видалити «${title}»`,
        "hold": "Утримуйте для видалення",
        "label": "Видалити"
      }
    },
    "expenses": {
      "title": "Витрати",
      "total": "Всього",
      "paidBy": "Сплачено",
      "paid": "Оплачено",
      "empty": "Поки що нічого не сталося. Запросіть друзів і додайте витрати, щоб почати рух.",
      "delete": {
        "hold": "Утримуй, щоб видалити"
      }
    },
    "spending": {
      "yours": "Ваші витрати",
      "total": "Всього витрачено"
    },
    "me": "Я",
    "selector": {
      "regular": "Розділити"
    },
    "archive": {
      "header": "Архів",
      "warning": "Архівування пригоди є остаточним і не може бути скасоване.",
      "merge": {
        "label": "Перенести баланси",
        "description": "Коли цю пригоду буде заархівовано, невиплачені залишки перетворяться на звичайні борги між учасниками."
      }
    },
    "balance": {
      "header": "Під час архівування цієї пригоди:",
      "merge": "Перемістити борги до боргів звичайних учасників",
      "keep": "Залишити борги/баланс у пригоді"
    },
    "archived": "Заархівовано",
    "hint": {
      "action": "Почни свою першу пригоду",
      "dismiss": "Закрити",
      "dismissed": "Ви можете створити нову пригоду будь-коли через меню «+» внизу екрана."
    },
    "title": "Пригоди",
    "panel": {
      "total": "Разом"
    },
    "participants": {
      "title": "Учасники",
      "add": "Додати учасників",
      "empty": "Тут поки нікого немає. Додайте учасників, щоб розпочати пригоду."
    }
  },
  "zh-CN": {
    "editor": {
      "cover": "封面",
      "upload": "自行选择",
      "name": "冒险名称",
      "note": "所有成员都能看到此名字",
      "info": "冒险适合那些希望平等分担花费的人，无论是一起旅行、共同买单还是家庭开支。冒险中的债务不是个人之间的，而是所有成员共同分担，确保每个人的账目都公平。",
      "settings": "设置",
      "title": "新冒险"
    },
    "finish": {
      "archive": {
        "title": "完成冒险",
        "description": "将冒险归档后，它会从新增支出页面移除，并被移到你的冒险列表末尾。",
        "button": "归档冒险"
      },
      "delete": {
        "button": (title) => `删除${title}`,
        "hold": "按住删除",
        "label": "删除"
      }
    },
    "expenses": {
      "title": "支出",
      "total": "总计",
      "paidBy": "由...支付",
      "paid": "已支付",
      "empty": "还没有任何活动。邀请一些朋友并添加花费，让事情开始运转吧。",
      "delete": {
        "hold": "长按删除"
      }
    },
    "spending": {
      "yours": "你的支出",
      "total": "总支出"
    },
    "me": "我",
    "selector": {
      "regular": "分摊"
    },
    "archive": {
      "header": "归档",
      "warning": "归档此冒险将是永久性的，无法撤销。",
      "merge": {
        "label": "转移余额",
        "description": "当此冒险被归档时，未结清的余额将转换为成员之间的常规债务。"
      }
    },
    "balance": {
      "header": "归档此冒险时：",
      "merge": "将债务移至普通成员债务",
      "keep": "在冒险中留下债务/余额"
    },
    "archived": "已归档",
    "hint": {
      "action": "开启你的第一次冒险",
      "dismiss": "关闭",
      "dismissed": "你可以随时通过屏幕底部的 + 菜单创建新的冒险。"
    },
    "title": "冒险",
    "panel": {
      "total": "总计"
    },
    "participants": {
      "title": "成员",
      "add": "添加成员",
      "empty": "这里还没有人。添加一些成员，开启冒险之旅吧。"
    }
  }
};
