// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("./types").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "members": {
      "title": "الأعضاء",
      "add": "إضافة أعضاء",
      "empty": "لا يوجد أحد هنا بعد. أضِف بعض الأعضاء لبدء المغامرة."
    },
    "editor": {
      "cover": "غلاف",
      "upload": "اختر بنفسك",
      "name": "اسم المغامرة",
      "note": "سيتمكن جميع الأعضاء من رؤية هذا الاسم",
      "info": "المغامرات مخصصة لأولئك الذين يرغبون في الإنفاق بالتساوي، سواء كانت رحلة معًا أو فاتورة بار أو حتى مصاريف منزلية مشتركة. الديون في المغامرة ليست بين الأفراد، بل بين جميع الأعضاء للحفاظ على حسابات متساوية للجميع.",
      "settings": "الإعدادات",
      "title": "مغامرة جديدة"
    },
    "finish": {
      "archive": {
        "title": "أنهِ المغامرة",
        "description": "أرشفة المغامرة ستزيلها من شاشة المصاريف الجديدة وتنقلها إلى نهاية قائمة مغامراتك.",
        "button": "أرشفة المغامرة"
      },
      "delete": {
        "title": "حذف المغامرة",
        "description": "لم يحدث أي شيء بعد. ادعُ بعض الأصدقاء وأضِف بعض المصروفات لتبدأ الأمور.",
        "button": (title) => `حذف ${title}`
      }
    },
    "expenses": {
      "title": "النفقات",
      "total": "الإجمالي",
      "paidBy": "دفع بواسطة",
      "paid": "دفع"
    },
    "spending": {
      "yours": "إنفاقك",
      "total": "إجمالي الإنفاق"
    },
    "me": "أنا",
    "selector": {
      "regular": "الإنفاق المنتظم"
    },
    "archive": {
      "header": (title, empty) => empty ? `يتم حذف ${title}` : `يتم أرشفة ${title}`,
      "delete": {
        "description": "هذه المغامرة ليس لديها أي نفقات وسيتم حذفها",
        "button": "حذف المغامرة"
      },
      "warning": "أرشفة المغامرة إجراء دائم ولا يمكن التراجع عنه."
    },
    "balance": {
      "header": "عند أرشفة هذه المغامرة:",
      "merge": "انقل الديون إلى ديون الأعضاء العاديين",
      "keep": "ترك الديون/الأرصدة في المغامرة"
    },
    "archived": "مؤرشف"
  },
  "de-DE": {
    "members": {
      "title": "Mitglieder",
      "add": "Mitglieder hinzufügen",
      "empty": "Hier ist noch niemand. Füge Mitglieder hinzu, um das Abenteuer zu starten."
    },
    "editor": {
      "cover": "Titelbild",
      "upload": "Wähle selbst",
      "name": "Abenteuername",
      "note": "Alle Mitglieder sehen diesen Namen",
      "info": "Abenteuer sind für diejenigen, die die Ausgaben gleichmäßig teilen möchten – egal ob gemeinsame Reise, Bar-Rechnung oder einfach Haushaltskosten. Die Schulden innerhalb eines Abenteuers bestehen nicht zwischen einzelnen Nutzern, sondern gegenüber allen Mitgliedern, sodass alle Ausgaben fair abgerechnet werden.",
      "settings": "Einstellungen",
      "title": "Neues Abenteuer"
    },
    "finish": {
      "archive": {
        "title": "Abenteuer abschließen",
        "description": "Wenn du das Abenteuer archivierst, wird es vom Bildschirm für neue Ausgaben entfernt und ans Ende deiner Abenteuerliste verschoben.",
        "button": "Abenteuer archivieren"
      },
      "delete": {
        "title": "Abenteuer löschen",
        "description": "Bisher ist noch nichts passiert. Lade ein paar Freunde ein und füge Ausgaben hinzu, um loszulegen.",
        "button": (title) => `"${title}" löschen`
      }
    },
    "expenses": {
      "title": "Ausgaben",
      "total": "Gesamt",
      "paidBy": "Bezahlt von",
      "paid": "Bezahlt"
    },
    "spending": {
      "yours": "Ihre Ausgaben",
      "total": "Gesamtausgaben"
    },
    "me": "Ich",
    "selector": {
      "regular": "Regelmäßige Ausgaben"
    },
    "archive": {
      "header": (title, empty) => empty ? `${title} wird gelöscht` : `${title} wird archiviert`,
      "delete": {
        "description": "Dieses Abenteuer hat keine Ausgaben und wird gelöscht",
        "button": "Abenteuer löschen"
      },
      "warning": "Das Archivieren des Abenteuers ist dauerhaft und kann nicht rückgängig gemacht werden."
    },
    "balance": {
      "header": "Beim Archivieren dieses Abenteuers:",
      "merge": "Schulden zu den regulären Mitgliedsschulden übertragen",
      "keep": "Schulden/Salden im Abenteuer belassen"
    },
    "archived": "Archiviert"
  },
  "en-US": {
    "members": {
      "title": "Members",
      "add": "Add members",
      "empty": "Nobody here yet. Add some members to start the adventure."
    },
    "editor": {
      "cover": "Cover",
      "upload": "Choose your own",
      "name": "Adventure name",
      "note": "All members will see this name",
      "info": "Adventures are for those who want to split expenses equally, whether it's a trip together, a bar tab, or just shared household costs. Debts in an adventure aren't between individual users but among all members, keeping everyone’s share balanced.",
      "settings": "Settings",
      "title": "New Adventure"
    },
    "finish": {
      "archive": {
        "title": "Finish the adventure",
        "description": "Archiving the adventure will remove it from the new expense screen and move it to the back of your adventure list.",
        "button": "Archive adventure"
      },
      "delete": {
        "title": "Delete adventure",
        "description": "Nothing's happened yet. Invite some friends and add some expenses to get started.",
        "button": (title) => `Delete ${title}`
      }
    },
    "expenses": {
      "title": "Expenses",
      "total": "Total",
      "paidBy": "Paid by",
      "paid": "Paid"
    },
    "spending": {
      "yours": "Your spending",
      "total": "Total spent"
    },
    "me": "Me",
    "selector": {
      "regular": "Regular spending"
    },
    "archive": {
      "header": (title, empty) => empty ? `Deleting ${title}` : `Archiving ${title}`,
      "delete": {
        "description": "This adventure has no expenses and will be deleted",
        "button": "Delete adventure"
      },
      "warning": "Archiving the adventure is permanent and cannot be undone."
    },
    "balance": {
      "header": "When archiving this adventure:",
      "merge": "Move debts to the regular member debts",
      "keep": "Leave debts/balances in adventure"
    },
    "archived": "Archived"
  },
  "es-ES": {
    "members": {
      "title": "Miembros",
      "add": "Agregar miembros",
      "empty": "Todavía no hay nadie aquí. Añade algunos miembros para comenzar la aventura."
    },
    "editor": {
      "cover": "Portada",
      "upload": "Elige el tuyo",
      "name": "Nombre de la aventura",
      "note": "Todos los miembros verán este nombre",
      "info": "Las aventuras son para quienes desean compartir los gastos por igual, ya sea un viaje juntos, una cuenta de bar o simplemente los gastos comunes del hogar. Las deudas en una aventura no son entre usuarios individuales, sino entre todos los miembros, para mantener cuentas equitativas.",
      "settings": "Configuración",
      "title": "Nueva aventura"
    },
    "finish": {
      "archive": {
        "title": "Finalizar la aventura",
        "description": "Archivar la aventura la eliminará de la pantalla de nuevos gastos y la moverá al final de tu lista de aventuras.",
        "button": "Archivar aventura"
      },
      "delete": {
        "title": "Eliminar aventura",
        "description": "Todavía no ha pasado nada. Invita a algunos amigos y añade algunos gastos para poner esto en marcha.",
        "button": (title) => `Eliminar ${title}`
      }
    },
    "expenses": {
      "title": "Gastos",
      "total": "Total",
      "paidBy": "Pagado por",
      "paid": "Pagado"
    },
    "spending": {
      "yours": "Tus gastos",
      "total": "Total gastado"
    },
    "me": "Yo",
    "selector": {
      "regular": "Gastos habituales"
    },
    "archive": {
      "header": (title, empty) => empty ? `Eliminando ${title}` : `Archivando ${title}`,
      "delete": {
        "description": "Esta aventura no tiene gastos y será eliminada",
        "button": "Eliminar aventura"
      },
      "warning": "Archivar la aventura es una acción permanente y no se puede deshacer."
    },
    "balance": {
      "header": "Al archivar esta aventura:",
      "merge": "Mover deudas a las deudas de miembros regulares",
      "keep": "Dejar deudas/saldos en la aventura"
    },
    "archived": "Archivado"
  },
  "fr-FR": {
    "members": {
      "title": "Membres",
      "add": "Ajouter des membres",
      "empty": "Personne n'est encore là. Ajoutez des membres pour commencer l'aventure."
    },
    "editor": {
      "cover": "Couverture",
      "upload": "Choisissez le vôtre",
      "name": "Nom de l’aventure",
      "note": "Tous les membres verront ce nom",
      "info": "Les aventures sont faites pour ceux qui veulent partager les dépenses de manière égale, que ce soit un voyage ensemble, une addition de bar ou simplement des frais ménagers communs. Les dettes lors d’une aventure ne sont pas entre individus, mais entre tous les membres pour garder un équilibre équitable.",
      "settings": "Paramètres",
      "title": "Nouvelle aventure"
    },
    "finish": {
      "archive": {
        "title": "Terminer l’aventure",
        "description": "Archiver l’aventure la retirera de l’écran des nouvelles dépenses et la placera à la fin de ta liste d’aventures.",
        "button": "Archiver l’aventure"
      },
      "delete": {
        "title": "Supprimer l’aventure",
        "description": "Rien ne s'est encore passé. Invitez des amis et ajoutez des dépenses pour lancer les choses.",
        "button": (title) => `Supprimer ${title}`
      }
    },
    "expenses": {
      "title": "Dépenses",
      "total": "Total",
      "paidBy": "Payé par",
      "paid": "Payé"
    },
    "spending": {
      "yours": "Vos dépenses",
      "total": "Total dépensé"
    },
    "me": "Moi",
    "selector": {
      "regular": "Dépenses régulières"
    },
    "archive": {
      "header": (title, empty) => empty ? `Suppression de ${title}` : `Archivage de ${title}`,
      "delete": {
        "description": "Cette aventure n'a aucune dépense et sera supprimée",
        "button": "Supprimer l’aventure"
      },
      "warning": "L’archivage de l’aventure est définitif et ne peut pas être annulé."
    },
    "balance": {
      "header": "Lors de l’archivage de cette aventure :",
      "merge": "Transférer les dettes vers les dettes des membres réguliers",
      "keep": "Laisser les dettes/soldes dans l’aventure"
    },
    "archived": "Archivé"
  },
  "hi-IN": {
    "members": {
      "title": "सदस्य",
      "add": "सदस्य जोड़ें",
      "empty": "अभी यहाँ कोई नहीं है। साहसिक यात्रा शुरू करने के लिए कुछ सदस्य जोड़ें।"
    },
    "editor": {
      "cover": "कवर",
      "upload": "अपना स्वयं चुनें",
      "name": "साहसिक कार्य का नाम",
      "note": "सभी सदस्य यह नाम देख पाएंगे",
      "info": "रोमांच उन लोगों के लिए है जो खर्च बराबर करना चाहते हैं, चाहे वह साथ में यात्रा हो, बार का बिल हो या सिर्फ सामान्य घरेलू खर्च। रोमांच में क़र्ज़े व्यक्तिगत यूज़र्स के बीच नहीं, बल्कि सभी सदस्यों के बीच होते हैं ताकि सभी का हिसाब बराबर रहे।",
      "settings": "सेटिंग्स",
      "title": "नई रोमांचक यात्रा"
    },
    "finish": {
      "archive": {
        "title": "साहसिक कार्य समाप्त करें",
        "description": "एडवेंचर को आर्काइव करने से यह नए खर्च स्क्रीन से हट जाएगा और आपकी एडवेंचर सूची के अंत में चला जाएगा।",
        "button": "एडवेंचर को संग्रहित करें"
      },
      "delete": {
        "title": "साहसिक कार्य हटाएं",
        "description": "अभी तक कुछ भी नहीं हुआ है। दोस्तों को बुलाएँ और कुछ खर्च जोड़ें ताकि शुरुआत हो सके।",
        "button": (title) => `${title} हटाएँ`
      }
    },
    "expenses": {
      "title": "खर्चे",
      "total": "कुल",
      "paidBy": "द्वारा भुगतान किया गया",
      "paid": "भुगतान किया गया"
    },
    "spending": {
      "yours": "आपके खर्च",
      "total": "कुल खर्च"
    },
    "me": "मैं",
    "selector": {
      "regular": "नियमित खर्च"
    },
    "archive": {
      "header": (title, empty) => empty ? `${title} को हटाया जा रहा है` : `${title} को संग्रहित किया जा रहा है`,
      "delete": {
        "description": "इस साहसिक यात्रा में कोई खर्च नहीं है और इसे हटाया जाएगा",
        "button": "एडवेंचर हटाएँ"
      },
      "warning": "एडवेंचर को आर्काइव करना स्थायी है और इसे वापस नहीं लिया जा सकता।"
    },
    "balance": {
      "header": "इस साहसिक कार्य को संग्रहित करते समय:",
      "merge": "ऋणों को नियमित सदस्य के ऋणों में स्थानांतरित करें",
      "keep": "ऋण/शेष राशि को साहसिक यात्रा में ही रखें"
    },
    "archived": "संग्रहीत"
  },
  "it-IT": {
    "members": {
      "title": "Membri",
      "add": "Aggiungi membri",
      "empty": "Non c'è ancora nessuno qui. Aggiungi dei membri per iniziare l'avventura."
    },
    "editor": {
      "cover": "Copertina",
      "upload": "Scegli il tuo",
      "name": "Nome dell’avventura",
      "note": "Tutti i membri vedranno questo nome",
      "info": "Le avventure sono per chi vuole dividere le spese in modo equo, che si tratti di un viaggio insieme, di un conto al bar o delle semplici spese domestiche comuni. I debiti in un’avventura non sono tra utenti singoli, ma tra tutti i partecipanti, così da mantenere i conti in pari per tutti.",
      "settings": "Impostazioni",
      "title": "Nuova avventura"
    },
    "finish": {
      "archive": {
        "title": "Concludi l’avventura",
        "description": "Archiviare l’avventura la rimuoverà dalla schermata delle nuove spese e la sposterà in fondo alla tua lista di avventure.",
        "button": "Archivia avventura"
      },
      "delete": {
        "title": "Elimina avventura",
        "description": "Non è ancora successo nulla. Invita qualche amico e aggiungi delle spese per iniziare.",
        "button": (title) => `Elimina ${title}`
      }
    },
    "expenses": {
      "title": "Spese",
      "total": "Totale",
      "paidBy": "Pagato da",
      "paid": "Pagato"
    },
    "spending": {
      "yours": "Le tue spese",
      "total": "Totale speso"
    },
    "me": "Io",
    "selector": {
      "regular": "Spese regolari"
    },
    "archive": {
      "header": (title, empty) => empty ? `Eliminazione di ${title}` : `Archiviazione di ${title}`,
      "delete": {
        "description": "Questa avventura non ha spese e verrà eliminata",
        "button": "Elimina avventura"
      },
      "warning": "L’archiviazione dell’avventura è permanente e non può essere annullata."
    },
    "balance": {
      "header": "Durante l’archiviazione di questa avventura:",
      "merge": "Sposta i debiti nei debiti dei membri regolari",
      "keep": "Lascia debiti/saldi nell’avventura"
    },
    "archived": "Archiviato"
  },
  "ja-JP": {
    "members": {
      "title": "メンバー",
      "add": "メンバーを追加",
      "empty": "まだ誰もいません。冒険を始めるためにメンバーを追加しましょう。"
    },
    "editor": {
      "cover": "カバー",
      "upload": "自分で選ぶ",
      "name": "冒険の名前",
      "note": "すべてのメンバーがこの名前を表示します",
      "info": "冒険は、旅行や飲み代、または日々の共同出費など、すべてを平等に分担したい人たちのためのものです。冒険での債務は個々のユーザー間で発生するものではなく、全メンバー間で均等に精算されます。",
      "settings": "設定",
      "title": "新しい冒険"
    },
    "finish": {
      "archive": {
        "title": "冒険を完了する",
        "description": "冒険をアーカイブすると、新しい支出画面から削除され、あなたの冒険リストの最後に移動します。",
        "button": "冒険をアーカイブ"
      },
      "delete": {
        "title": "冒険を削除",
        "description": "まだ何も起きていません。友達を招待して、支出を追加してみましょう。",
        "button": (title) => `${title}を削除`
      }
    },
    "expenses": {
      "title": "経費",
      "total": "合計",
      "paidBy": "支払者",
      "paid": "支払い済み"
    },
    "spending": {
      "yours": "あなたの支出",
      "total": "合計支出"
    },
    "me": "私",
    "selector": {
      "regular": "定期的な支出"
    },
    "archive": {
      "header": (title, empty) => empty ? `${title}を削除中` : `${title}をアーカイブ中`,
      "delete": {
        "description": "このアドベンチャーには費用がかからず、削除されます",
        "button": "冒険を削除"
      },
      "warning": "冒険のアーカイブは永久的で元に戻せません。"
    },
    "balance": {
      "header": "この冒険をアーカイブする際：",
      "merge": "債務を通常メンバーの債務に移動する",
      "keep": "借金／残高を冒険内に残す"
    },
    "archived": "アーカイブ済み"
  },
  "ko-KR": {
    "members": {
      "title": "구성원",
      "add": "구성원 추가",
      "empty": "아직 아무도 없습니다. 모험을 시작하려면 멤버를 추가하세요."
    },
    "editor": {
      "cover": "커버",
      "upload": "직접 선택하세요",
      "name": "모험 이름",
      "note": "모든 멤버가 이 이름을 볼 수 있습니다",
      "info": "모험은 여행, 술집 계산, 또는 단순한 공동 가계비와 같이 비용을 공평하게 나누고 싶은 사람들을 위한 것입니다. 모험의 빚은 개인 사용자 간이 아니라 모든 회원들끼리 서로 공평하게 정산되도록 되어 있습니다.",
      "settings": "설정",
      "title": "새로운 모험"
    },
    "finish": {
      "archive": {
        "title": "모험 마무리하기",
        "description": "모험을 보관하면 새로운 지출 화면에서 제거되고 모험 목록의 맨 뒤로 이동합니다.",
        "button": "모험 보관하기"
      },
      "delete": {
        "title": "모험 삭제",
        "description": "아직 아무 일도 일어나지 않았어요. 친구들을 초대하고 지출을 추가해 시작해보세요.",
        "button": (title) => `${title} 삭제`
      }
    },
    "expenses": {
      "title": "지출",
      "total": "합계",
      "paidBy": "결제자",
      "paid": "결제 완료"
    },
    "spending": {
      "yours": "내 지출",
      "total": "총 지출"
    },
    "me": "나",
    "selector": {
      "regular": "정기 지출"
    },
    "archive": {
      "header": (title, empty) => empty ? `${title} 삭제 중` : `${title} 보관 중`,
      "delete": {
        "description": "이 모험에는 비용이 없으며 삭제됩니다",
        "button": "모험 삭제"
      },
      "warning": "이 모험을 보관하면 영구적으로 삭제되며 되돌릴 수 없습니다."
    },
    "balance": {
      "header": "이 모험을 보관할 때:",
      "merge": "부채를 일반 회원 부채로 이동",
      "keep": "모험 내에 부채/잔액 남기기"
    },
    "archived": "보관됨"
  },
  "nl-NL": {
    "members": {
      "title": "Leden",
      "add": "Leden toevoegen",
      "empty": "Hier is nog niemand. Voeg leden toe om het avontuur te beginnen."
    },
    "editor": {
      "cover": "Omslag",
      "upload": "Kies zelf",
      "name": "Naam van het avontuur",
      "note": "Alle leden zien deze naam",
      "info": "Avonturen zijn er voor mensen die de kosten gelijk willen delen, of het nu om samen reizen, een gezamenlijke barrekening of gewoon huishoudelijke uitgaven gaat. De schulden binnen een avontuur zijn niet tussen losse gebruikers, maar onder alle leden om het eerlijk bij te houden.",
      "settings": "Instellingen",
      "title": "Nieuw avontuur"
    },
    "finish": {
      "archive": {
        "title": "Avontuur afronden",
        "description": "Als je het avontuur archiveert, wordt het van het nieuwe onkostenscherm verwijderd en naar het einde van je avonturenlijst verplaatst.",
        "button": "Avontuur archiveren"
      },
      "delete": {
        "title": "Avontuur verwijderen",
        "description": "Er is nog niets gebeurd. Nodig wat vrienden uit en voeg uitgaven toe om te beginnen.",
        "button": (title) => `${title} verwijderen`
      }
    },
    "expenses": {
      "title": "Uitgaven",
      "total": "Totaal",
      "paidBy": "Betaald door",
      "paid": "Betaald"
    },
    "spending": {
      "yours": "Jouw uitgaven",
      "total": "Totaal uitgegeven"
    },
    "me": "Ik",
    "selector": {
      "regular": "Regelmatige uitgaven"
    },
    "archive": {
      "header": (title, empty) => empty ? `${title} wordt verwijderd` : `${title} wordt gearchiveerd`,
      "delete": {
        "description": "Dit avontuur heeft geen uitgaven en wordt verwijderd",
        "button": "Avontuur verwijderen"
      },
      "warning": "Het archiveren van het avontuur is permanent en kan niet ongedaan worden gemaakt."
    },
    "balance": {
      "header": "Bij het archiveren van dit avontuur:",
      "merge": "Verplaats schulden naar de gewone leden-schulden",
      "keep": "Schulden/saldi in het avontuur laten"
    },
    "archived": "Gearchiveerd"
  },
  "ru-RU": {
    "members": {
      "title": "Участники",
      "add": "Добавить участников",
      "empty": "Здесь пока никого нет. Добавьте участников, чтобы начать приключение."
    },
    "editor": {
      "cover": "Обложка",
      "upload": "Выберите свой вариант",
      "name": "Название приключения",
      "note": "Все участники увидят это имя",
      "info": "Приключения созданы для тех, кто хочет делить расходы поровну — будь то совместное путешествие, счёт в баре или просто общие домашние траты. Долги в приключениях распределяются не между отдельными пользователями, а между всеми участниками, чтобы поддерживать равный баланс.",
      "settings": "Настройки",
      "title": "Новое приключение"
    },
    "finish": {
      "archive": {
        "title": "Завершить приключение",
        "description": "Архивация приключения удалит его с экрана новых расходов и переместит в конец вашего списка приключений.",
        "button": "Архивировать приключение"
      },
      "delete": {
        "title": "Удалить приключение",
        "description": "Пока ничего не произошло. Пригласите друзей и добавьте расходы, чтобы начать.",
        "button": (title) => `Удалить «${title}»`
      }
    },
    "expenses": {
      "title": "Расходы",
      "total": "Итого",
      "paidBy": "Оплачено",
      "paid": "Оплачено"
    },
    "spending": {
      "yours": "Ваши расходы",
      "total": "Всего потрачено"
    },
    "me": "Я",
    "selector": {
      "regular": "Регулярные расходы"
    },
    "archive": {
      "header": (title, empty) => empty ? `Удаление ${title}` : `Архивирование ${title}`,
      "delete": {
        "description": "У этого приключения нет расходов, и оно будет удалено",
        "button": "Удалить приключение"
      },
      "warning": "Архивирование приключения — это необратимое действие и не может быть отменено."
    },
    "balance": {
      "header": "При архивировании этого приключения:",
      "merge": "Перенести долги в долги обычных участников",
      "keep": "Оставить долги/балансы в приключении"
    },
    "archived": "Архивировано"
  },
  "sw-TZ": {
    "members": {
      "title": "Wanachama",
      "add": "Ongeza wanachama",
      "empty": "Hakuna mtu hapa bado. Ongeza wanachama kuanza safari ya kichumbakazi."
    },
    "editor": {
      "cover": "Jalada",
      "upload": "Chagua yako mwenyewe",
      "name": "Jina la tukio",
      "note": "Wanachama wote wataona jina hili",
      "info": "Matukio ni kwa wale wanaotaka kugawana gharama sawa, iwe ni safari pamoja, bili ya baa, au matumizi ya kawaida ya nyumbani. Madeni kwenye tukio hayawekwi kati ya watumiaji mmoja mmoja, bali kati ya wanachama wote wanaosaidia kuweka usawa kwenye matumizi.",
      "settings": "Mipangilio",
      "title": "Ndoto Mpya"
    },
    "finish": {
      "archive": {
        "title": "Kamata safari",
        "description": "Kuhifadhi tukio hili kutaliondoa kwenye skrini ya matumizi mapya na kulipeleka mwisho wa orodha yako ya matukio.",
        "button": "Hifadhi adventure"
      },
      "delete": {
        "title": "Futa tukio",
        "description": "Hakuna kilichotokea bado. Karibu marafiki zako na ongeza matumizi ili uanze mambo.",
        "button": (title) => `Futa ${title}`
      }
    },
    "expenses": {
      "title": "Matumizi",
      "total": "Jumla",
      "paidBy": "Imelipiwa na",
      "paid": "Imelipwa"
    },
    "spending": {
      "yours": "Matumizi yako",
      "total": "Jumla iliyotumika"
    },
    "me": "Mimi",
    "selector": {
      "regular": "Matumizi ya kawaida"
    },
    "archive": {
      "header": (title, empty) => empty ? `Inaondoa ${title}` : `Inaweka ${title} kwenye kumbukumbu`,
      "delete": {
        "description": "Safari hii haina matumizi na itafutwa",
        "button": "Futa tukio"
      },
      "warning": "Kuhifadhi tukio hili ni la kudumu na haliwezi kubatilishwa."
    },
    "balance": {
      "header": "Unapohifadhi tukio hili kwenye kumbukumbu:",
      "merge": "Hamisha madeni kwa madeni ya wanachama wa kawaida",
      "keep": "Acha madeni/saldo ndani ya tukio la冒险"
    },
    "archived": "Imehifadhiwa"
  },
  "tr-TR": {
    "members": {
      "title": "Üyeler",
      "add": "Üye ekle",
      "empty": "Henüz burada kimse yok. Maceraya başlamak için birkaç üye ekle."
    },
    "editor": {
      "cover": "Kapak",
      "upload": "Kendi seçimini yap",
      "name": "Macera adı",
      "note": "Tüm üyeler bu ismi görecek",
      "info": "Macera, masrafları eşit şekilde paylaşmak isteyenler içindir; ister birlikte bir seyahat, ister bar hesabı ya da sadece ortak ev harcamaları olsun. Maceradaki borçlar bireysel kullanıcılar arasında değil, tüm üyeler arasında eşit şekilde tutulur.",
      "settings": "Ayarlar",
      "title": "Yeni Macera"
    },
    "finish": {
      "archive": {
        "title": "Macerayı bitir",
        "description": "Macera arşivlendiğinde yeni harcama ekranından kaldırılır ve macera listenizin sonuna taşınır.",
        "button": "Macera arşivle"
      },
      "delete": {
        "title": "Macera sil",
        "description": "Henüz hiçbir şey olmadı. Birkaç arkadaşını davet et ve harcamalar ekleyerek işleri başlat.",
        "button": (title) => `${title} Sil`
      }
    },
    "expenses": {
      "title": "Giderler",
      "total": "Toplam",
      "paidBy": "Ödeyen",
      "paid": "Ödendi"
    },
    "spending": {
      "yours": "Harcamalarınız",
      "total": "Toplam harcama"
    },
    "me": "Ben",
    "selector": {
      "regular": "Düzenli harcamalar"
    },
    "archive": {
      "header": (title, empty) => empty ? `${title} siliniyor` : `${title} arşivleniyor`,
      "delete": {
        "description": "Bu maceranın gideri yok ve silinecek",
        "button": "Macera sil"
      },
      "warning": "Macera arşivlendiğinde bu işlem kalıcıdır ve geri alınamaz."
    },
    "balance": {
      "header": "Bu macera arşivlenirken:",
      "merge": "Borçları normal üye borçlarına taşı",
      "keep": "Borçları/bakiyeleri macerada bırak"
    },
    "archived": "Arşivlendi"
  },
  "uk-UA": {
    "members": {
      "title": "Учасники",
      "add": "Додати учасників",
      "empty": "Тут поки нікого немає. Додайте учасників, щоб розпочати пригоду."
    },
    "editor": {
      "cover": "Обкладинка",
      "upload": "Виберіть свій варіант",
      "name": "Назва пригоди",
      "note": "Усі учасники побачать це ім'я",
      "info": "Пригоди створені для тих, хто хоче ділити витрати порівну — чи це спільна подорож, рахунок у барі чи просто загальні домашні витрати. Борги в пригоді виникають не між окремими користувачами, а між усіма учасниками, щоб кожен мав рівні частки.",
      "settings": "Налаштування",
      "title": "Нова пригода"
    },
    "finish": {
      "archive": {
        "title": "Завершити пригоду",
        "description": "Архівування пригоди видалить її з екрана нових витрат і перемістить у кінець вашого списку пригод.",
        "button": "Архівувати пригоду"
      },
      "delete": {
        "title": "Видалити пригоду",
        "description": "Поки що нічого не сталося. Запросіть друзів і додайте витрати, щоб розпочати.",
        "button": (title) => `Видалити «${title}»`
      }
    },
    "expenses": {
      "title": "Витрати",
      "total": "Всього",
      "paidBy": "Сплачено",
      "paid": "Оплачено"
    },
    "spending": {
      "yours": "Ваші витрати",
      "total": "Всього витрачено"
    },
    "me": "Я",
    "selector": {
      "regular": "Регулярні витрати"
    },
    "archive": {
      "header": (title, empty) => empty ? `Видалення ${title}` : `Архівування ${title}`,
      "delete": {
        "description": "У цій пригоді немає витрат, і вона буде видалена",
        "button": "Видалити пригоду"
      },
      "warning": "Архівування пригоди є остаточним і не може бути скасоване."
    },
    "balance": {
      "header": "Під час архівування цієї пригоди:",
      "merge": "Перемістити борги до боргів звичайних учасників",
      "keep": "Залишити борги/баланси в пригоді"
    },
    "archived": "Заархівовано"
  },
  "zh-CN": {
    "members": {
      "title": "成员",
      "add": "添加成员",
      "empty": "这里还没有人。添加一些成员，开启冒险之旅吧。"
    },
    "editor": {
      "cover": "封面",
      "upload": "自行选择",
      "name": "冒险名称",
      "note": "所有成员都能看到此名字",
      "info": "冒险适合那些希望平等分担花费的人，无论是一起旅行、共同买单还是家庭开支。冒险中的债务不是个人之间的，而是所有成员共同分担，确保每个人的账目都公平。",
      "settings": "设置",
      "title": "新冒险"
    },
    "finish": {
      "archive": {
        "title": "完成冒险",
        "description": "将冒险归档后，它会从新增支出页面移除，并被移到你的冒险列表末尾。",
        "button": "归档冒险"
      },
      "delete": {
        "title": "删除冒险",
        "description": "还没有任何活动。快邀请朋友并添加一些支出，让一切开始运转吧。",
        "button": (title) => `删除${title}`
      }
    },
    "expenses": {
      "title": "支出",
      "total": "总计",
      "paidBy": "由...支付",
      "paid": "已支付"
    },
    "spending": {
      "yours": "你的支出",
      "total": "总支出"
    },
    "me": "我",
    "selector": {
      "regular": "定期支出"
    },
    "archive": {
      "header": (title, empty) => empty ? `正在删除${title}` : `正在归档${title}`,
      "delete": {
        "description": "该冒险没有任何费用，并将被删除",
        "button": "删除冒险"
      },
      "warning": "归档此冒险将是永久性的，无法撤销。"
    },
    "balance": {
      "header": "归档此冒险时：",
      "merge": "将债务移至普通成员债务",
      "keep": "将债务/余额保留在冒险中"
    },
    "archived": "已归档"
  }
};
/** @type {import("./types").Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];

