// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("./types").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "components": {
      "title": "المكونات",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "طيّ"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `عرض: ${count}`
      }
    },
    "loading": {
      "title": "شاشة التحميل"
    }
  },
  "de-DE": {
    "components": {
      "title": "Komponenten",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Einklappen"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Anzeigen: ${count}`
      }
    },
    "loading": {
      "title": "Ladebildschirm"
    }
  },
  "en-US": {
    "components": {
      "title": "Components",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Collapse"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Show: ${count}`
      }
    },
    "loading": {
      "title": "Loading screen"
    }
  },
  "es-ES": {
    "components": {
      "title": "Componentes",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Colapsar"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Mostrar: ${count}`
      }
    },
    "loading": {
      "title": "Pantalla de carga"
    }
  },
  "fr-FR": {
    "components": {
      "title": "Composants",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Réduire"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Afficher : ${count}`
      }
    },
    "loading": {
      "title": "Écran de chargement"
    }
  },
  "hi-IN": {
    "components": {
      "title": "घटक",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "संकुचित करें"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `${count} दिखाएं`
      }
    },
    "loading": {
      "title": "लोडिंग स्क्रीन"
    }
  },
  "it-IT": {
    "components": {
      "title": "Componenti",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Comprimi"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Mostra: ${count}`
      }
    },
    "loading": {
      "title": "Schermata di caricamento"
    }
  },
  "ja-JP": {
    "components": {
      "title": "コンポーネント",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "折りたたむ"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `${count}件を表示`
      }
    },
    "loading": {
      "title": "ロード画面"
    }
  },
  "ko-KR": {
    "components": {
      "title": "구성 요소",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "접기"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `${count}개 표시`
      }
    },
    "loading": {
      "title": "로딩 화면"
    }
  },
  "nl-NL": {
    "components": {
      "title": "Componenten",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Inklappen"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Tonen: ${count}`
      }
    },
    "loading": {
      "title": "Laadscherm"
    }
  },
  "ru-RU": {
    "components": {
      "title": "Компоненты",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Свернуть"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Показать: ${count}`
      }
    },
    "loading": {
      "title": "Экран загрузки"
    }
  },
  "sw-TZ": {
    "components": {
      "title": "Vipengele",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Ficha"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Onyesha: ${count}`
      }
    },
    "loading": {
      "title": "Skrini ya kupakia"
    }
  },
  "tr-TR": {
    "components": {
      "title": "Bileşenler",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Daralt"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `${count} göster`
      }
    },
    "loading": {
      "title": "Yükleme ekranı"
    }
  },
  "uk-UA": {
    "components": {
      "title": "Компоненти",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Згорнути"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Показати: ${count}`
      }
    },
    "loading": {
      "title": "Екран завантаження"
    }
  },
  "zh-CN": {
    "components": {
      "title": "组件",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "收起"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `显示：${count}`
      }
    },
    "loading": {
      "title": "加载界面"
    }
  }
};
/** @type {import("./types").Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];

