// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("./types").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "components": {
      "title": "المكونات",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "طيّ"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `عرض: ${count}`
      },
      "graph": {
        "title": "مخطط الديون"
      },
      "receipts": {
        "title": "الإيصالات",
        "upload": {
          "label": "تحميل"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "طلب إذن",
        "granted": "تم منح الإذن",
        "denied": "تم رفض الإذن",
        "unsupported": "غير مدعوم"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "شاشة التحميل"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "de-DE": {
    "components": {
      "title": "Komponenten",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Einklappen"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Anzeigen: ${count}`
      },
      "graph": {
        "title": "Schuldenübersicht"
      },
      "receipts": {
        "title": "Quittungen",
        "upload": {
          "label": "Hochladen"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Zugriffsanfrage",
        "granted": "Erlaubnis erteilt",
        "denied": "Zugriff verweigert",
        "unsupported": "Nicht unterstützt"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Ladebildschirm"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "en-US": {
    "components": {
      "title": "Components",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Collapse"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Show: ${count}`
      },
      "graph": {
        "title": "Debt Graph"
      },
      "receipts": {
        "title": "Receipts",
        "upload": {
          "label": "Upload"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Request permission",
        "granted": "Permission granted",
        "denied": "Permission denied",
        "unsupported": "Not supported"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Loading screen"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "es-ES": {
    "components": {
      "title": "Componentes",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Colapsar"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Mostrar: ${count}`
      },
      "graph": {
        "title": "Gráfico de deudas"
      },
      "receipts": {
        "title": "Recibos",
        "upload": {
          "label": "Subir"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Solicitar permiso",
        "granted": "Permiso concedido",
        "denied": "Permiso denegado",
        "unsupported": "No compatible"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Pantalla de carga"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "fr-FR": {
    "components": {
      "title": "Composants",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Réduire"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Afficher : ${count}`
      },
      "graph": {
        "title": "Graphique des dettes"
      },
      "receipts": {
        "title": "Reçus",
        "upload": {
          "label": "Téléverser"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Demander l'autorisation",
        "granted": "Autorisation accordée",
        "denied": "Autorisation refusée",
        "unsupported": "Non pris en charge"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Écran de chargement"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "hi-IN": {
    "components": {
      "title": "घटक",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "संकुचित करें"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `${count} दिखाएं`
      },
      "graph": {
        "title": "ऋण ग्राफ़"
      },
      "receipts": {
        "title": "रसीदें",
        "upload": {
          "label": "अपलोड करें"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "अनुमति अनुरोध करें",
        "granted": "अनुमति दी गई",
        "denied": "अनुमति अस्वीकृत",
        "unsupported": "समर्थित नहीं है"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "लोडिंग स्क्रीन"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "it-IT": {
    "components": {
      "title": "Componenti",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Comprimi"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Mostra: ${count}`
      },
      "graph": {
        "title": "Grafico dei debiti"
      },
      "receipts": {
        "title": "Scontrini",
        "upload": {
          "label": "Carica"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Richiedi autorizzazione",
        "granted": "Autorizzazione concessa",
        "denied": "Autorizzazione negata",
        "unsupported": "Non supportato"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Schermata di caricamento"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "ja-JP": {
    "components": {
      "title": "コンポーネント",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "折りたたむ"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `${count}件を表示`
      },
      "graph": {
        "title": "債務グラフ"
      },
      "receipts": {
        "title": "レシート",
        "upload": {
          "label": "アップロード"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "許可をリクエスト",
        "granted": "許可されました",
        "denied": "権限がありません",
        "unsupported": "サポートされていません"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "ロード画面"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "ko-KR": {
    "components": {
      "title": "구성 요소",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "접기"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `${count}개 표시`
      },
      "graph": {
        "title": "부채 그래프"
      },
      "receipts": {
        "title": "영수증",
        "upload": {
          "label": "업로드"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "권한 요청",
        "granted": "권한이 부여되었습니다",
        "denied": "권한이 거부되었습니다",
        "unsupported": "지원되지 않음"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "로딩 화면"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "nl-NL": {
    "components": {
      "title": "Componenten",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Inklappen"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Tonen: ${count}`
      },
      "graph": {
        "title": "Schuldenoverzicht"
      },
      "receipts": {
        "title": "Bonnetjes",
        "upload": {
          "label": "Uploaden"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Toestemming aanvragen",
        "granted": "Toestemming verleend",
        "denied": "Toestemming geweigerd",
        "unsupported": "Niet ondersteund"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Laadscherm"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "ru-RU": {
    "components": {
      "title": "Компоненты",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Свернуть"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Показать: ${count}`
      },
      "graph": {
        "title": "График долгов"
      },
      "receipts": {
        "title": "Чеки",
        "upload": {
          "label": "Загрузить"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Запросить разрешение",
        "granted": "Разрешение предоставлено",
        "denied": "Доступ запрещён",
        "unsupported": "Не поддерживается"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Экран загрузки"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "sw-TZ": {
    "components": {
      "title": "Vipengele",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Ficha"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Onyesha: ${count}`
      },
      "graph": {
        "title": "Chati ya Madeni"
      },
      "receipts": {
        "title": "Risiti",
        "upload": {
          "label": "Pakia"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Omba ruhusa",
        "granted": "Ruhusa imetolewa",
        "denied": "Ruhusa imekataliwa",
        "unsupported": "Haijaungwa mkono"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Skrini ya kupakia"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "tr-TR": {
    "components": {
      "title": "Bileşenler",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Daralt"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `${count} göster`
      },
      "graph": {
        "title": "Borç Grafiği"
      },
      "receipts": {
        "title": "Fişler",
        "upload": {
          "label": "Yükle"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "İzin iste",
        "granted": "İzin verildi",
        "denied": "İzin reddedildi",
        "unsupported": "Desteklenmiyor"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Yükleme ekranı"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "uk-UA": {
    "components": {
      "title": "Компоненти",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Згорнути"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Показати: ${count}`
      },
      "graph": {
        "title": "Графік боргів"
      },
      "receipts": {
        "title": "Чеки",
        "upload": {
          "label": "Завантажити"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Запит на дозвіл",
        "granted": "Дозвіл надано",
        "denied": "Доступ заборонено",
        "unsupported": "Не підтримується"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Екран завантаження"
    },
    "receipts": {
      "upload": {

      }
    }
  },
  "zh-CN": {
    "components": {
      "title": "组件",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "收起"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `显示：${count}`
      },
      "graph": {
        "title": "债务图表"
      },
      "receipts": {
        "title": "小票",
        "upload": {
          "label": "上传"
        }
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "请求权限",
        "granted": "已授予权限",
        "denied": "权限被拒绝",
        "unsupported": "不受支持"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "加载界面"
    },
    "receipts": {
      "upload": {

      }
    }
  }
};
/** @type {import("./types").Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];

