// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("./types").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "components": {
      "title": "المكونات",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "طيّ"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `عرض: ${count}`
      },
      "graph": {
        "title": "مخطط الديون"
      },
      "receipts": {
        "title": "الإيصالات",
        "upload": {
          "label": "تحميل"
        },
        "progress": {
          "uploading": {
            "title": "جارٍ الرفع",
            "comment": "يستغرق الأمر عادة بضع لحظات"
          },
          "processing": {
            "comment": "تمسك جيدًا، أوشكنا على الوصول",
            "title": "جارٍ المعالجة"
          },
          "ready": {
            "title": "جاهز",
            "comment": (ms) => `تم في ${(ms / 1000).toFixed(1)} ثانية`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "المشاركون",
        "managedContactsCreation": "عرض زر إنشاء جهات الاتصال المُدارة",
        "shareUrl": "مشاركة الرابط"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "أضف مرفقًا إلى أي مصروف",
        "delete": "اضغط مطولًا للحذف"
      },
      "invitation": {
        "title": "الدعوات"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "طلب إذن",
        "granted": "تم منح الإذن",
        "denied": "تم رفض الإذن",
        "unsupported": "غير مدعوم"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "شاشة التحميل"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "منطقة الإسقاط"
      }
    },
    "actions": {
      "continue": "متابعة"
    },
    "nav": {
      "home": "الرئيسية",
      "components": "المكوّنات",
      "transmission": "ناقل الحركة",
      "app": "التطبيق"
    }
  },
  "de-DE": {
    "components": {
      "title": "Komponenten",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Einklappen"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Anzeigen: ${count}`
      },
      "graph": {
        "title": "Schuldenübersicht"
      },
      "receipts": {
        "title": "Quittungen",
        "upload": {
          "label": "Hochladen"
        },
        "progress": {
          "uploading": {
            "title": "Wird hochgeladen",
            "comment": "Dauert normalerweise nur wenige Augenblicke"
          },
          "processing": {
            "comment": "Halte durch, gleich sind wir da",
            "title": "Wird verarbeitet"
          },
          "ready": {
            "title": "Bereit",
            "comment": (ms) => `Fertig in ${(ms / 1000).toFixed(1)} Sekunden`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "Teilnehmende",
        "managedContactsCreation": "Button zum Erstellen verwalteter Kontakte anzeigen",
        "shareUrl": "URL teilen"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "Füge einen Anhang zu einer beliebigen Ausgabe hinzu",
        "delete": "Zum Löschen halten"
      },
      "invitation": {
        "title": "Einladungen"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Zugriffsanfrage",
        "granted": "Erlaubnis erteilt",
        "denied": "Zugriff verweigert",
        "unsupported": "Nicht unterstützt"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Ladebildschirm"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "Ablagebereich"
      }
    },
    "actions": {
      "continue": "Weiter"
    },
    "nav": {
      "home": "Startseite",
      "components": "Komponenten",
      "transmission": "Getriebe",
      "app": "App"
    }
  },
  "en-US": {
    "components": {
      "title": "Components",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Collapse"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Show: ${count}`
      },
      "graph": {
        "title": "Debt Graph"
      },
      "receipts": {
        "title": "Receipts",
        "upload": {
          "label": "Upload"
        },
        "progress": {
          "uploading": {
            "title": "Uploading",
            "comment": "Usually takes a few moments"
          },
          "processing": {
            "comment": "Hang tight, almost there",
            "title": "Processing"
          },
          "ready": {
            "title": "Ready",
            "comment": (ms) => `Done in ${(ms / 1000).toFixed(1)} seconds`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "Participants",
        "managedContactsCreation": "Show managed contacts creation button",
        "shareUrl": "Share URL"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "Add an attachment to any expense",
        "delete": "Hold to delete"
      },
      "invitation": {
        "title": "Invitations"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Request permission",
        "granted": "Permission granted",
        "denied": "Permission denied",
        "unsupported": "Not supported"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Loading screen"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "Dropzone"
      }
    },
    "actions": {
      "continue": "Continue"
    },
    "nav": {
      "home": "Home",
      "components": "Components",
      "transmission": "Transmission",
      "app": "App"
    }
  },
  "es-ES": {
    "components": {
      "title": "Componentes",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Colapsar"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Mostrar: ${count}`
      },
      "graph": {
        "title": "Gráfico de deudas"
      },
      "receipts": {
        "title": "Recibos",
        "upload": {
          "label": "Subir"
        },
        "progress": {
          "uploading": {
            "title": "Subiendo",
            "comment": "Normalmente tarda unos momentos"
          },
          "processing": {
            "comment": "Aguanta, ya casi llegamos",
            "title": "Procesando"
          },
          "ready": {
            "title": "Listo",
            "comment": (ms) => `Listo en ${(ms / 1000).toFixed(1)} segundos`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "Participantes",
        "managedContactsCreation": "Mostrar botón para crear contactos gestionados",
        "shareUrl": "Compartir URL"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "Añade un archivo adjunto a cualquier gasto",
        "delete": "Mantén pulsado para borrar"
      },
      "invitation": {
        "title": "Invitaciones"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Solicitar permiso",
        "granted": "Permiso concedido",
        "denied": "Permiso denegado",
        "unsupported": "No compatible"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Pantalla de carga"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "Zona de arrastre"
      }
    },
    "actions": {
      "continue": "Continuar"
    },
    "nav": {
      "home": "Inicio",
      "components": "Componentes",
      "transmission": "Transmisión",
      "app": "App"
    }
  },
  "fr-FR": {
    "components": {
      "title": "Composants",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Réduire"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Afficher : ${count}`
      },
      "graph": {
        "title": "Graphique des dettes"
      },
      "receipts": {
        "title": "Reçus",
        "upload": {
          "label": "Téléverser"
        },
        "progress": {
          "uploading": {
            "title": "Téléchargement en cours",
            "comment": "Cela prend généralement quelques instants"
          },
          "processing": {
            "comment": "Accroche-toi, on y est presque",
            "title": "Traitement en cours"
          },
          "ready": {
            "title": "Prêt",
            "comment": (ms) => `Terminé en ${(ms / 1000).toFixed(1)} secondes`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "Participants",
        "managedContactsCreation": "Afficher le bouton de création de contacts gérés",
        "shareUrl": "Partager l’URL"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "Ajoute une pièce jointe à n’importe quelle dépense",
        "delete": "Maintiens pour supprimer"
      },
      "invitation": {
        "title": "Invitations"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Demander l'autorisation",
        "granted": "Autorisation accordée",
        "denied": "Autorisation refusée",
        "unsupported": "Non pris en charge"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Écran de chargement"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "Zone de dépôt"
      }
    },
    "actions": {
      "continue": "Continuer"
    },
    "nav": {
      "home": "Accueil",
      "components": "Composants",
      "transmission": "Transmission",
      "app": "Appli"
    }
  },
  "hi-IN": {
    "components": {
      "title": "घटक",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "संकुचित करें"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `${count} दिखाएं`
      },
      "graph": {
        "title": "ऋण ग्राफ़"
      },
      "receipts": {
        "title": "रसीदें",
        "upload": {
          "label": "अपलोड करें"
        },
        "progress": {
          "uploading": {
            "title": "अपलोड किया जा रहा है",
            "comment": "आम तौर पर कुछ क्षण लगते हैं"
          },
          "processing": {
            "comment": "बस थोड़ा रुकिए, हम लगभग पहुँच गए हैं",
            "title": "प्रोसेस हो रहा है"
          },
          "ready": {
            "title": "तैयार",
            "comment": (ms) => `${(ms / 1000).toFixed(1)} सेकंड में पूरा हुआ`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "प्रतिभागी",
        "managedContactsCreation": "प्रबंधित संपर्क निर्माण बटन दिखाएं",
        "shareUrl": "URL साझा करें"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "किसी भी खर्च में अटैचमेंट जोड़ो",
        "delete": "हटाने के लिए दबाए रखें"
      },
      "invitation": {
        "title": "निमंत्रण"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "अनुमति अनुरोध करें",
        "granted": "अनुमति दी गई",
        "denied": "अनुमति अस्वीकृत",
        "unsupported": "समर्थित नहीं है"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "लोडिंग स्क्रीन"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "ड्रॉप ज़ोन"
      }
    },
    "actions": {
      "continue": "जारी रखें"
    },
    "nav": {
      "home": "होम",
      "components": "कॉम्पोनेंट्स",
      "transmission": "ट्रांसमिशन",
      "app": "ऐप"
    }
  },
  "it-IT": {
    "components": {
      "title": "Componenti",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Comprimi"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Mostra: ${count}`
      },
      "graph": {
        "title": "Grafico dei debiti"
      },
      "receipts": {
        "title": "Scontrini",
        "upload": {
          "label": "Carica"
        },
        "progress": {
          "uploading": {
            "title": "Caricamento in corso",
            "comment": "Di solito ci vogliono pochi istanti"
          },
          "processing": {
            "comment": "Resisti, ci siamo quasi",
            "title": "Elaborazione in corso"
          },
          "ready": {
            "title": "Pronto",
            "comment": (ms) => `Fatto in ${(ms / 1000).toFixed(1)} secondi`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "Partecipanti",
        "managedContactsCreation": "Mostra il pulsante per creare contatti gestiti",
        "shareUrl": "Condividi URL"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "Aggiungi un allegato a qualsiasi spesa",
        "delete": "Tieni premuto per eliminare"
      },
      "invitation": {
        "title": "Inviti"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Richiedi autorizzazione",
        "granted": "Autorizzazione concessa",
        "denied": "Autorizzazione negata",
        "unsupported": "Non supportato"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Schermata di caricamento"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "Area di rilascio"
      }
    },
    "actions": {
      "continue": "Continua"
    },
    "nav": {
      "home": "Home",
      "components": "Componenti",
      "transmission": "Trasmissione",
      "app": "App"
    }
  },
  "ja-JP": {
    "components": {
      "title": "コンポーネント",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "折りたたむ"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `${count}件を表示`
      },
      "graph": {
        "title": "債務グラフ"
      },
      "receipts": {
        "title": "レシート",
        "upload": {
          "label": "アップロード"
        },
        "progress": {
          "uploading": {
            "title": "アップロード中",
            "comment": "通常は数瞬で完了します"
          },
          "processing": {
            "comment": "もう少しで到着です、頑張ってください",
            "title": "処理中"
          },
          "ready": {
            "title": "準備完了",
            "comment": (ms) => `${(ms / 1000).toFixed(1)}秒で完了`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "参加者",
        "managedContactsCreation": "管理対象の連絡先作成ボタンを表示",
        "shareUrl": "URLを共有"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "どの支出にも添付ファイルを追加しよう",
        "delete": "長押しで削除"
      },
      "invitation": {
        "title": "招待"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "許可をリクエスト",
        "granted": "許可されました",
        "denied": "権限がありません",
        "unsupported": "サポートされていません"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "ロード画面"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "ドロップゾーン"
      }
    },
    "actions": {
      "continue": "続行"
    },
    "nav": {
      "home": "ホーム",
      "components": "コンポーネント",
      "transmission": "トランスミッション",
      "app": "アプリ"
    }
  },
  "ko-KR": {
    "components": {
      "title": "구성 요소",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "접기"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `${count}개 표시`
      },
      "graph": {
        "title": "부채 그래프"
      },
      "receipts": {
        "title": "영수증",
        "upload": {
          "label": "업로드"
        },
        "progress": {
          "uploading": {
            "title": "업로드 중",
            "comment": "보통 잠시만 걸립니다"
          },
          "processing": {
            "comment": "조금만 참아 주세요, 거의 다 왔어요",
            "title": "처리 중"
          },
          "ready": {
            "title": "준비 완료",
            "comment": (ms) => `${(ms / 1000).toFixed(1)}초 만에 완료됨`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "참가자",
        "managedContactsCreation": "관리되는 연락처 생성 버튼 표시",
        "shareUrl": "URL 공유"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "어느 지출에나 첨부파일을 추가해봐",
        "delete": "길게 눌러서 삭제"
      },
      "invitation": {
        "title": "초대장"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "권한 요청",
        "granted": "권한이 부여되었습니다",
        "denied": "권한이 거부되었습니다",
        "unsupported": "지원되지 않음"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "로딩 화면"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "드롭존"
      }
    },
    "actions": {
      "continue": "계속"
    },
    "nav": {
      "home": "홈",
      "components": "컴포넌트",
      "transmission": "변속기",
      "app": "앱"
    }
  },
  "nl-NL": {
    "components": {
      "title": "Componenten",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Inklappen"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Tonen: ${count}`
      },
      "graph": {
        "title": "Schuldenoverzicht"
      },
      "receipts": {
        "title": "Bonnetjes",
        "upload": {
          "label": "Uploaden"
        },
        "progress": {
          "uploading": {
            "title": "Bezig met uploaden",
            "comment": "Duurt meestal slechts een paar momenten"
          },
          "processing": {
            "comment": "Hou vol, we zijn er bijna",
            "title": "Bezig met verwerken"
          },
          "ready": {
            "title": "Klaar",
            "comment": (ms) => `Klaar in ${(ms / 1000).toFixed(1)} seconden`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "Deelnemers",
        "managedContactsCreation": "Knop voor het aanmaken van beheerde contacten tonen",
        "shareUrl": "URL delen"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "Voeg een bijlage toe aan een willekeurige uitgave",
        "delete": "Vasthouden om te verwijderen"
      },
      "invitation": {
        "title": "Uitnodigingen"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Toestemming aanvragen",
        "granted": "Toestemming verleend",
        "denied": "Toestemming geweigerd",
        "unsupported": "Niet ondersteund"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Laadscherm"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "Dropzone"
      }
    },
    "actions": {
      "continue": "Doorgaan"
    },
    "nav": {
      "home": "Startpagina",
      "components": "Componenten",
      "transmission": "Transmissie",
      "app": "App"
    }
  },
  "ru-RU": {
    "components": {
      "title": "Компоненты",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Свернуть"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Показать: ${count}`
      },
      "graph": {
        "title": "График долгов"
      },
      "receipts": {
        "title": "Чеки",
        "upload": {
          "label": "Загрузить"
        },
        "progress": {
          "uploading": {
            "title": "Загрузка",
            "comment": "Обычно занимает несколько секунд"
          },
          "processing": {
            "comment": "Потерпи, почти пришли",
            "title": "Обработка"
          },
          "ready": {
            "title": "Готово",
            "comment": (ms) => `Готово за ${(ms / 1000).toFixed(1)} секунд(ы)`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "Участники",
        "managedContactsCreation": "Показать кнопку создания управляемых контактов",
        "shareUrl": "Поделиться ссылкой"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "Добавь вложение к любому расходу",
        "delete": "Удерживай, чтобы удалить"
      },
      "invitation": {
        "title": "Приглашения"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Запросить разрешение",
        "granted": "Разрешение предоставлено",
        "denied": "Доступ запрещён",
        "unsupported": "Не поддерживается"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Экран загрузки"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "Зона для загрузки"
      }
    },
    "actions": {
      "continue": "Продолжить"
    },
    "nav": {
      "home": "Главная",
      "components": "Компоненты",
      "transmission": "Трансмиссия",
      "app": "Приложение"
    }
  },
  "sw-TZ": {
    "components": {
      "title": "Vipengele",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Ficha"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Onyesha: ${count}`
      },
      "graph": {
        "title": "Chati ya Madeni"
      },
      "receipts": {
        "title": "Risiti",
        "upload": {
          "label": "Pakia"
        },
        "progress": {
          "uploading": {
            "title": "Inapakia",
            "comment": "Kwa kawaida huchukua muda mfupi tu"
          },
          "processing": {
            "comment": "Shikilia, tumebakiza kidogo tu",
            "title": "Inashughulikiwa"
          },
          "ready": {
            "title": "Tayari",
            "comment": (ms) => `Imekamilika kwa sekunde ${(ms / 1000).toFixed(1)}`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "Washiriki",
        "managedContactsCreation": "Onyesha kitufe cha kuunda mawasiliano yanayosimamiwa",
        "shareUrl": "Shiriki URL"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "Ongeza kiambatisho kwenye gharama yoyote",
        "delete": "Shikilia kufuta"
      },
      "invitation": {
        "title": "Mialiko"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Omba ruhusa",
        "granted": "Ruhusa imetolewa",
        "denied": "Ruhusa imekataliwa",
        "unsupported": "Haijaungwa mkono"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Skrini ya kupakia"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "Eneo la kutupia"
      }
    },
    "actions": {
      "continue": "Endelea"
    },
    "nav": {
      "home": "Mwanzo",
      "components": "Vijenzi",
      "transmission": "Gia",
      "app": "App"
    }
  },
  "tr-TR": {
    "components": {
      "title": "Bileşenler",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Daralt"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `${count} göster`
      },
      "graph": {
        "title": "Borç Grafiği"
      },
      "receipts": {
        "title": "Fişler",
        "upload": {
          "label": "Yükle"
        },
        "progress": {
          "uploading": {
            "title": "Yükleniyor",
            "comment": "Genellikle birkaç saniye sürer"
          },
          "processing": {
            "comment": "Biraz daha sabret, neredeyse geldik",
            "title": "İşleniyor"
          },
          "ready": {
            "title": "Hazır",
            "comment": (ms) => `${(ms / 1000).toFixed(1)} saniyede tamamlandı`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "Katılımcılar",
        "managedContactsCreation": "Yönetilen kişiler oluşturma butonunu göster",
        "shareUrl": "URL’yi paylaş"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "Herhangi bir harcamaya ek dosya ekle",
        "delete": "Silmek için basılı tut"
      },
      "invitation": {
        "title": "Davetiyeler"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "İzin iste",
        "granted": "İzin verildi",
        "denied": "İzin reddedildi",
        "unsupported": "Desteklenmiyor"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Yükleme ekranı"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "Bırakma alanı"
      }
    },
    "actions": {
      "continue": "Devam et"
    },
    "nav": {
      "home": "Ana Sayfa",
      "components": "Bileşenler",
      "transmission": "Şanzıman",
      "app": "Uygulama"
    }
  },
  "uk-UA": {
    "components": {
      "title": "Компоненти",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "Згорнути"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `Показати: ${count}`
      },
      "graph": {
        "title": "Графік боргів"
      },
      "receipts": {
        "title": "Чеки",
        "upload": {
          "label": "Завантажити"
        },
        "progress": {
          "uploading": {
            "title": "Завантаження",
            "comment": "Зазвичай це займає кілька секунд"
          },
          "processing": {
            "comment": "Тримайся, вже майже на місці",
            "title": "Обробка"
          },
          "ready": {
            "title": "Готово",
            "comment": (ms) => `Виконано за ${(ms / 1000).toFixed(1)} секунд(и)`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "Учасники",
        "managedContactsCreation": "Показати кнопку створення керованих контактів",
        "shareUrl": "Поділитися посиланням"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "Додай вкладення до будь-якої витрати",
        "delete": "Утримуй, щоб видалити"
      },
      "invitation": {
        "title": "Запрошення"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "Запит на дозвіл",
        "granted": "Дозвіл надано",
        "denied": "Доступ заборонено",
        "unsupported": "Не підтримується"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "Екран завантаження"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "Зона для перетягування"
      }
    },
    "actions": {
      "continue": "Продовжити"
    },
    "nav": {
      "home": "Головна",
      "components": "Компоненти",
      "transmission": "Трансмісія",
      "app": "Застосунок"
    }
  },
  "zh-CN": {
    "components": {
      "title": "组件",
      "hold": {
        "title": "Hold"
      },
      "stack": {
        "title": "Stack",
        "collapse": "收起"
      },
      "notifications": {
        "title": "Notifications",
        "display": (count) => `显示：${count}`
      },
      "graph": {
        "title": "债务图表"
      },
      "receipts": {
        "title": "小票",
        "upload": {
          "label": "上传"
        },
        "progress": {
          "uploading": {
            "title": "正在上传",
            "comment": "通常只需几秒钟"
          },
          "processing": {
            "comment": "坚持一下，马上就到了",
            "title": "处理中"
          },
          "ready": {
            "title": "已准备好",
            "comment": (ms) => `${(ms / 1000).toFixed(1)} 秒内完成`
          }
        }
      },
      "picture": {
        "title": "Picture"
      },
      "participants": {
        "title": "参与者",
        "managedContactsCreation": "显示托管联系人创建按钮",
        "shareUrl": "分享链接"
      },
      "fullscreen": {
        "title": "Fullscreen",
        "attachment": "给任意一笔支出添加附件",
        "delete": "长按删除"
      },
      "invitation": {
        "title": "邀请"
      }
    },
    "transmission": {
      "title": "Transmission",
      "permission": {
        "request": "请求权限",
        "granted": "已授予权限",
        "denied": "权限被拒绝",
        "unsupported": "不受支持"
      },
      "ping": "Ping"
    },
    "loading": {
      "title": "加载界面"
    },
    "receipts": {
      "upload": {

      },
      "dropzone": {
        "label": "拖放区"
      }
    },
    "actions": {
      "continue": "继续"
    },
    "nav": {
      "home": "首页",
      "components": "组件",
      "transmission": "变速器",
      "app": "应用"
    }
  }
};
/** @type {import("./types").Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];

