// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "en-US": {
    "native": "English",
    "locale": "en-US",
    "actions": {
      "continue": "Continue"
    }
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["en-US"];
