// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "native": "العربية",
    "locale": "ar-SA",
    "actions": {
      "continue": "متابعة",
      "holdToLogout": "اضغط مطولًا لتسجيل الخروج",
      "signout": "تسجيل الخروج"
    },
    "nav": {
      "home": "الرئيسية",
      "evns": "تسوية",
      "profile": "أنا",
      "contacts": "الأصدقاء"
    },
    "terms": "الشروط والأحكام",
    "privacy": "سياسة الخصوصية",
    "madeBy": "من صنع",
    "profile": {
      "title": "ملفي الشخصي",
      "language": {
        "title": "اللغة",
        "description": "هذا لا يؤثر على التعرف على الشيك. على أي حال، نحن نفهم معظم اللغات هناك."
      }
    },
    "form": {
      "enterName": "أدخل الاسم"
    },
    "copyright": "© Seed.me، 2024-2025",
    "onboarding": {
      "name": {
        "title": "لمسة شخصية",
        "description": "اسمك كما سيظهر"
      }
    },
    "contacts": {
      "title": "الأصدقاء",
      "empty": {
        "title": "المكان هنا موحش",
        "description": "أضِف الأصدقاء يدويًا أو ادعُ الأشخاص",
        "invite": {
          "share": "دعوة الأصدقاء",
          "qr": "دعوة عبر رمز الاستجابة السريعة"
        }
      }
    }
  },
  "de-DE": {
    "native": "Deutsch",
    "locale": "de-DE",
    "actions": {
      "continue": "Weiter",
      "holdToLogout": "Zum Abmelden gedrückt halten",
      "signout": "Abmelden"
    },
    "nav": {
      "home": "Startseite",
      "evns": "Ausgleich",
      "profile": "Ich",
      "contacts": "Freunde"
    },
    "terms": "Allgemeine Geschäftsbedingungen",
    "privacy": "Datenschutzerklärung",
    "madeBy": "Erstellt von",
    "profile": {
      "title": "Mein Profil",
      "language": {
        "title": "Sprache",
        "description": "Das beeinflusst die Scheck-Erkennung nicht. Wir verstehen dort ohnehin die meisten Sprachen."
      }
    },
    "form": {
      "enterName": "Name eingeben"
    },
    "copyright": "© Seed.me, 2024–2025",
    "onboarding": {
      "name": {
        "title": "Persönliche Note",
        "description": "Ihr Name, wie er angezeigt wird"
      }
    },
    "contacts": {
      "title": "Freunde",
      "empty": {
        "title": "Hier ist es einsam",
        "description": "Freunde manuell hinzufügen oder Personen einladen",
        "invite": {
          "share": "Freunde einladen",
          "qr": "Per QR-Code einladen"
        }
      }
    }
  },
  "en-US": {
    "native": "English",
    "locale": "en-US",
    "actions": {
      "continue": "Continue",
      "holdToLogout": "Hold to log out",
      "signout": "Sign out"
    },
    "nav": {
      "home": "Home",
      "evns": "Evns",
      "profile": "Me",
      "contacts": "Friends"
    },
    "terms": "Terms & Conditions",
    "privacy": "Privacy Policy",
    "madeBy": "Made by",
    "profile": {
      "title": "My Profile",
      "language": {
        "title": "Language",
        "description": "This does not affect cheque recognition. We understand most languages there anyway."
      }
    },
    "form": {
      "enterName": "Enter name"
    },
    "copyright": "© Seed.me, 2024-2025",
    "onboarding": {
      "name": {
        "title": "Personal Touch",
        "description": "Your name as it will appear"
      }
    },
    "contacts": {
      "title": "Friends",
      "empty": {
        "title": "It's lonely here",
        "description": "Add friends manually or invite people",
        "invite": {
          "share": "Invite friends",
          "qr": "Invite by QR code"
        }
      }
    }
  },
  "es-ES": {
    "native": "Español",
    "locale": "es-ES",
    "actions": {
      "continue": "Continuar",
      "holdToLogout": "Mantén pulsado para cerrar sesión",
      "signout": "Cerrar sesión"
    },
    "nav": {
      "home": "Inicio",
      "evns": "Ajustes",
      "profile": "Yo",
      "contacts": "Amigos"
    },
    "terms": "Términos y condiciones",
    "privacy": "Política de privacidad",
    "madeBy": "Hecho por",
    "profile": {
      "title": "Mi perfil",
      "language": {
        "title": "Idioma",
        "description": "Esto no afecta al reconocimiento de cheques. De todas formas, entendemos la mayoría de los idiomas allí."
      }
    },
    "form": {
      "enterName": "Introduce el nombre"
    },
    "copyright": "© Seed.me, 2024-2025",
    "onboarding": {
      "name": {
        "title": "Toque personal",
        "description": "Tu nombre tal como se verá"
      }
    },
    "contacts": {
      "title": "Amigos",
      "empty": {
        "title": "Aquí está solitario",
        "description": "Añade amigos manualmente o invita a personas",
        "invite": {
          "share": "Invitar a amigos",
          "qr": "Invitar por código QR"
        }
      }
    }
  },
  "fr-FR": {
    "native": "Français",
    "locale": "fr-FR",
    "actions": {
      "continue": "Continuer",
      "holdToLogout": "Maintenez pour vous déconnecter",
      "signout": "Se déconnecter"
    },
    "nav": {
      "home": "Accueil",
      "evns": "Règlements",
      "profile": "Moi",
      "contacts": "Amis"
    },
    "terms": "Conditions générales",
    "privacy": "Politique de confidentialité",
    "madeBy": "Créé par",
    "profile": {
      "title": "Mon profil",
      "language": {
        "title": "Langue",
        "description": "Cela n’affecte pas la reconnaissance des chèques. Nous comprenons de toute façon la plupart des langues là-bas."
      }
    },
    "form": {
      "enterName": "Saisissez le nom"
    },
    "copyright": "© Seed.me, 2024-2025",
    "onboarding": {
      "name": {
        "title": "Touche personnelle",
        "description": "Votre nom tel qu'il sera affiché"
      }
    },
    "contacts": {
      "title": "Amis",
      "empty": {
        "title": "C'est désert ici",
        "description": "Ajoutez des amis manuellement ou invitez des personnes",
        "invite": {
          "share": "Inviter des amis",
          "qr": "Inviter par QR code"
        }
      }
    }
  },
  "hi-IN": {
    "native": "हिन्दी",
    "locale": "hi-IN",
    "actions": {
      "continue": "जारी रखें",
      "holdToLogout": "लॉगआउट के लिए दबाए रखें",
      "signout": "साइन आउट करें"
    },
    "nav": {
      "home": "मुख्य पृष्ठ",
      "evns": "सेटलमेंट",
      "profile": "मैं",
      "contacts": "मित्र"
    },
    "terms": "नियम और शर्तें",
    "privacy": "गोपनीयता नीति",
    "madeBy": "द्वारा निर्मित",
    "profile": {
      "title": "मेरा प्रोफ़ाइल",
      "language": {
        "title": "भाषा",
        "description": "यह चेक की पहचान को प्रभावित नहीं करता है। वैसे भी, हम वहां अधिकांश भाषाओं को समझते हैं।"
      }
    },
    "form": {
      "enterName": "नाम दर्ज करें"
    },
    "copyright": "© Seed.me, 2024-2025",
    "onboarding": {
      "name": {
        "title": "व्यक्तिगत स्पर्श",
        "description": "आपका नाम जैसा दिखाई देगा"
      }
    },
    "contacts": {
      "title": "दोस्त",
      "empty": {
        "title": "यहाँ अकेलापन है",
        "description": "दोस्तों को मैन्युअली जोड़ें या लोगों को आमंत्रित करें",
        "invite": {
          "share": "दोस्तों को आमंत्रित करें",
          "qr": "QR कोड से आमंत्रित करें"
        }
      }
    }
  },
  "it-IT": {
    "native": "Italiano",
    "locale": "it-IT",
    "actions": {
      "continue": "Continua",
      "holdToLogout": "Tieni premuto per uscire",
      "signout": "Esci"
    },
    "nav": {
      "home": "Home",
      "evns": "Saldo",
      "profile": "Io",
      "contacts": "Amici"
    },
    "terms": "Termini e condizioni",
    "privacy": "Informativa sulla privacy",
    "madeBy": "Realizzato da",
    "profile": {
      "title": "Il mio profilo",
      "language": {
        "title": "Lingua",
        "description": "Questo non influisce sul riconoscimento dell'assegno. Comunque, lì capiamo la maggior parte delle lingue."
      }
    },
    "form": {
      "enterName": "Inserisci il nome"
    },
    "copyright": "© Seed.me, 2024-2025",
    "onboarding": {
      "name": {
        "title": "Tocco personale",
        "description": "Il tuo nome come verrà visualizzato"
      }
    },
    "contacts": {
      "title": "Amici",
      "empty": {
        "title": "È solitario qui",
        "description": "Aggiungi amici manualmente o invita persone",
        "invite": {
          "share": "Invita amici",
          "qr": "Invita tramite codice QR"
        }
      }
    }
  },
  "ja-JP": {
    "native": "日本語",
    "locale": "ja-JP",
    "actions": {
      "continue": "続ける",
      "holdToLogout": "長押ししてログアウト",
      "signout": "サインアウト"
    },
    "nav": {
      "home": "ホーム",
      "evns": "清算",
      "profile": "私",
      "contacts": "友だち"
    },
    "terms": "利用規約",
    "privacy": "プライバシーポリシー",
    "madeBy": "作成者",
    "profile": {
      "title": "マイプロフィール",
      "language": {
        "title": "言語",
        "description": "これは小切手の認識には影響しません。そもそも、私たちはほとんどの言語を理解しています。"
      }
    },
    "form": {
      "enterName": "名前を入力してください"
    },
    "copyright": "© Seed.me, 2024年～2025年",
    "onboarding": {
      "name": {
        "title": "パーソナルタッチ",
        "description": "表示されるあなたの名前"
      }
    },
    "contacts": {
      "title": "友達",
      "empty": {
        "title": "ここは寂しいです",
        "description": "友達を手動で追加するか、招待する",
        "invite": {
          "share": "友達を招待する",
          "qr": "QRコードで招待"
        }
      }
    }
  },
  "ko-KR": {
    "native": "한국어",
    "locale": "ko-KR",
    "actions": {
      "continue": "계속",
      "holdToLogout": "길게 눌러 로그아웃",
      "signout": "로그아웃"
    },
    "nav": {
      "home": "홈",
      "evns": "정산",
      "profile": "나",
      "contacts": "친구"
    },
    "terms": "이용 약관",
    "privacy": "개인정보 처리방침",
    "madeBy": "제작자",
    "profile": {
      "title": "내 프로필",
      "language": {
        "title": "언어",
        "description": "이는 수표 인식에 영향을 주지 않습니다. 어차피 저희는 대부분의 언어를 이해합니다."
      }
    },
    "form": {
      "enterName": "이름을 입력하세요"
    },
    "copyright": "© Seed.me, 2024-2025",
    "onboarding": {
      "name": {
        "title": "개인적인 터치",
        "description": "표시될 이름"
      }
    },
    "contacts": {
      "title": "친구",
      "empty": {
        "title": "여기는 외로워요",
        "description": "친구를 직접 추가하거나 사람들을 초대하세요",
        "invite": {
          "share": "친구 초대하기",
          "qr": "QR 코드로 초대"
        }
      }
    }
  },
  "nl-NL": {
    "native": "Nederlands",
    "locale": "nl-NL",
    "actions": {
      "continue": "Doorgaan",
      "holdToLogout": "Ingedrukt houden om uit te loggen",
      "signout": "Afmelden"
    },
    "nav": {
      "home": "Home",
      "evns": "Afrekening",
      "profile": "Ik",
      "contacts": "Vrienden"
    },
    "terms": "Algemene voorwaarden",
    "privacy": "Privacybeleid",
    "madeBy": "Gemaakt door",
    "profile": {
      "title": "Mijn profiel",
      "language": {
        "title": "Taal",
        "description": "Dit heeft geen invloed op de chequedetectie. We begrijpen daar toch de meeste talen."
      }
    },
    "form": {
      "enterName": "Naam invoeren"
    },
    "copyright": "© Seed.me, 2024-2025",
    "onboarding": {
      "name": {
        "title": "Persoonlijk tintje",
        "description": "Je naam zoals die getoond zal worden"
      }
    },
    "contacts": {
      "title": "Vrienden",
      "empty": {
        "title": "Het is hier verlaten",
        "description": "Voeg vrienden handmatig toe of nodig mensen uit",
        "invite": {
          "share": "Vrienden uitnodigen",
          "qr": "Uitnodigen via QR-code"
        }
      }
    }
  },
  "ru-RU": {
    "native": "Русский",
    "locale": "ru-RU",
    "actions": {
      "continue": "Продолжить",
      "holdToLogout": "Удерживайте для выхода",
      "signout": "Выйти"
    },
    "nav": {
      "home": "Главная",
      "evns": "Расчёты",
      "profile": "Я",
      "contacts": "Друзья"
    },
    "terms": "Условия и положения",
    "privacy": "Политика конфиденциальности",
    "madeBy": "Сделано",
    "profile": {
      "title": "Мой профиль",
      "language": {
        "title": "Язык",
        "description": "Это не влияет на распознавание чеков. Мы и так понимаем там большинство языков."
      }
    },
    "form": {
      "enterName": "Введите имя"
    },
    "copyright": "© Seed.me, 2024–2025",
    "onboarding": {
      "name": {
        "title": "Личный штрих",
        "description": "Ваше имя, как оно будет отображаться"
      }
    },
    "contacts": {
      "title": "Друзья",
      "empty": {
        "title": "Здесь одиноко",
        "description": "Добавьте друзей вручную или пригласите людей",
        "invite": {
          "share": "Пригласить друзей",
          "qr": "Пригласить по QR-коду"
        }
      }
    }
  },
  "sw-TZ": {
    "native": "Kiswahili",
    "locale": "sw-TZ",
    "actions": {
      "continue": "Endelea",
      "holdToLogout": "Shikilia ili utoke",
      "signout": "Ondoka"
    },
    "nav": {
      "home": "Mwanzo",
      "evns": "Marejesho",
      "profile": "Mimi",
      "contacts": "Marafiki"
    },
    "terms": "Sheria na Masharti",
    "privacy": "Sera ya Faragha",
    "madeBy": "Imetengenezwa na",
    "profile": {
      "title": "Wasifu wangu",
      "language": {
        "title": "Lugha",
        "description": "Hili haiathiri utambuzi wa hundi. Hata hivyo, tunaelewa lugha nyingi hapo."
      }
    },
    "form": {
      "enterName": "Weka jina"
    },
    "copyright": "© Seed.me, 2024-2025",
    "onboarding": {
      "name": {
        "title": "Mguso wa kibinafsi",
        "description": "Jina lako litakavyoonekana"
      }
    },
    "contacts": {
      "title": "Marafiki",
      "empty": {
        "title": "Hapa ni upweke",
        "description": "Ongeza marafiki mwenyewe au alika watu",
        "invite": {
          "share": "Alika marafiki",
          "qr": "Alika kwa kutumia msimbo wa QR"
        }
      }
    }
  },
  "tr-TR": {
    "native": "Türkçe",
    "locale": "tr-TR",
    "actions": {
      "continue": "Devam Et",
      "holdToLogout": "Çıkış yapmak için basılı tutun",
      "signout": "Oturumu kapat"
    },
    "nav": {
      "home": "Ana Sayfa",
      "evns": "Hesaplaşma",
      "profile": "Ben",
      "contacts": "Arkadaşlar"
    },
    "terms": "Şartlar ve Koşullar",
    "privacy": "Gizlilik Politikası",
    "madeBy": "Tarafından yapıldı",
    "profile": {
      "title": "Profilim",
      "language": {
        "title": "Dil",
        "description": "Bu, çek tanımayı etkilemez. Zaten oradaki dillerin çoğunu anlıyoruz."
      }
    },
    "form": {
      "enterName": "İsim girin"
    },
    "copyright": "© Seed.me, 2024-2025",
    "onboarding": {
      "name": {
        "title": "Kişisel dokunuş",
        "description": "Adınızın görüneceği şekliyle"
      }
    },
    "contacts": {
      "title": "Arkadaşlar",
      "empty": {
        "title": "Burası yalnız",
        "description": "Arkadaşları manuel olarak ekleyin veya kişileri davet edin",
        "invite": {
          "share": "Arkadaşlarını davet et",
          "qr": "QR kod ile davet et"
        }
      }
    }
  },
  "uk-UA": {
    "native": "Українська",
    "locale": "uk-UA",
    "actions": {
      "continue": "Продовжити",
      "holdToLogout": "Утримуйте, щоб вийти",
      "signout": "Вийти"
    },
    "nav": {
      "home": "Головна",
      "evns": "Розрахунок",
      "profile": "Я",
      "contacts": "Друзі"
    },
    "terms": "Умови та положення",
    "privacy": "Політика конфіденційності",
    "madeBy": "Створено",
    "profile": {
      "title": "Мій профіль",
      "language": {
        "title": "Мова",
        "description": "Це не впливає на розпізнавання чеків. Ми й так розуміємо там більшість мов."
      }
    },
    "form": {
      "enterName": "Введіть ім’я"
    },
    "copyright": "© Seed.me, 2024–2025",
    "onboarding": {
      "name": {
        "title": "Особистий штрих",
        "description": "Ваше ім’я, як воно буде відображатися"
      }
    },
    "contacts": {
      "title": "Друзі",
      "empty": {
        "title": "Тут самотньо",
        "description": "Додайте друзів вручну або запросіть людей",
        "invite": {
          "share": "Запросити друзів",
          "qr": "Запросити за QR-кодом"
        }
      }
    }
  },
  "zh-CN": {
    "native": "中文",
    "locale": "zh-CN",
    "actions": {
      "continue": "继续",
      "holdToLogout": "按住退出登录",
      "signout": "退出登录"
    },
    "nav": {
      "home": "首页",
      "evns": "结算",
      "profile": "我",
      "contacts": "朋友"
    },
    "terms": "条款与条件",
    "privacy": "隐私政策",
    "madeBy": "由...制作",
    "profile": {
      "title": "我的个人资料",
      "language": {
        "title": "语言",
        "description": "这不会影响支票识别。反正我们在那里大多数语言都能理解。"
      }
    },
    "form": {
      "enterName": "输入姓名"
    },
    "copyright": "© Seed.me，2024-2025",
    "onboarding": {
      "name": {
        "title": "个性化体验",
        "description": "您的姓名将被显示为"
      }
    },
    "contacts": {
      "title": "朋友",
      "empty": {
        "title": "这里很孤独",
        "description": "手动添加好友或邀请他人",
        "invite": {
          "share": "邀请朋友",
          "qr": "通过二维码邀请"
        }
      }
    }
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];
