// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("./types").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "reduction": {
      "switch": {
        "label": "الديون الذكية",
        "description": "يُدمج الديون بين الأعضاء حتى تقل الحاجة لعدد المدفوعات لتسوية كل شيء. لا يدفع أحد أكثر أو أقل — هذا فقط يقلل من عدد المعاملات."
      }
    },
    "expenses": {
      "title": "الفعاليات",
      "empty": "لا توجد مصروفات مشتركة حتى الآن."
    },
    "balance": "رصيدك",
    "cover": "صورة الغلاف",
    "details": {
      "total": "إجمالي المصروف",
      "paid": "لقد دفعت"
    },
    "editor": {
      "settings": "الإعدادات"
    },
    "selector": {
      "none": "تقسيم"
    }
  },
  "de-DE": {
    "reduction": {
      "switch": {
        "label": "Intelligente Schulden",
        "description": "Fasst Schulden zwischen Mitgliedern zusammen, sodass weniger Zahlungen nötig sind, um alles auszugleichen. Niemand zahlt mehr oder weniger – es werden einfach weniger Transaktionen nötig."
      }
    },
    "expenses": {
      "title": "Veranstaltungen",
      "empty": "Bisher keine geteilten Ausgaben."
    },
    "balance": "Dein Kontostand",
    "cover": "Titelbild",
    "details": {
      "total": "Insgesamt ausgegeben",
      "paid": "Du hast bezahlt"
    },
    "editor": {
      "settings": "Einstellungen"
    },
    "selector": {
      "none": "Aufteilen"
    }
  },
  "en-US": {
    "reduction": {
      "switch": {
        "label": "Smart Debts",
        "description": "Merges debts between members so fewer payments are needed to settle everything. No one pays more or less — it just reduces the number of transactions."
      }
    },
    "expenses": {
      "title": "Events",
      "empty": "No shared expenses so far."
    },
    "balance": "Your balance",
    "cover": "Cover Photo",
    "details": {
      "total": "Total spent",
      "paid": "You’ve paid"
    },
    "editor": {
      "settings": "Settings"
    },
    "selector": {
      "none": "Split"
    }
  },
  "es-ES": {
    "reduction": {
      "switch": {
        "label": "Deudas inteligentes",
        "description": "Agrupa las deudas entre los miembros para que se necesiten menos pagos al saldar todo. Nadie paga más ni menos: solo se reduce la cantidad de transacciones."
      }
    },
    "expenses": {
      "title": "Eventos",
      "empty": "Aún no hay gastos compartidos."
    },
    "balance": "Tu saldo",
    "cover": "Foto de portada",
    "details": {
      "total": "Total gastado",
      "paid": "Has pagado"
    },
    "editor": {
      "settings": "Configuración"
    },
    "selector": {
      "none": "Dividir"
    }
  },
  "fr-FR": {
    "reduction": {
      "switch": {
        "label": "Dettes intelligentes",
        "description": "Fusionne les dettes entre membres afin de réduire le nombre de paiements nécessaires pour tout régler. Personne ne paie plus ou moins — cela réduit simplement le nombre de transactions."
      }
    },
    "expenses": {
      "title": "Événements",
      "empty": "Aucune dépense partagée pour le moment."
    },
    "balance": "Votre solde",
    "cover": "Photo de couverture",
    "details": {
      "total": "Total dépensé",
      "paid": "Tu as payé"
    },
    "editor": {
      "settings": "Paramètres"
    },
    "selector": {
      "none": "Partager"
    }
  },
  "hi-IN": {
    "reduction": {
      "switch": {
        "label": "स्मार्ट कर्ज",
        "description": "सदस्यों के बीच कर्ज को एकीकृत करता है ताकि सब कुछ चुकाने के लिए कम भुगतान करने पड़ें। कोई ज्यादा या कम नहीं देता — इससे सिर्फ लेन-देन की संख्या घटती है।"
      }
    },
    "expenses": {
      "title": "इवेंट्स",
      "empty": "अभी तक कोई साझा खर्च नहीं हैं।"
    },
    "balance": "आपकी शेष राशि",
    "cover": "कवर फोटो",
    "details": {
      "total": "कुल खर्च",
      "paid": "तुमने भुगतान किया है"
    },
    "editor": {
      "settings": "सेटिंग्स"
    },
    "selector": {
      "none": "बांटो"
    }
  },
  "it-IT": {
    "reduction": {
      "switch": {
        "label": "Debiti smart",
        "description": "Unisce i debiti tra i membri così sono necessari meno pagamenti per saldare tutto. Nessuno paga più o meno — si riduce solo il numero di transazioni."
      }
    },
    "expenses": {
      "title": "Eventi",
      "empty": "Nessuna spesa condivisa finora."
    },
    "balance": "Il tuo saldo",
    "cover": "Foto di copertina",
    "details": {
      "total": "Totale speso",
      "paid": "Hai pagato"
    },
    "editor": {
      "settings": "Impostazioni"
    },
    "selector": {
      "none": "Dividi"
    }
  },
  "ja-JP": {
    "reduction": {
      "switch": {
        "label": "スマート債務",
        "description": "メンバー間の借金をまとめて、すべてを精算するために必要な支払い回数を減らします。誰かが多く払ったり少なく払ったりすることはなく、単に取引の数が減るだけです。"
      }
    },
    "expenses": {
      "title": "イベント",
      "empty": "まだ共有された支出はありません。"
    },
    "balance": "あなたの残高",
    "cover": "カバー写真",
    "details": {
      "total": "合計支出",
      "paid": "あなたが支払いました"
    },
    "editor": {
      "settings": "設定"
    },
    "selector": {
      "none": "分ける"
    }
  },
  "ko-KR": {
    "reduction": {
      "switch": {
        "label": "스마트 부채",
        "description": "회원 간의 빚을 합쳐서 모든 정산에 필요한 결제 횟수를 줄여줍니다. 누구도 더 많이 내거나 덜 내지 않으며, 단순히 거래 횟수가 줄어듭니다."
      }
    },
    "expenses": {
      "title": "이벤트",
      "empty": "아직 공동 지출이 없습니다."
    },
    "balance": "내 잔액",
    "cover": "커버 사진",
    "details": {
      "total": "총 지출",
      "paid": "네가 결제함"
    },
    "editor": {
      "settings": "설정"
    },
    "selector": {
      "none": "나누기"
    }
  },
  "nl-NL": {
    "reduction": {
      "switch": {
        "label": "Slimme schulden",
        "description": "Voegt schulden tussen leden samen zodat er minder betalingen nodig zijn om alles af te rekenen. Niemand betaalt meer of minder — het vermindert alleen het aantal transacties."
      }
    },
    "expenses": {
      "title": "Evenementen",
      "empty": "Nog geen gedeelde uitgaven."
    },
    "balance": "Jouw saldo",
    "cover": "Omslagfoto",
    "details": {
      "total": "Totaal uitgegeven",
      "paid": "Je hebt betaald"
    },
    "editor": {
      "settings": "Instellingen"
    },
    "selector": {
      "none": "Verdelen"
    }
  },
  "ru-RU": {
    "reduction": {
      "switch": {
        "label": "Умные долги",
        "description": "Объединяет долги между участниками, чтобы для полного расчёта требовалось меньше платежей. Никто не платит больше или меньше — просто сокращается количество транзакций."
      }
    },
    "expenses": {
      "title": "События",
      "empty": "Пока нет общих расходов."
    },
    "balance": "Ваш баланс",
    "cover": "Обложка",
    "details": {
      "total": "Всего потрачено",
      "paid": "Ты заплатил(а)"
    },
    "editor": {
      "settings": "Настройки"
    },
    "selector": {
      "none": "Разделить"
    }
  },
  "sw-TZ": {
    "reduction": {
      "switch": {
        "label": "Mikopo mahiri",
        "description": "Inaunganisha madeni kati ya wanachama ili malipo machache yahitajike kumaliza kila kitu. Hakuna anayelipa zaidi au pungufu — inapunguza tu idadi ya miamala."
      }
    },
    "expenses": {
      "title": "Matukio",
      "empty": "Hakuna gharama zilizoshirikiwa hadi sasa."
    },
    "balance": "Salio lako",
    "cover": "Picha ya jalada",
    "details": {
      "total": "Jumla iliyotumika",
      "paid": "Umelipa"
    },
    "editor": {
      "settings": "Mipangilio"
    },
    "selector": {
      "none": "Gawanya"
    }
  },
  "tr-TR": {
    "reduction": {
      "switch": {
        "label": "Akıllı Borçlar",
        "description": "Üyeler arasındaki borçları birleştirir, böylece her şeyi kapatmak için daha az ödeme gerekir. Kimse daha fazla ya da daha az ödemez — sadece işlem sayısı azalır."
      }
    },
    "expenses": {
      "title": "Etkinlikler",
      "empty": "Henüz paylaşılan bir harcama yok."
    },
    "balance": "Bakiyeniz",
    "cover": "Kapak fotoğrafı",
    "details": {
      "total": "Toplam harcanan",
      "paid": "Sen ödedin"
    },
    "editor": {
      "settings": "Ayarlar"
    },
    "selector": {
      "none": "Bölüş"
    }
  },
  "uk-UA": {
    "reduction": {
      "switch": {
        "label": "Розумні борги",
        "description": "Об’єднує борги між учасниками, щоб для врегулювання всього потрібно було менше платежів. Ніхто не платить більше чи менше — це лише скорочує кількість транзакцій."
      }
    },
    "expenses": {
      "title": "Події",
      "empty": "Поки що немає спільних витрат."
    },
    "balance": "Ваш баланс",
    "cover": "Обкладинка",
    "details": {
      "total": "Всього витрачено",
      "paid": "Ти заплатив(ла)"
    },
    "editor": {
      "settings": "Налаштування"
    },
    "selector": {
      "none": "Розділити"
    }
  },
  "zh-CN": {
    "reduction": {
      "switch": {
        "label": "智能债务",
        "description": "合并成员之间的债务，从而减少结算所有账目所需的付款次数。没有人会多付或少付——只是减少了交易笔数。"
      }
    },
    "expenses": {
      "title": "活动",
      "empty": "目前还没有共享支出。"
    },
    "balance": "你的余额",
    "cover": "封面照片",
    "details": {
      "total": "总支出",
      "paid": "你已付款"
    },
    "editor": {
      "settings": "设置"
    },
    "selector": {
      "none": "拆分"
    }
  }
};
/** @type {import("./types").Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];

