// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("./types").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "settings": {
      "title": "الإشعارات",
      "description": "سنقوم بإبلاغك عندما يحدث أمر مهم",
      "contacts": {
        "title": "الأصدقاء",
        "description": "طلبات الصداقة والاتصالات"
      },
      "groups": {
        "title": "المجموعات",
        "description": "دعوات المجموعة والانضمامات"
      },
      "expenses": {
        "description": "النفقات المشتركة وأنشطة المال",
        "title": "المصروفات"
      }
    },
    "permission": {
      "prompt": "قم بتفعيل الإشعارات للحصول على تحديثات فورية حول النفقات والإيصالات والنشاطات الأخرى.",
      "button": "تفعيل الإشعارات",
      "dismiss": "تجاهل",
      "dismissed": "يمكنك دائمًا تفعيل الإشعارات لاحقًا من إعدادات حسابك.",
      "later": "افعل ذلك لاحقًا",
      "comment": "نحن لا نستخدم الإشعارات لأغراض تسويقية."
    }
  },
  "de-DE": {
    "settings": {
      "title": "Benachrichtigungen",
      "description": "Wir benachrichtigen dich, wenn etwas Wichtiges passiert",
      "contacts": {
        "title": "Freunde",
        "description": "Freundschaftsanfragen und Verbindungen"
      },
      "groups": {
        "title": "Gruppen",
        "description": "Gruppeneinladungen und Beitritte"
      },
      "expenses": {
        "description": "Geteilte Ausgaben und Zahlungsaktivitäten",
        "title": "Ausgaben"
      }
    },
    "permission": {
      "prompt": "Aktiviere Benachrichtigungen, um sofort über Ausgaben, Quittungen und andere Aktivitäten informiert zu werden.",
      "button": "Benachrichtigungen aktivieren",
      "dismiss": "Schließen",
      "dismissed": "Du kannst Benachrichtigungen jederzeit später in deinen Kontoeinstellungen aktivieren.",
      "later": "Später erledigen",
      "comment": "Wir verwenden Benachrichtigungen nicht für Marketingzwecke."
    }
  },
  "en-US": {
    "settings": {
      "title": "Notifications",
      "description": "We’ll notify you when something important happens",
      "contacts": {
        "title": "Friends",
        "description": "Friend requests and connections"
      },
      "groups": {
        "title": "Groups",
        "description": "Group invites and joins"
      },
      "expenses": {
        "description": "Shared expenses and money activity",
        "title": "Expenses"
      }
    },
    "permission": {
      "prompt": "Turn on notifications to get instant updates about expenses, receipts, and other activity.",
      "button": "Enable notifications",
      "dismiss": "Dismiss",
      "dismissed": "You can always enable notifications later in your account settings.",
      "later": "Do it later",
      "comment": "We do not use notifications for marketing."
    }
  },
  "es-ES": {
    "settings": {
      "title": "Notificaciones",
      "description": "Te avisaremos cuando suceda algo importante",
      "contacts": {
        "title": "Amigos",
        "description": "Solicitudes de amistad y conexiones"
      },
      "groups": {
        "title": "Grupos",
        "description": "Invitaciones y uniones de grupo"
      },
      "expenses": {
        "description": "Gastos compartidos y actividad de dinero",
        "title": "Gastos"
      }
    },
    "permission": {
      "prompt": "Activa las notificaciones para recibir actualizaciones instantáneas sobre gastos, recibos y otras actividades.",
      "button": "Activar notificaciones",
      "dismiss": "Descartar",
      "dismissed": "Siempre puedes activar las notificaciones más tarde en la configuración de tu cuenta.",
      "later": "Hazlo más tarde",
      "comment": "No usamos las notificaciones con fines de marketing."
    }
  },
  "fr-FR": {
    "settings": {
      "title": "Notifications",
      "description": "Nous vous avertirons si quelque chose d’important se produit",
      "contacts": {
        "title": "Amis",
        "description": "Invitations et relations"
      },
      "groups": {
        "title": "Groupes",
        "description": "Invitations et adhésions au groupe"
      },
      "expenses": {
        "description": "Dépenses partagées et activités d’argent",
        "title": "Dépenses"
      }
    },
    "permission": {
      "prompt": "Activez les notifications pour recevoir des mises à jour instantanées sur les dépenses, les reçus et d'autres activités.",
      "button": "Activer les notifications",
      "dismiss": "Fermer",
      "dismissed": "Vous pourrez toujours activer les notifications plus tard dans les paramètres de votre compte.",
      "later": "Fais-le plus tard",
      "comment": "Nous n'utilisons pas les notifications à des fins de marketing."
    }
  },
  "hi-IN": {
    "settings": {
      "title": "सूचनाएं",
      "description": "जब कुछ महत्वपूर्ण होगा, तो हम आपको सूचित करेंगे",
      "contacts": {
        "title": "मित्र",
        "description": "मित्र अनुरोध और संपर्क"
      },
      "groups": {
        "title": "समूह",
        "description": "समूह निमंत्रण और जुड़ना"
      },
      "expenses": {
        "description": "साझा खर्च और पैसों की गतिविधि",
        "title": "खर्चे"
      }
    },
    "permission": {
      "prompt": "खर्च, रसीदों और अन्य गतिविधियों के बारे में तुरंत अपडेट पाने के लिए नोटिफिकेशन चालू करें।",
      "button": "नोटिफिकेशन सक्षम करें",
      "dismiss": "खारिज करें",
      "dismissed": "आप कभी भी अपने खाते की सेटिंग्स में बाद में सूचनाएं चालू कर सकते हैं।",
      "later": "इसे बाद में करें",
      "comment": "हम मार्केटिंग के लिए नोटिफिकेशन का इस्तेमाल नहीं करते हैं।"
    }
  },
  "it-IT": {
    "settings": {
      "title": "Notifiche",
      "description": "Ti avviseremo quando succederà qualcosa di importante",
      "contacts": {
        "title": "Amici",
        "description": "Richieste di amicizia e connessioni"
      },
      "groups": {
        "title": "Gruppi",
        "description": "Inviti e adesioni al gruppo"
      },
      "expenses": {
        "description": "Spese condivise e attività finanziaria",
        "title": "Spese"
      }
    },
    "permission": {
      "prompt": "Attiva le notifiche per ricevere aggiornamenti istantanei su spese, ricevute e altre attività.",
      "button": "Attiva le notifiche",
      "dismiss": "Chiudi",
      "dismissed": "Puoi sempre attivare le notifiche in un secondo momento dalle impostazioni del tuo account.",
      "later": "Fallo dopo",
      "comment": "Non utilizziamo le notifiche per scopi di marketing."
    }
  },
  "ja-JP": {
    "settings": {
      "title": "通知",
      "description": "重要なことが起きたときにお知らせします",
      "contacts": {
        "title": "友達",
        "description": "友達リクエストとつながり"
      },
      "groups": {
        "title": "グループ",
        "description": "グループの招待と参加"
      },
      "expenses": {
        "description": "共有の支出とお金の履歴",
        "title": "支出"
      }
    },
    "permission": {
      "prompt": "通知をオンにして、経費、領収書、その他のアクティビティに関する即時アップデートを受け取りましょう。",
      "button": "通知を有効にする",
      "dismiss": "閉じる",
      "dismissed": "通知は後からアカウント設定でいつでも有効にできます。",
      "later": "あとでやる",
      "comment": "通知はマーケティング目的には使用しません。"
    }
  },
  "ko-KR": {
    "settings": {
      "title": "알림",
      "description": "중요한 일이 발생하면 알려드리겠습니다",
      "contacts": {
        "title": "친구",
        "description": "친구 요청 및 연결"
      },
      "groups": {
        "title": "그룹",
        "description": "그룹 초대 및 가입"
      },
      "expenses": {
        "description": "공동 지출 및 금전 활동",
        "title": "지출"
      }
    },
    "permission": {
      "prompt": "알림을 켜서 비용, 영수증 및 기타 활동에 대한 즉각적인 업데이트를 받아보세요.",
      "button": "알림 활성화",
      "dismiss": "닫기",
      "dismissed": "알림은 나중에 계정 설정에서 언제든지 활성화할 수 있습니다.",
      "later": "나중에 하기",
      "comment": "저희는 마케팅을 위해 알림을 사용하지 않습니다."
    }
  },
  "nl-NL": {
    "settings": {
      "title": "Meldingen",
      "description": "We laten het je weten als er iets belangrijks gebeurt",
      "contacts": {
        "title": "Vrienden",
        "description": "Vriendschapsverzoeken en connecties"
      },
      "groups": {
        "title": "Groepen",
        "description": "Groepsuitnodigingen en -deelname"
      },
      "expenses": {
        "description": "Gedeelde uitgaven en geldactiviteiten",
        "title": "Uitgaven"
      }
    },
    "permission": {
      "prompt": "Zet meldingen aan om direct updates te krijgen over uitgaven, bonnen en andere activiteiten.",
      "button": "Meldingen inschakelen",
      "dismiss": "Sluiten",
      "dismissed": "Je kunt meldingen later altijd inschakelen via je accountinstellingen.",
      "later": "Later doen",
      "comment": "Wij gebruiken meldingen niet voor marketingdoeleinden."
    }
  },
  "ru-RU": {
    "settings": {
      "title": "Уведомления",
      "description": "Мы уведомим вас, когда произойдет что-то важное",
      "contacts": {
        "title": "Друзья",
        "description": "Запросы в друзья и связи"
      },
      "groups": {
        "title": "Группы",
        "description": "Приглашения и вступления в группу"
      },
      "expenses": {
        "description": "Совместные расходы и денежная активность",
        "title": "Расходы"
      }
    },
    "permission": {
      "prompt": "Включите уведомления, чтобы получать мгновенные обновления о расходах, чеках и другой активности.",
      "button": "Включить уведомления",
      "dismiss": "Закрыть",
      "dismissed": "Вы всегда сможете включить уведомления позже в настройках аккаунта.",
      "later": "Сделать позже",
      "comment": "Мы не используем уведомления для маркетинга."
    }
  },
  "sw-TZ": {
    "settings": {
      "title": "Taarifa",
      "description": "Tutakujulisha kunapotokea jambo muhimu",
      "contacts": {
        "title": "Marafiki",
        "description": "Ombi za urafiki na muunganiko"
      },
      "groups": {
        "title": "Makundi",
        "description": "Mialiko na ujiungaji wa kikundi"
      },
      "expenses": {
        "description": "Matumizi ya pamoja na shughuli za fedha",
        "title": "Matumizi"
      }
    },
    "permission": {
      "prompt": "Washa arifa ili upate masasisho ya papo hapo kuhusu matumizi, risiti na shughuli nyingine.",
      "button": "Washa arifa",
      "dismiss": "Funga",
      "dismissed": "Unaweza kuwasha arifa wakati wowote baadaye katika mipangilio ya akaunti yako.",
      "later": "Fanya baadaye",
      "comment": "Hatutumii arifa kwa madhumuni ya uuzaji."
    }
  },
  "tr-TR": {
    "settings": {
      "title": "Bildirimler",
      "description": "Önemli bir şey olduğunda sana bildiririz",
      "contacts": {
        "title": "Arkadaşlar",
        "description": "Arkadaşlık istekleri ve bağlantılar"
      },
      "groups": {
        "title": "Gruplar",
        "description": "Grup davetleri ve katılımlar"
      },
      "expenses": {
        "description": "Paylaşılan harcamalar ve para hareketleri",
        "title": "Giderler"
      }
    },
    "permission": {
      "prompt": "Giderler, makbuzlar ve diğer aktivitelerle ilgili anlık güncellemeler almak için bildirimleri açın.",
      "button": "Bildirimleri etkinleştir",
      "dismiss": "Kapat",
      "dismissed": "Bildirimleri dilediğin zaman hesap ayarlarından etkinleştirebilirsin.",
      "later": "Daha sonra yap",
      "comment": "Bildirimleri pazarlama amacıyla kullanmıyoruz."
    }
  },
  "uk-UA": {
    "settings": {
      "title": "Сповіщення",
      "description": "Ми повідомимо вас, коли станеться щось важливе",
      "contacts": {
        "title": "Друзі",
        "description": "Запити на дружбу та зв’язки"
      },
      "groups": {
        "title": "Групи",
        "description": "Запрошення та приєднання до групи"
      },
      "expenses": {
        "description": "Спільні витрати та грошова активність",
        "title": "Витрати"
      }
    },
    "permission": {
      "prompt": "Увімкніть сповіщення, щоб миттєво отримувати оновлення про витрати, чеки та іншу активність.",
      "button": "Увімкнути сповіщення",
      "dismiss": "Закрити",
      "dismissed": "Ви завжди зможете ввімкнути сповіщення пізніше в налаштуваннях облікового запису.",
      "later": "Зробити пізніше",
      "comment": "Ми не використовуємо сповіщення для маркетингових цілей."
    }
  },
  "zh-CN": {
    "settings": {
      "title": "通知",
      "description": "当有重要事项发生时，我们会通知你",
      "contacts": {
        "title": "朋友",
        "description": "好友请求和连接"
      },
      "groups": {
        "title": "群组",
        "description": "群组邀请和加入"
      },
      "expenses": {
        "description": "共享支出与资金活动",
        "title": "支出"
      }
    },
    "permission": {
      "prompt": "开启通知，第一时间获取有关支出、收据及其他活动的更新。",
      "button": "启用通知",
      "dismiss": "关闭",
      "dismissed": "你可以稍后在账户设置中随时开启通知。",
      "later": "稍后再做",
      "comment": "我们不会将通知用于营销目的。"
    }
  }
};
/** @type {import("./types").Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];

