// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("./types").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "settings": {
      "title": "الإشعارات",
      "description": "سنقوم بإبلاغك عندما يحدث أمر مهم",
      "contacts": {
        "title": "الأصدقاء",
        "description": "طلبات الصداقة والاتصالات"
      },
      "groups": {
        "title": "المجموعات",
        "description": "دعوات المجموعة والانضمامات"
      },
      "expenses": {
        "description": "النفقات المشتركة وأنشطة المال",
        "title": "المصروفات"
      }
    },
    "permission": {
      "prompt": "احصل على تحديثات فورية عندما يضيف الأصدقاء إيصالات ونفقات مشتركة. فعّل الإشعارات على الجهاز حتى لا يفوتك أي شيء. لا نستخدم الإشعارات لأغراض تسويقية.",
      "button": "تفعيل الإشعارات",
      "dismiss": "تجاهل",
      "dismissed": "يمكنك تفعيل الإشعارات في ملفك الشخصي في أي وقت.",
      "later": "افعل ذلك لاحقًا"
    }
  },
  "de-DE": {
    "settings": {
      "title": "Benachrichtigungen",
      "description": "Wir benachrichtigen dich, wenn etwas Wichtiges passiert",
      "contacts": {
        "title": "Freunde",
        "description": "Freundschaftsanfragen und Verbindungen"
      },
      "groups": {
        "title": "Gruppen",
        "description": "Gruppeneinladungen und Beitritte"
      },
      "expenses": {
        "description": "Geteilte Ausgaben und Zahlungsaktivitäten",
        "title": "Ausgaben"
      }
    },
    "permission": {
      "prompt": "Erhalte Echtzeit-Benachrichtigungen, wenn Freunde gemeinsame Belege und Ausgaben hinzufügen. Aktiviere Benachrichtigungen auf deinem Gerät, damit du nichts verpasst. Wir verwenden Benachrichtigungen nicht für Marketingzwecke.",
      "button": "Benachrichtigungen aktivieren",
      "dismiss": "Schließen",
      "dismissed": "Du kannst Benachrichtigungen jederzeit in deinem Profil aktivieren.",
      "later": "Später erledigen"
    }
  },
  "en-US": {
    "settings": {
      "title": "Notifications",
      "description": "We’ll notify you when something important happens",
      "contacts": {
        "title": "Friends",
        "description": "Friend requests and connections"
      },
      "groups": {
        "title": "Groups",
        "description": "Group invites and joins"
      },
      "expenses": {
        "description": "Shared expenses and money activity",
        "title": "Expenses"
      }
    },
    "permission": {
      "prompt": "Get real-time updates when friends add shared receipts and expenses. Turn on on-device notifications so you never miss one. We do not use notifications for marketing.",
      "button": "Enable notifications",
      "dismiss": "Dismiss",
      "dismissed": "You can enable notifications anytime in your profile.",
      "later": "Do it later"
    }
  },
  "es-ES": {
    "settings": {
      "title": "Notificaciones",
      "description": "Te avisaremos cuando suceda algo importante",
      "contacts": {
        "title": "Amigos",
        "description": "Solicitudes de amistad y conexiones"
      },
      "groups": {
        "title": "Grupos",
        "description": "Invitaciones y uniones de grupo"
      },
      "expenses": {
        "description": "Gastos compartidos y actividad de dinero",
        "title": "Gastos"
      }
    },
    "permission": {
      "prompt": "Recibe actualizaciones en tiempo real cuando tus amigos añadan recibos o gastos compartidos. Activa las notificaciones en tu dispositivo para no perderte nada. No usamos las notificaciones con fines de marketing.",
      "button": "Activar notificaciones",
      "dismiss": "Descartar",
      "dismissed": "Puedes activar las notificaciones en tu perfil en cualquier momento.",
      "later": "Hazlo más tarde"
    }
  },
  "fr-FR": {
    "settings": {
      "title": "Notifications",
      "description": "Nous vous avertirons si quelque chose d’important se produit",
      "contacts": {
        "title": "Amis",
        "description": "Invitations et relations"
      },
      "groups": {
        "title": "Groupes",
        "description": "Invitations et adhésions au groupe"
      },
      "expenses": {
        "description": "Dépenses partagées et activités d’argent",
        "title": "Dépenses"
      }
    },
    "permission": {
      "prompt": "Recevez des mises à jour en temps réel lorsque vos amis ajoutent des reçus et des dépenses partagés. Activez les notifications sur votre appareil pour ne rien manquer. Nous n'utilisons pas les notifications à des fins marketing.",
      "button": "Activer les notifications",
      "dismiss": "Fermer",
      "dismissed": "Vous pouvez activer les notifications à tout moment dans votre profil.",
      "later": "Faire plus tard"
    }
  },
  "hi-IN": {
    "settings": {
      "title": "सूचनाएं",
      "description": "जब कुछ महत्वपूर्ण होगा, तो हम आपको सूचित करेंगे",
      "contacts": {
        "title": "मित्र",
        "description": "मित्र अनुरोध और संपर्क"
      },
      "groups": {
        "title": "समूह",
        "description": "समूह निमंत्रण और जुड़ना"
      },
      "expenses": {
        "description": "साझा खर्च और पैसों की गतिविधि",
        "title": "खर्चे"
      }
    },
    "permission": {
      "prompt": "दोस्त साझा रसीदें और खर्च जोड़ें तो तुरंत अपडेट पाएं। डिवाइस नोटिफिकेशन चालू करें ताकि आप कोई भी अपडेट न चूकें। हम नोटिफिकेशन का इस्तेमाल मार्केटिंग के लिए नहीं करते।",
      "button": "नोटिफिकेशन सक्षम करें",
      "dismiss": "खारिज करें",
      "dismissed": "आप कभी भी अपनी प्रोफ़ाइल में सूचनाएँ चालू कर सकते हैं।",
      "later": "बाद में करें"
    }
  },
  "it-IT": {
    "settings": {
      "title": "Notifiche",
      "description": "Ti avviseremo quando succederà qualcosa di importante",
      "contacts": {
        "title": "Amici",
        "description": "Richieste di amicizia e connessioni"
      },
      "groups": {
        "title": "Gruppi",
        "description": "Inviti e adesioni al gruppo"
      },
      "expenses": {
        "description": "Spese condivise e attività finanziaria",
        "title": "Spese"
      }
    },
    "permission": {
      "prompt": "Ricevi aggiornamenti in tempo reale quando gli amici aggiungono ricevute e spese condivise. Attiva le notifiche sul dispositivo per non perderne nessuna. Non usiamo le notifiche per scopi di marketing.",
      "button": "Attiva le notifiche",
      "dismiss": "Chiudi",
      "dismissed": "Puoi attivare le notifiche in qualsiasi momento nel tuo profilo.",
      "later": "Fallo dopo"
    }
  },
  "ja-JP": {
    "settings": {
      "title": "通知",
      "description": "重要なことが起きたときにお知らせします",
      "contacts": {
        "title": "友達",
        "description": "友達リクエストとつながり"
      },
      "groups": {
        "title": "グループ",
        "description": "グループの招待と参加"
      },
      "expenses": {
        "description": "共有の支出とお金の履歴",
        "title": "支出"
      }
    },
    "permission": {
      "prompt": "友だちが共有レシートや支出を追加した際、リアルタイムで通知を受け取れます。デバイスの通知をオンにして、見逃しを防ぎましょう。通知はマーケティング目的で使用しません。",
      "button": "通知を有効にする",
      "dismiss": "閉じる",
      "dismissed": "通知はいつでもプロフィールで有効にできます。",
      "later": "後でやる"
    }
  },
  "ko-KR": {
    "settings": {
      "title": "알림",
      "description": "중요한 일이 발생하면 알려드리겠습니다",
      "contacts": {
        "title": "친구",
        "description": "친구 요청 및 연결"
      },
      "groups": {
        "title": "그룹",
        "description": "그룹 초대 및 가입"
      },
      "expenses": {
        "description": "공동 지출 및 금전 활동",
        "title": "지출"
      }
    },
    "permission": {
      "prompt": "친구가 공유 영수증이나 비용을 추가하면 실시간 업데이트를 받아보세요. 기기 알림을 켜 두면 빠뜨리는 일이 없습니다. 알림은 마케팅 목적에 사용되지 않습니다.",
      "button": "알림 활성화",
      "dismiss": "닫기",
      "dismissed": "언제든지 프로필에서 알림을 활성화할 수 있습니다.",
      "later": "나중에 하기"
    }
  },
  "nl-NL": {
    "settings": {
      "title": "Meldingen",
      "description": "We laten het je weten als er iets belangrijks gebeurt",
      "contacts": {
        "title": "Vrienden",
        "description": "Vriendschapsverzoeken en connecties"
      },
      "groups": {
        "title": "Groepen",
        "description": "Groepsuitnodigingen en -deelname"
      },
      "expenses": {
        "description": "Gedeelde uitgaven en geldactiviteiten",
        "title": "Uitgaven"
      }
    },
    "permission": {
      "prompt": "Ontvang realtime updates wanneer vrienden gedeelde bonnetjes en uitgaven toevoegen. Zet meldingen op je apparaat aan, zodat je er nooit eentje mist. We gebruiken meldingen niet voor marketing.",
      "button": "Meldingen inschakelen",
      "dismiss": "Sluiten",
      "dismissed": "Je kunt op elk moment meldingen inschakelen in je profiel.",
      "later": "Later doen"
    }
  },
  "ru-RU": {
    "settings": {
      "title": "Уведомления",
      "description": "Мы уведомим вас, когда произойдет что-то важное",
      "contacts": {
        "title": "Друзья",
        "description": "Запросы в друзья и связи"
      },
      "groups": {
        "title": "Группы",
        "description": "Приглашения и вступления в группу"
      },
      "expenses": {
        "description": "Совместные расходы и денежная активность",
        "title": "Расходы"
      }
    },
    "permission": {
      "prompt": "Получайте обновления в реальном времени, когда друзья добавляют общие чеки и расходы. Включите уведомления на устройстве, чтобы ничего не пропустить. Мы не используем уведомления для маркетинга.",
      "button": "Включить уведомления",
      "dismiss": "Закрыть",
      "dismissed": "Вы можете включить уведомления в своём профиле в любое время.",
      "later": "Сделать позже"
    }
  },
  "sw-TZ": {
    "settings": {
      "title": "Taarifa",
      "description": "Tutakujulisha kunapotokea jambo muhimu",
      "contacts": {
        "title": "Marafiki",
        "description": "Ombi za urafiki na muunganiko"
      },
      "groups": {
        "title": "Makundi",
        "description": "Mialiko na ujiungaji wa kikundi"
      },
      "expenses": {
        "description": "Matumizi ya pamoja na shughuli za fedha",
        "title": "Matumizi"
      }
    },
    "permission": {
      "prompt": "Pata masasisho ya papo hapo unapofiwa na marafiki wanapoongeza risiti na gharama za pamoja. Washa arifa kwenye kifaa chako ili usikose hata moja. Hatutumii arifa kwa masuala ya masoko.",
      "button": "Washa arifa",
      "dismiss": "Funga",
      "dismissed": "Unaweza kuwasha arifa wakati wowote kwenye wasifu wako.",
      "later": "Fanya baadaye"
    }
  },
  "tr-TR": {
    "settings": {
      "title": "Bildirimler",
      "description": "Önemli bir şey olduğunda sana bildiririz",
      "contacts": {
        "title": "Arkadaşlar",
        "description": "Arkadaşlık istekleri ve bağlantılar"
      },
      "groups": {
        "title": "Gruplar",
        "description": "Grup davetleri ve katılımlar"
      },
      "expenses": {
        "description": "Paylaşılan harcamalar ve para hareketleri",
        "title": "Giderler"
      }
    },
    "permission": {
      "prompt": "Arkadaşlarınız paylaşılan fiş ve harcamalar eklediğinde anlık güncellemeler alın. Hiçbirini kaçırmamak için cihaz bildirimlerini açın. Bildirimleri pazarlama amaçlı kullanmıyoruz.",
      "button": "Bildirimleri etkinleştir",
      "dismiss": "Kapat",
      "dismissed": "Profilinizde istediğiniz zaman bildirimleri etkinleştirebilirsiniz.",
      "later": "Daha sonra yap"
    }
  },
  "uk-UA": {
    "settings": {
      "title": "Сповіщення",
      "description": "Ми повідомимо вас, коли станеться щось важливе",
      "contacts": {
        "title": "Друзі",
        "description": "Запити на дружбу та зв’язки"
      },
      "groups": {
        "title": "Групи",
        "description": "Запрошення та приєднання до групи"
      },
      "expenses": {
        "description": "Спільні витрати та грошова активність",
        "title": "Витрати"
      }
    },
    "permission": {
      "prompt": "Отримуйте оновлення в реальному часі, коли друзі додають спільні чеки та витрати. Увімкніть сповіщення на пристрої, щоб нічого не пропустити. Ми не використовуємо сповіщення для маркетингу.",
      "button": "Увімкнути сповіщення",
      "dismiss": "Закрити",
      "dismissed": "Ви можете ввімкнути сповіщення у своєму профілі будь-коли.",
      "later": "Зробити пізніше"
    }
  },
  "zh-CN": {
    "settings": {
      "title": "通知",
      "description": "当有重要事项发生时，我们会通知你",
      "contacts": {
        "title": "朋友",
        "description": "好友请求和连接"
      },
      "groups": {
        "title": "群组",
        "description": "群组邀请和加入"
      },
      "expenses": {
        "description": "共享支出与资金活动",
        "title": "支出"
      }
    },
    "permission": {
      "prompt": "当朋友添加共享收据和支出时，实时获取更新。开启设备通知，及时掌握每一条动态。我们不会将通知用于营销目的。",
      "button": "启用通知",
      "dismiss": "关闭",
      "dismissed": "你可以随时在个人资料中启用通知。",
      "later": "稍后再做"
    }
  }
};
/** @type {import("./types").Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];

