// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "groups": {
      "joined": {
        "me": (groupName) => `لقد انضممت إلى ${groupName}`,
        "others": (names, groupName) => `${new Intl.ListFormat("ar", { style: "long", type: "conjunction" }).format(names)} انضم${names.length === 1 ? "/ت" : "وا"} إلى ${groupName}`
      }
    },
    "accounts": {
      "created": {
        "welcome": "مرحبًا بك في Evnly!",
        "hint": "اسحب للإزالة"
      }
    },
    "erase": (n) => `مسح الكل (${n})`
  },
  "de-DE": {
    "groups": {
      "joined": {
        "me": (groupName) => `Du bist ${groupName} beigetreten`,
        "others": (names, groupName) => `${new Intl.ListFormat("de", { style: "long", type: "conjunction" }).format(names)} ${names.length === 1 ? "ist" : "sind"} der Gruppe ${groupName} beigetreten`
      }
    },
    "accounts": {
      "created": {
        "welcome": "Willkommen bei Evnly!",
        "hint": "Zum Entfernen wischen"
      }
    },
    "erase": (n) => `Alle löschen (${n})`
  },
  "en-US": {
    "groups": {
      "joined": {
        "me": (groupName) => `You have joined ${groupName}`,
        "others": (names, groupName) => `${new Intl.ListFormat("en", { style: "long", type: "conjunction" }).format(names)} joined ${groupName}`
      }
    },
    "accounts": {
      "created": {
        "welcome": "Welcome to Evnly!",
        "hint": "Swipe to remove"
      }
    },
    "erase": (n) => `Erase all (${n})`
  },
  "es-ES": {
    "groups": {
      "joined": {
        "me": (groupName) => `Te has unido a ${groupName}`,
        "others": (names, groupName) => `${new Intl.ListFormat("es", { style: "long", type: "conjunction" }).format(names)} se ha${names.length === 1 ? "" : "n"} unido a ${groupName}`
      }
    },
    "accounts": {
      "created": {
        "welcome": "¡Bienvenido a Evnly!",
        "hint": "Desliza para eliminar"
      }
    },
    "erase": (n) => `Borrar todo (${n})`
  },
  "fr-FR": {
    "groups": {
      "joined": {
        "me": (groupName) => `Vous avez rejoint ${groupName}`,
        "others": (names, groupName) => `${new Intl.ListFormat("fr", { style: "long", type: "conjunction" }).format(names)} a${names.length === 1 ? "" : "ont"} rejoint ${groupName}`
      }
    },
    "accounts": {
      "created": {
        "welcome": "Bienvenue chez Evnly !",
        "hint": "Faites glisser pour supprimer"
      }
    },
    "erase": (n) => `Tout effacer (${n})`
  },
  "hi-IN": {
    "groups": {
      "joined": {
        "me": (groupName) => `${groupName} में आप शामिल हो गए हैं`,
        "others": (names, groupName) => `${new Intl.ListFormat("hi", { style: "long", type: "conjunction" }).format(names)} ${names.length === 1 ? "ने" : "ने"} ${groupName} को जॉइन किया`
      }
    },
    "accounts": {
      "created": {
        "welcome": "Evnly में आपका स्वागत है!",
        "hint": "हटाने के लिए स्वाइप करें"
      }
    },
    "erase": (n) => `सभी मिटाएँ (${n})`
  },
  "it-IT": {
    "groups": {
      "joined": {
        "me": (groupName) => `Sei entrato in ${groupName}`,
        "others": (names, groupName) => `${new Intl.ListFormat("it", { style: "long", type: "conjunction" }).format(names)} ha${names.length === 1 ? "" : "nno"} aderito a ${groupName}`
      }
    },
    "accounts": {
      "created": {
        "welcome": "Benvenuto su Evnly!",
        "hint": "Scorri per rimuovere"
      }
    },
    "erase": (n) => `Cancella tutto (${n})`
  },
  "ja-JP": {
    "groups": {
      "joined": {
        "me": (groupName) => `${groupName} に参加しました`,
        "others": (names, groupName) => `${new Intl.ListFormat("ja", { style: "long", type: "conjunction" }).format(names)} が${groupName}に参加しました`
      }
    },
    "accounts": {
      "created": {
        "welcome": "Evnlyへようこそ！",
        "hint": "スワイプして削除"
      }
    },
    "erase": (n) => `すべて消去 (${n})`
  },
  "ko-KR": {
    "groups": {
      "joined": {
        "me": (groupName) => `${groupName}에 참가하셨습니다`,
        "others": (names, groupName) => `${new Intl.ListFormat("ko", { style: "long", type: "conjunction" }).format(names)}님이 ${groupName}에 가입했습니다`
      }
    },
    "accounts": {
      "created": {
        "welcome": "Evnly에 오신 것을 환영합니다!",
        "hint": "삭제하려면 스와이프하세요"
      }
    },
    "erase": (n) => `모두 지우기 (${n})`
  },
  "nl-NL": {
    "groups": {
      "joined": {
        "me": (groupName) => `Je bent lid geworden van ${groupName}`,
        "others": (names, groupName) => `${new Intl.ListFormat("nl", { style: "long", type: "conjunction" }).format(names)} ${names.length === 1 ? "is" : "zijn"} lid geworden van ${groupName}`
      }
    },
    "accounts": {
      "created": {
        "welcome": "Welkom bij Evnly!",
        "hint": "Veeg om te verwijderen"
      }
    },
    "erase": (n) => `Alles wissen (${n})`
  },
  "ru-RU": {
    "groups": {
      "joined": {
        "me": (groupName) => `Вы присоединились к группе ${groupName}`,
        "others": (names, groupName) => `${new Intl.ListFormat("ru", { style: "long", type: "conjunction" }).format(names)} присоединил${names.length === 1 ? "ся" : "ись"} к группе ${groupName}`
      }
    },
    "accounts": {
      "created": {
        "welcome": "Добро пожаловать в Evnly!",
        "hint": "Свайпните, чтобы удалить"
      }
    },
    "erase": (n) => `Удалить всё (${n})`
  },
  "sw-TZ": {
    "groups": {
      "joined": {
        "me": (groupName) => `Umejiunga na ${groupName}`,
        "others": (names, groupName) => `${new Intl.ListFormat("sw", { style: "long", type: "conjunction" }).format(names)} ame${names.length === 1 ? "ji" : "ji"}unga na ${groupName}`
      }
    },
    "accounts": {
      "created": {
        "welcome": "Karibu kwenye Evnly!",
        "hint": "Gusa uondoe"
      }
    },
    "erase": (n) => `Futa vyote (${n})`
  },
  "tr-TR": {
    "groups": {
      "joined": {
        "me": (groupName) => `${groupName} grubuna katıldınız`,
        "others": (names, groupName) => `${new Intl.ListFormat("tr", { style: "long", type: "conjunction" }).format(names)} ${groupName} grubuna katıldı`
      }
    },
    "accounts": {
      "created": {
        "welcome": "Evnly'e hoş geldiniz!",
        "hint": "Kaldırmak için kaydırın"
      }
    },
    "erase": (n) => `Hepsini sil (${n})`
  },
  "uk-UA": {
    "groups": {
      "joined": {
        "me": (groupName) => `Ви приєдналися до ${groupName}`,
        "others": (names, groupName) => `${new Intl.ListFormat("uk", { style: "long", type: "conjunction" }).format(names)} приєдна${names.length === 1 ? "вся" : "лися"} до групи ${groupName}`
      }
    },
    "accounts": {
      "created": {
        "welcome": "Ласкаво просимо до Evnly!",
        "hint": "Проведіть, щоб видалити"
      }
    },
    "erase": (n) => `Видалити все (${n})`
  },
  "zh-CN": {
    "groups": {
      "joined": {
        "me": (groupName) => `您已加入${groupName}`,
        "others": (names, groupName) => `${new Intl.ListFormat("zh-CN", { style: "long", type: "conjunction" }).format(names)}已加入${groupName}`
      }
    },
    "accounts": {
      "created": {
        "welcome": "欢迎来到 Evnly！",
        "hint": "滑动以移除"
      }
    },
    "erase": (n) => `全部清除 (${n})`
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];
