// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import("$lib/intl").Locale, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "promo": {
      "label": "رمز ترويجي"
    },
    "apply": {
      "submit": "استبدال"
    },
    "create": {
      "interval": "الفترة",
      "submit": "إنشاء",
      "intervals": {
        "P1M": "شهر واحد",
        "P3M": "٣ أشهر",
        "P6M": "6 أشهر",
        "P1Y": "سنة واحدة"
      }
    }
  },
  "de-DE": {
    "promo": {
      "label": "Promo-Code"
    },
    "apply": {
      "submit": "Einlösen"
    },
    "create": {
      "interval": "Intervall",
      "submit": "Erstellen",
      "intervals": {
        "P1M": "1 Monat",
        "P3M": "3 Monate",
        "P6M": "6 Monate",
        "P1Y": "1 Jahr"
      }
    }
  },
  "en-US": {
    "promo": {
      "label": "Promo code"
    },
    "apply": {
      "submit": "Redeem"
    },
    "create": {
      "interval": "Interval",
      "submit": "Create",
      "intervals": {
        "P1M": "1 month",
        "P3M": "3 months",
        "P6M": "6 months",
        "P1Y": "1 year"
      }
    }
  },
  "es-ES": {
    "promo": {
      "label": "Código promocional"
    },
    "apply": {
      "submit": "Canjear"
    },
    "create": {
      "interval": "Intervalo",
      "submit": "Crear",
      "intervals": {
        "P1M": "1 mes",
        "P3M": "3 meses",
        "P6M": "6 meses",
        "P1Y": "1 año"
      }
    }
  },
  "fr-FR": {
    "promo": {
      "label": "Code promo"
    },
    "apply": {
      "submit": "Utiliser"
    },
    "create": {
      "interval": "Intervalle",
      "submit": "Créer",
      "intervals": {
        "P1M": "1 mois",
        "P3M": "3 mois",
        "P6M": "6 mois",
        "P1Y": "1 an"
      }
    }
  },
  "hi-IN": {
    "promo": {
      "label": "प्रोमो कोड"
    },
    "apply": {
      "submit": "रिडीम करो"
    },
    "create": {
      "interval": "अवधि",
      "submit": "बनाओ",
      "intervals": {
        "P1M": "1 महीना",
        "P3M": "3 महीने",
        "P6M": "6 महीने",
        "P1Y": "1 साल"
      }
    }
  },
  "it-IT": {
    "promo": {
      "label": "Codice promo"
    },
    "apply": {
      "submit": "Riscatta"
    },
    "create": {
      "interval": "Intervallo",
      "submit": "Crea",
      "intervals": {
        "P1M": "1 mese",
        "P3M": "3 mesi",
        "P6M": "6 mesi",
        "P1Y": "1 anno"
      }
    }
  },
  "ja-JP": {
    "promo": {
      "label": "プロモコード"
    },
    "apply": {
      "submit": "利用する"
    },
    "create": {
      "interval": "間隔",
      "submit": "作成",
      "intervals": {
        "P1M": "1か月",
        "P3M": "3か月",
        "P6M": "6か月",
        "P1Y": "1年"
      }
    }
  },
  "ko-KR": {
    "promo": {
      "label": "프로모션 코드"
    },
    "apply": {
      "submit": "사용하기"
    },
    "create": {
      "interval": "간격",
      "submit": "생성",
      "intervals": {
        "P1M": "1개월",
        "P3M": "3개월",
        "P6M": "6개월",
        "P1Y": "1년"
      }
    }
  },
  "nl-NL": {
    "promo": {
      "label": "Promocode"
    },
    "apply": {
      "submit": "Inwisselen"
    },
    "create": {
      "interval": "Interval",
      "submit": "Aanmaken",
      "intervals": {
        "P1M": "1 maand",
        "P3M": "3 maanden",
        "P6M": "6 maanden",
        "P1Y": "1 jaar"
      }
    }
  },
  "ru-RU": {
    "promo": {
      "label": "Промокод"
    },
    "apply": {
      "submit": "Активировать"
    },
    "create": {
      "interval": "Интервал",
      "submit": "Создать",
      "intervals": {
        "P1M": "1 месяц",
        "P3M": "3 месяца",
        "P6M": "6 месяцев",
        "P1Y": "1 год"
      }
    }
  },
  "sw-TZ": {
    "promo": {
      "label": "Nambari ya promo"
    },
    "apply": {
      "submit": "Tumia"
    },
    "create": {
      "interval": "Kipindi",
      "submit": "Tengeneza",
      "intervals": {
        "P1M": "Mwezi 1",
        "P3M": "miezi 3",
        "P6M": "Miezi 6",
        "P1Y": "mwaka 1"
      }
    }
  },
  "tr-TR": {
    "promo": {
      "label": "Promosyon kodu"
    },
    "apply": {
      "submit": "Kullan"
    },
    "create": {
      "interval": "Aralık",
      "submit": "Oluştur",
      "intervals": {
        "P1M": "1 ay",
        "P3M": "3 ay",
        "P6M": "6 ay",
        "P1Y": "1 yıl"
      }
    }
  },
  "uk-UA": {
    "promo": {
      "label": "Промокод"
    },
    "apply": {
      "submit": "Активувати"
    },
    "create": {
      "interval": "Інтервал",
      "submit": "Створити",
      "intervals": {
        "P1M": "1 місяць",
        "P3M": "3 місяці",
        "P6M": "6 місяців",
        "P1Y": "1 рік"
      }
    }
  },
  "zh-CN": {
    "promo": {
      "label": "优惠码"
    },
    "apply": {
      "submit": "兑换"
    },
    "create": {
      "interval": "周期",
      "submit": "创建",
      "intervals": {
        "P1M": "1个月",
        "P3M": "3个月",
        "P6M": "6个月",
        "P1Y": "1年"
      }
    }
  }
};
