// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "title": "ملاحظات",
    "description": "يسعدنا سماع آرائكم! يرجى مشاركة أفكاركم وملاحظاتكم واقتراحاتكم.",
    "send": "إرسال",
    "form": {
      "email": {
        "description": "يمكنك إدخال بريدك الإلكتروني اختياريًا للحصول على رد.",
        "placeholder": "بريدك الإلكتروني"
      },
      "message": {
        "placeholder": "اكتب رسالتك"
      }
    }
  },
  "de-DE": {
    "title": "Feedback",
    "description": "Wir freuen uns auf Ihr Feedback! Teilen Sie uns gerne Ihre Gedanken, Rückmeldungen und Vorschläge mit.",
    "send": "Absenden",
    "form": {
      "email": {
        "description": "Optional kannst du deine E-Mail angeben, um eine Rückmeldung zu erhalten.",
        "placeholder": "Ihre E-Mail-Adresse"
      },
      "message": {
        "placeholder": "Nachricht eingeben"
      }
    }
  },
  "en-US": {
    "title": "Feedback",
    "description": "We would love to hear from you! Please share your thoughts, feedback, and suggestions.",
    "send": "Send",
    "form": {
      "email": {
        "description": "Optionally, you can provide your email to get a response.",
        "placeholder": "Your email"
      },
      "message": {
        "placeholder": "Type your message"
      }
    }
  },
  "es-ES": {
    "title": "Comentarios",
    "description": "¡Nos encantaría saber tu opinión! Comparte tus ideas, comentarios y sugerencias.",
    "send": "Enviar",
    "form": {
      "email": {
        "description": "Opcionalmente, puedes dejar tu correo electrónico para recibir una respuesta.",
        "placeholder": "Tu correo electrónico"
      },
      "message": {
        "placeholder": "Escribe tu mensaje"
      }
    }
  },
  "fr-FR": {
    "title": "Retour",
    "description": "Nous serions ravis d’avoir votre avis ! Partagez vos pensées, retours et suggestions.",
    "send": "Envoyer",
    "form": {
      "email": {
        "description": "Vous pouvez saisir votre e-mail pour obtenir une réponse (optionnel).",
        "placeholder": "Votre e-mail"
      },
      "message": {
        "placeholder": "Saisissez votre message"
      }
    }
  },
  "hi-IN": {
    "title": "प्रतिपुष्टि",
    "description": "हम आपकी राय जानना चाहेंगे! कृपया अपने विचार, प्रतिक्रियाएँ और सुझाव साझा करें।",
    "send": "भेजें",
    "form": {
      "email": {
        "description": "आप चाहें तो उत्तर पाने के लिए अपना ईमेल दे सकते हैं।",
        "placeholder": "आपका ईमेल"
      },
      "message": {
        "placeholder": "अपना संदेश लिखें"
      }
    }
  },
  "it-IT": {
    "title": "Feedback",
    "description": "Ci farebbe molto piacere sentire la tua opinione! Condividi i tuoi pensieri, feedback e suggerimenti.",
    "send": "Invia",
    "form": {
      "email": {
        "description": "Puoi inserire la tua email, se vuoi ricevere una risposta.",
        "placeholder": "La tua email"
      },
      "message": {
        "placeholder": "Scrivi il tuo messaggio"
      }
    }
  },
  "ja-JP": {
    "title": "フィードバック",
    "description": "ぜひご意見をお聞かせください！ご感想やご意見、ご提案をお寄せください。",
    "send": "送信",
    "form": {
      "email": {
        "description": "返信が必要な場合は、メールアドレスを任意でご入力ください。",
        "placeholder": "あなたのメールアドレス"
      },
      "message": {
        "placeholder": "メッセージを入力してください"
      }
    }
  },
  "ko-KR": {
    "title": "피드백",
    "description": "여러분의 소중한 의견을 기다리고 있어요! 생각, 피드백, 제안을 자유롭게 남겨 주세요.",
    "send": "보내기",
    "form": {
      "email": {
        "description": "답변을 받으시려면 이메일을 선택적으로 입력하실 수 있습니다.",
        "placeholder": "이메일 주소"
      },
      "message": {
        "placeholder": "메시지를 입력하세요"
      }
    }
  },
  "nl-NL": {
    "title": "Feedback",
    "description": "We horen graag van je! Deel je gedachten, feedback en suggesties met ons.",
    "send": "Verzenden",
    "form": {
      "email": {
        "description": "Je kunt optioneel je e-mailadres invullen om een reactie te ontvangen.",
        "placeholder": "Je e-mailadres"
      },
      "message": {
        "placeholder": "Typ je bericht"
      }
    }
  },
  "ru-FU": {
    "title": "Малява",
    "description": "Пиши сюда любую хуйню — всё равно никто это не читает. Но пиши от души.",
    "send": "Закинуть",
    "form": {
      "email": {
        "placeholder": "Твоё мыло (нам не надо)",
        "description": "Если вдруг надеешься, что нам делать больше нехуй, кроме как тебе ответить."
      },
      "message": {
        "placeholder": "Пиши свой высер"
      }
    }
  },
  "ru-RU": {
    "title": "Отзыв",
    "description": "Нам важно ваше мнение! Пожалуйста, поделитесь своими мыслями, отзывами и предложениями.",
    "send": "Отправить",
    "form": {
      "email": {
        "description": "Вы можете указать свой e-mail, чтобы получить ответ (необязательно).",
        "placeholder": "Ваш email"
      },
      "message": {
        "placeholder": "Введите сообщение"
      }
    }
  },
  "sw-TZ": {
    "title": "Maoni",
    "description": "Tunapenda kusikia kutoka kwako! Tafadhali shiriki mawazo, maoni na mapendekezo yako.",
    "send": "Tuma",
    "form": {
      "email": {
        "description": "Kwa hiari, unaweza kutoa barua pepe yako upate majibu.",
        "placeholder": "Barua pepe yako"
      },
      "message": {
        "placeholder": "Andika ujumbe wako"
      }
    }
  },
  "tr-TR": {
    "title": "Geri Bildirim",
    "description": "Sizden haber almak isteriz! Lütfen düşüncelerinizi, geri bildirimlerinizi ve önerilerinizi bizimle paylaşın.",
    "send": "Gönder",
    "form": {
      "email": {
        "description": "İsterseniz yanıt almak için e-posta adresinizi girebilirsiniz.",
        "placeholder": "E-posta adresiniz"
      },
      "message": {
        "placeholder": "Mesajınızı yazın"
      }
    }
  },
  "uk-UA": {
    "title": "Відгук",
    "description": "Ми із задоволенням вислухаємо вашу думку! Будь ласка, поділіться своїми думками, відгуками та пропозиціями.",
    "send": "Відправити",
    "form": {
      "email": {
        "description": "За бажанням ви можете вказати свою електронну пошту, щоб отримати відповідь.",
        "placeholder": "Ваш email"
      },
      "message": {
        "placeholder": "Введіть ваше повідомлення"
      }
    }
  },
  "zh-CN": {
    "title": "反馈",
    "description": "我们非常期待收到您的反馈！欢迎分享您的想法、意见和建议。",
    "send": "发送",
    "form": {
      "email": {
        "description": "如需回复，可选择填写您的邮箱。",
        "placeholder": "你的邮箱"
      },
      "message": {
        "placeholder": "请输入您的消息"
      }
    }
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-FU","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];
