// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<string, import("./types").Dictionary>} */
export const dictionaries = {
  "ar-SA": {
    "message": "هناك خطأ في أحد العناصر التي نقرت عليها",
    "action": "متابعة",
    "background": "على الأقل تبدو الخلفية جميلة"
  },
  "de-DE": {
    "message": "Etwas, das du angeklickt hast, funktioniert nicht",
    "action": "Weiter",
    "background": "Wenigstens sieht der Hintergrund schön aus"
  },
  "en-US": {
    "message": "Something you clicked on is broken",
    "action": "Continue",
    "background": "At least the background looks nice"
  },
  "es-ES": {
    "message": "Algo en lo que has hecho clic no funciona",
    "action": "Continuar",
    "background": "Al menos el fondo se ve bien"
  },
  "fr-FR": {
    "message": "Un élément sur lequel vous avez cliqué ne fonctionne pas",
    "action": "Continuer",
    "background": "Au moins, l’arrière-plan est joli"
  },
  "hi-IN": {
    "message": "जिस चीज़ पर आपने क्लिक किया है, वह ठीक से काम नहीं कर रही है",
    "action": "जारी रखें",
    "background": "कम से कम पृष्ठभूमि तो अच्छी लग रही है"
  },
  "it-IT": {
    "message": "Qualcosa su cui hai cliccato non funziona",
    "action": "Continua",
    "background": "Almeno lo sfondo è bello"
  },
  "ja-JP": {
    "message": "クリックした何かが壊れています",
    "action": "続行",
    "background": "少なくとも背景はきれいに見える"
  },
  "ko-KR": {
    "message": "클릭한 항목에 문제가 발생했습니다",
    "action": "계속",
    "background": "적어도 배경은 예쁘게 보여"
  },
  "nl-NL": {
    "message": "Iets waar je op hebt geklikt werkt niet",
    "action": "Doorgaan",
    "background": "Tenminste ziet de achtergrond er mooi uit"
  },
  "ru-RU": {
    "message": "Что-то, на что вы нажали, не работает",
    "action": "Продолжить",
    "background": "По крайней мере, фон выглядит хорошо"
  },
  "sw-TZ": {
    "message": "Kitu ulichobofya hakifanyi kazi",
    "action": "Endelea",
    "background": "Angalau mandhari inaonekana nzuri"
  },
  "tr-TR": {
    "message": "Tıkladığınız bir şey bozuk",
    "action": "Devam et",
    "background": "En azından arka plan güzel görünüyor"
  },
  "uk-UA": {
    "message": "Щось, на що ви натиснули, не працює",
    "action": "Продовжити",
    "background": "Принаймні фон виглядає гарно"
  },
  "zh-CN": {
    "message": "您点击的某个内容出现了问题",
    "action": "继续",
    "background": "至少背景看起来不错"
  }
};

/** @type {string[]} */
export const locales = ["ar-SA","de-DE","en-US","es-ES","fr-FR","hi-IN","it-IT","ja-JP","ko-KR","nl-NL","ru-RU","sw-TZ","tr-TR","uk-UA","zh-CN"];
